### ISSUE TITLE
dclexperience: radio screen doesn't work 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1000]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

 Radio screen doesn't work .

When it is ON, it should show the chosen station. When it is OFF; it should show OFF. 

Explorer: 

https://github.com/decentraland/unity-explorer/assets/146749313/ab58926e-bc18-4777-976d-da5a509ef675

Alpha: 

https://github.com/decentraland/unity-explorer/assets/146749313/ca37358d-8e59-4084-8e4b-95a095d01766

### **Steps to reproduce:**

  1.Go to alpha explorer
  2.Interact with radio
 

### **Expected behaviour:**

Radio screen should work

### **Current behaviour:**

Radio screen doesn't work

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Fixed on latest 
![image](https://github.com/decentraland/unity-explorer/assets/139157886/411ed967-142a-4c82-81a2-fca9585a0abc)
