### ISSUE TITLE
dclexperience: app crashed once when trying to turn off the radio

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1001]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

A crash took place only once so far when trying to turn off the radio. The button to turn it off didnt seem to work and after having pressed it several times, the app crashed:

https://github.com/decentraland/unity-explorer/assets/146749313/56377ff1-c3d9-498c-8c83-6cb36cc02cea

These are the logs:

[crash when trying to turn off radio.log](https://github.com/decentraland/unity-explorer/files/15241260/crash.when.trying.to.turn.off.radio.log)

### **Steps to reproduce:**

  1. Go to the radio
  2.Try to turn it off
  

### **Expected behaviour:**

Radio should be properly turned off

### **Current behaviour:**

Radio may not turn off and after some tries app may crash

### **Reproduction rate:**
- [ x] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [x ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [x ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Could not reproduce on latest build **0.3.402-g7a23dc7e-main**
