### ISSUE TITLE
Gamepad support extended

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#1006]
Lets adapt the gamepad just to show we have that in mind for the demo
- The camera movement is too slow, including the movement of the mouse

Control Scheme:

Movement > Left Stick
Camera > Right Stick
Change Shoulder > L3
Lock / Unlock Cursor > R3
Run > B (pressed)
Jump > A

Primary action > Click > X
Secondary action > Y
Action 1 > Left Trigger
Action 2 > Right Trigger
Action 3 > Left Shoulder
Action 4 > Right Shoulder

Menu > Start
Settings > Select

UP > Map
Down > Camera Toggle
LEFT > Backpack
RIGHT > Emotes

**Comment by m3taphysics** [comment]
Closing in favor of shape up
