### ISSUE TITLE
[QA] Wind is not longer working

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#1007]
Wind is not working

Attaching the wind object to the character object solved the problem

**Comment by dalkia** [comment]
@m3taphysics I ve checked it, and its working as expected. It was probably fixed [here](https://github.com/decentraland/unity-explorer/pull/1003), can you confirm it?
![image](https://github.com/decentraland/unity-explorer/assets/1999557/db46c8dd-1f11-4d2f-9faf-592aba2c221e)

**Comment by m3taphysics** [comment]
Wind is working great!
