### ISSUE TITLE
dclexperience: Carousel at the spawn fountain is not working 

### ISSUE THREAD

**Issue by popuz** [decentraland/unity-explorer#1027]
### **Issue Description:**
FIXED - Clicking on the Places or Events billboards doesn't play shiny "popup" animation
FIXED - Switching via E/F is not working

- When switching billiboards via right/left 3d-arrows carousel often leaves E/F 3d-buttons in improper places (stuck with old billboard)
- When pressing in between billboard slots you can open the cards from the other billboards that are "hidden" but not disabled.

### **Steps to reproduce:**

  1. /goto dclexperience.dcl.eth
  2. try to click on the Places or Events billoboards - Observe nothing happens
  3. Press E/F - observe it does nothing
  4. Press Right/Left 3d-arrow buttons - observe E/F buttons not changing position to proper places
  
![image](https://github.com/decentraland/unity-explorer/assets/35366872/3302deed-7f42-48ab-95a2-3695f4dab5d3)

Legend to image:
- at the left you see big 3d arrow button
- at the right you see small F 3d-button

### **Expected behaviour:**
2. Bilboard should move in front of you with shiny animation (compare with web-explorer)
3. pressing E/F on keyboard should rotate carousel
4. E/F 3d-arrows should be on the focused billoboard after usage of the 3d big arrows

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [x]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [x] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
At build **0.3.402-g7a23dc7e-main** Currently, it only works by clicking the arrows, the rest of the buttons (E/F clicking and on keyboard) are not working.

**Comment by fcolarich** [comment]
The carrousel is working, but there are some visual issues, also, the slots are not disabled, just hidden from view, causing issues when clicking on between carrousel cards on other carrousels... 
Also the <E and F> buttons are not located correctly consistently...
