### ISSUE TITLE
[QA] Avatar positition stutters when moving on platforms

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#1029]
The avatar shakes up and down when displacing on moving platforms as resolves collisions. Is probable to fall through the platform if the speed is too high.

The character should be parented to the platforms to inherit position?

**Comment by LucasLioyQA** [comment]
This issue is still happening: 


https://github.com/decentraland/unity-explorer/assets/146749313/89e4a554-619e-4a45-beaf-66b113951d54
