### ISSUE TITLE
[QA] Metadynelabs: Delay in World Loading after Using /goto command

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1033]
### **Explorer Alpha build version:**
0.3.383-g852675f1-main

### **Issue Description:**
Sometimes after using the `/goto metadynelabs` command several times in prod , the landscape initially appears, but it takes a few seconds of walking before the world fully loads.

### **Steps to reproduce:**
1. Enter the /goto metadynelabs command.
2. Press the settings menu, exit the game.
3. Repeat step 1 and use the teleport prompt to go to genesis.
4. Repeat step 1.

### **Expected behavior:**
Upon using the `/goto metadynelabs` command, the world should load promptly without any delay

### **Current behavior:**

**issue displays at 1:13**

https://github.com/decentraland/unity-explorer/assets/146741383/cc72f5b7-518a-4bd8-8477-76746bca6955

### **Severity:**
- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [❌ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ❌] Medium
- [ ] Low

### **Platforms / OS:**
- [ ❌] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by anicalbano** [comment]
🟢 Working correctly on build v0.11.0

https://github.com/decentraland/unity-explorer/assets/139157886/bb93bc99-977d-4b2e-9e44-17bc8fd9fee1
