### ISSUE TITLE
[QA] In some places, the grass appears on top of the scene's floor

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1035]
### **Explorer Alpha build version:**
**0.3.383-g852675f1-main**

### **Issue Description:**

Currently there are some scenes in which the grass overlaps the floor defined to the scene.

### **Steps to reproduce:**

  1. Go to 101,-110
  2. Check the grass around the structure.
  3. Walk to 101,-113 and observe the same behavior 

### **Expected behaviour:**
The floor of the scene appears on top 

### **Current behaviour:**
The floor is mixed with the grass

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/d504c737-5685-47d5-b948-660ab2b4a4db)

**Comment by m3taphysics** [comment]
This is now fixed

![image](https://github.com/decentraland/unity-explorer/assets/296469/3158ef20-dcfd-47be-9009-685d3fc580f1)
