### ISSUE TITLE
[QA] When colliding against certain walls or objects, the avatar sometimes gets stuck and cannot move unless changing camera modes

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1046]
### **Explorer Alpha build version:**

0.3.383-g852675f1-main

### **Issue Description:**

When colliding against a columns, walls or certain objects, and putting your hands against the wall, sometimes the character gets stuck there, and you need to change the camera to first person and then go back again to third again to find it possible to move again. This happened to me on 33, -11 while colliding against the column which is in the middle of the stairs shown on the video, and has happened in some other places, too. 

https://github.com/decentraland/unity-explorer/assets/146749313/bbafc7d8-5cc1-4e27-971e-2b98c359d252

### **Steps to reproduce:**

  1. Collide against walls, columns, trees, rocks, etc. and stay there for some seconds 

### **Expected behaviour:**

After colliding against something, you should find it possible to freely move

### **Current behaviour:**

Sometimes the avatar gets stuck there and the user needs to put first person camera and then go back to third to find it possible to move again 

### **Reproduction rate:**
- [ ] < 10%
- [X ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [X ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
I believe this was fixed.
