### ISSUE TITLE
After jumping realms / worlds the shortcut keys will enable the map

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#1056]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
If you jump to a world using /goto world then I think the focus of the chat never changes. Thus when you join that world and use any shortcut keys they are no longer ignored.

### **Steps to reproduce:**

  1. Type /goto dclexperience
  2. Now type "m" once loaded
  3. Notice the map is loaded

### **Expected behaviour:**
Shortcut keys shouldn't occur when using chat.

**Comment by davidejensen** [comment]
I tested this and it is not happening, here is a video:

https://github.com/decentraland/unity-explorer/assets/4254522/c6d2f6d2-4643-4d53-bd45-87a037385ef5

Also tested in the build
