### ISSUE TITLE
Backpack does not load under heavy usage

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#1067]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
Durin a play test with approx 15+ users, after running around the plaza and then attempting to load the backpack  many were unable to load the first page of the backpage and it took quite a long time.

We should review what data we are downloading on the backpack, and check what requests are currently active / stuck in the queue after repeating this behavior. Other requests may be hogging bandwidth?

### **Steps to reproduce:**

  1. Join a scene with many avatars (may not be related to many avatars)
  2. Run around, try load quite a lot of LODs (run via the world)
  3. Try load the backpack.

### **Expected behaviour:**
Backpack should remain slick despite the world loading

**Comment by davidejensen** [comment]
Most likely was related to the request spam issue that was spotted, but after some investigation some issues were found in the backpack requests flow, optimised with this pr: https://github.com/decentraland/unity-explorer/pull/1075
