### ISSUE TITLE
dclexperience: places and events on board do not get highlighted as they do in regular explorer when selecting them 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1069]
### **Explorer Alpha build version:**

(Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Places and events on boards in DCL EXP do not get highlighted as they do in regular explorer when selecting them. 

As such, the 'SELECT' functionality which appears when hovering over the mouse seems not to work. 

Notice the difference: 

Alpha: 

https://github.com/decentraland/unity-explorer/assets/146749313/56e0949d-d839-4e05-b5e2-b94ac100ebf1

Regular explorer: 

https://github.com/decentraland/unity-explorer/assets/146749313/c5465471-3662-4c1e-9b5f-bab6889103a3

### **Steps to reproduce:**

  1. Go to DCL EXP in alpha
  2. Go to any of the three events boards
  3. Select 1 place or event

### **Expected behaviour:**

As per regular explorer, event or place should be highlighted when selecting it 

### **Current behaviour:**

Event or places isn't highlighted when selecting it 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ X] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Still happening on latest build **0.3.402-g7a23dc7e-main**
