### ISSUE TITLE
dclexperience: information not displayed on places and events boards in Alpha 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1076]
### **Explorer Alpha build version:**

(Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Information not displayed on places and events boards in Alpha.

Examples of missing information are: 
Number of likes 
Number in coordinates 
Jump in text in jump in button 
When the event has started 
Numbers in crowd board

Check this issue in Alpha: 

![information no retrieved on board one](https://github.com/decentraland/unity-explorer/assets/146749313/19b2175f-743f-486a-a56e-f52d0903cd6b)
![information no retrieved on board two](https://github.com/decentraland/unity-explorer/assets/146749313/36b21050-fdbe-4ae5-b387-07f9e908b82b)

Check how this is ok in regular explorer: 
![complete info events or places explorer](https://github.com/decentraland/unity-explorer/assets/146749313/f4d6ffd5-4cd7-41f3-92f8-b03e2ce09837)
![complete info two](https://github.com/decentraland/unity-explorer/assets/146749313/3a6d9453-88ed-42ed-9be8-e4a1d0139a0b)

### **Steps to reproduce:**

  1. Go to dcl exp in alpha
  2. Get close to the places and events boards
  

### **Expected behaviour:**

All information should be properly shown

### **Current behaviour:**

Some information is not shown, like: 

Number of likes 
Number in coordinates 
Jump in text in jump in button 
When the event has started 
Numbers in crowd board

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [X ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Still happening on latest build **0.3.402-g7a23dc7e-main**
