### ISSUE TITLE
goerli: crashes when walking into a scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1077]
### **Explorer Alpha build version:**
**0.3.402-g7a23dc7e-main**

### **Issue Description:**

Walking to the scene that has the Power Cube (south west corner, 72,-10 with the debug menu) makes the application crash.

### **Steps to reproduce:**

  1. `/goto goerli`
  2. Walk or teleport to location 72,-10

### **Current behaviour:**
A crash might trigger when going to said location

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [x]  50%
- [ ]  < = 75%
- [ ]  100%

#### **Evidence:**
@nearnshaw tagging Nico in case he can provide logs

**Comment by lorux0** [comment]
The scene uses:
```
PointerEvents.create(staticBase, {
  pointerEvents: [
    {
      eventType: PointerEventType.PET_DOWN,
      eventInfo: {
        showFeedback: false
      }
    }
  ]
})
```
Which in the client eventually ends up in the highlighting feature. This makes the client crash. So far, by disabling this if/else block [here](https://github.com/decentraland/unity-explorer/blob/0e19b9439c4dfc396ff38feb73b4ad17d0eb7d89/Explorer/Assets/DCL/Interaction/Systems/ProcessPointerEventsSystem.cs#L103) the crash stops. I will pass this issue to the highlighting creators.

**Comment by nearnshaw** [comment]
Oh wow nice find
Sounds like the fix shouldn't be so hard 🙏
