### ISSUE TITLE
goerli: no birds on the bird field

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1081]
### **Explorer Alpha build version:**
**0.3.402-g7a23dc7e-main**

### **Issue Description:**

Goerli Plaza Bird Field (74,-2) there should be a field of birds that fly up when you get near. Initial bird positions are set using a raycast to know the height of the ground on each spot.

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/892c80ba-b189-487a-bdae-b86571c87b06)

**Comment by nearnshaw** [comment]
With today's build, birds now do appear, but when I walk up to them they behave super weird and some fly sideways haha
