### ISSUE TITLE
goerli: can't click on the shark model

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1087]
### **Explorer Alpha build version:**

**0.3.402-g7a23dc7e-main**
### **Issue Description:**

`/goto 73,-8` The shark should play a bite animation when clicked, but it's not possible to do so at the moment. The GLTFShape is configured to use the visible mesh as the collider.

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/25b9e694-859a-4f0e-b868-83c3c0815d39)

**Comment by fcolarich** [comment]
The object has no collider! Its not an input issue
