### ISSUE TITLE
goerli: can't claim rewards, the client doesn't recognize being connected to mainnet

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1088]
### **Explorer Alpha build version:**

- **0.3.402-g7a23dc7e-main**
- **v0.11.0**

### **Issue Description:**

`/goto 82,-6` Can't claim any rewards. If I click on the pedestal under the glasses to get my wearable, I see an error message saying that I'm not connected with an ethereum wallet, even though I am.

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/25dca428-e934-4c37-8254-d059c21f13e2)

[Player.log](https://github.com/decentraland/unity-explorer/files/15298710/Player.log)

**Comment by pravusjif** [comment]
This is already happening with unity-renderer...

https://decentraland.org/play/?realm=sdk-team-cdn.decentraland.org%2Fipfs%2Fgoerli-plaza-main-latest&position=82%2C-6

**Comment by popuz** [comment]
re-checked in  unity-renderer - it works there

**Comment by popuz** [comment]
hey @anicalbano , can you also check "simple-giveaway-scene", which is near at `83,-4`.  Seems to be similar logic...

**Comment by anicalbano** [comment]
Still not working on my end. The box drops but I cannot claim the wearable because it's not recognizing the captcha. And for the scene on the ticket, I get the same error message on the build (v0.12)
![image](https://github.com/user-attachments/assets/806c91ff-45cb-40c6-886b-dd53b946b509)
