### ISSUE TITLE
goerli: the avatar is not playing animations on avatar-animation scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1104]
### **Explorer Alpha build version:**
**0.3.402-g7a23dc7e-main**

### **Issue Description:**

At `(80,0)` the avatar must have an animation when picking up a snowball and another one when it throws it out.
This is done by using triggerSceneEmote() with an animation loaded to the scene.

Also, clicking on the white boxes does not cause the avatar to perform any emote actions.

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/b07e9430-857f-46a4-889d-4314b9dd7dd4

https://github.com/decentraland/unity-explorer/assets/146741383/ce548d69-aabb-4efd-9ffb-64457d3f8f8e

#### ** 🖥️  Platforms:**

- Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
- Macbook M1 Pro Sonoma 14.5

**Comment by nearnshaw** [comment]
Looks like animations are now fixed on the latest commit from today :D

but one thing is different

If I pick up a snowball and throw it, I see the snowball travel from the origin point in the scene to the elf. In the web explorer it travels from my avatar's position instead

Maybe that's worth treating as a separate issue tho
