### ISSUE TITLE
Emotes Technical Debt 

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#1124]
1. `IEmoteCache` is not thread-safe.

We call into its methods from both the main thread from ECS and from `LoadOwnedEmotesSystem`. The latter contains a work-around currently to switch to the main thread to prevent issues. However it's not current and leads to executing parsing logic on the main thread.

2. `CreateWearableThumbnailPromise`

Right the same issue

3. `LoadEmotesByPointersSystem` is not unified with Wearables Resolution.

The logic is the same for about ~60% and should be unified. 
Moreover, cancellation is not properly handled there and will prevent emotes from recovery if they are cancelled at least once. This problem is already resolved in `ResolveWearableByPointerSystem` and, thus, the logic should be properly generalized.
`LoadEmotesByPointersSystem` can be distributed between different systems as required.

**Comment by NickKhalow** [comment]
1. I think `lock {}` would be enough for thread-safety in this case
2. Do you mean method `CreateWearableThumbnailABPromiseAsync`? I tried to search for a class/struct `CreateWearableThumbnailPromise` but I didn't find it
