### ISSUE TITLE
Goerli: Energy cube that disappears from the scene

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1135]
### **Issue Description:**
Upon picking up the Power Cube located in the southwest corner of a scene, the cube disappears from the user's view. In the production environment, when the cube is picked up, it remains attached to the user and does not disappear.

### **Steps to reproduce:**

1. `/goto goerli`
2. Walk or teleport to location 72,-10
3. Pick up the Power Cube

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/d5f360f3-f6d8-4f2d-a920-e7529fd172e0

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/aba9a2b6-90f5-4299-9716-7c5574a308ea

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by nearnshaw** [comment]
When you pick up the cube, you should be carrying it. The cube appears attached to the avatar's position, a meter in front.  You can then put it down by pressing E again.

You can observe this working well in the old web explorer at
https://decentraland.org/play/?realm=sdk-team-cdn.decentraland.org%2Fipfs%2Fgoerli-plaza-main-latest&position=72%2C-10
