### ISSUE TITLE
[QA] Scene freezes after certain interactions with NPCs

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1141]
### **Explorer Alpha build version:**
**Currently on main**

### **Issue Description:**

When entering the client **for the first time**, going to the cafe and speak with the NFT lady (the one at the bar), there is no dialogue on her box and the scene freezes without the canche to interact with anything else or go outside to the Plaza.

### **Steps to reproduce:** (these are tentative steps)

  1. Enter the client after clearing cache, it must be at first loggin
  2. Go to the cafe under the clouds and first click on the lady at the bar
  3. Press E

### **Expected behaviour:**
The dialogue with the NPC continues without issues and the scene behaves as expected with all the responsive items/NPCs

### **Current behaviour:**
The dialogue with the NPC doesn't proceed, it gets stuck in ... and after that, the whole scene can't be interacted with.
To fix it, we need to teleport via `/goto` or the map.

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/b236ede9-912d-46c3-92bb-5327428785fe

https://github.com/decentraland/unity-explorer/assets/139157886/b6a792cf-3692-439a-a7e2-ebadb092417e

**Comment by m3taphysics** [comment]
@anicalbano can we verify this is still an issue?

**Comment by anicalbano** [comment]
@m3taphysics after a fix that Juani implemented, the scene is not freezing anymore. I'll close this one!
