### ISSUE TITLE
[QA] Metadynelabs: Softlock at Level 02 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1145]
### **Explorer Alpha build version:**
0.3.402-g7a23dc7e

### **Issue Description:**
Upon reaching level 2 in Metadyne Labs, users encounter a softlock where they become trapped inside a black square with part of the game's UI visible, but further progress is not possible. Exiting and re-entering the world does not resolve the issue.

1️⃣ Preconditions
Use a new account to complete levels 00 and 01 to reach level 02.

### **Steps to reproduce:**

1. Teleport to Metadyne Labs using /goto Metadynelabs.
2. Progress through the game organically to reach level 02.

### **Expected behavior:**
Upon reaching level 2, the user should be able to continue playing the game without encountering any softlock or obstruction, ensuring a smooth and uninterrupted gameplay experience.

### **Current behavior:**
Upon reaching level 2, the user becomes trapped inside a black square with part of the game's UI visible. Further progress is not possible, leading to a softlock situation where the user is unable to continue playing.

### **Platforms / OS:**
- [❌] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
⚠️ LOGS: [Player-prev.zip](https://github.com/decentraland/unity-explorer/files/15336718/Player-prev.zip)

https://github.com/decentraland/unity-explorer/assets/146741383/b715899d-fed8-45b2-a47c-82e2908f0122

#### **Additional Notes:**
indows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by anicalbano** [comment]
🟢 Fixed on latest


https://github.com/decentraland/unity-explorer/assets/139157886/529165f4-7407-41b9-9838-f0744bec324c
