### ISSUE TITLE
[QA] Some base wearables don't appear equipped or get replaced

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1146]
### **Explorer Alpha build version:**
**Current main at 05/16**

### **Issue Description:**

When logging in and have a common wearable equipped, sometimes it happens that the wearable is not visible on the avatar or gets replaced by another one.

### **Steps to reproduce:**

  1. Equip one or more common wearables and save the changes
  2. Go out of the app and back in

### **Expected behaviour:**
The wearables are equipped

### **Current behaviour:**

- Sometimes it happens that the common wearables cannot be seen on the avatar even though they are equipped.
- In other cases, with the shoes for example, they get replaced by the starting orange shoes that came by default with the avatar.

#### **Evidence:**

![image](https://github.com/decentraland/unity-explorer/assets/139157886/b286b769-2644-4839-bab6-d96678aae390)

![image](https://github.com/decentraland/unity-explorer/assets/139157886/6060e077-083a-408c-a648-b63bc4e4f67c)

**Comment by aixaCode** [comment]
@anicalbano Could you re-check the issue?

**Comment by lorux0** [comment]
Most likely the wearables are missing asset bundles. Please provide urns, so i can check

**Comment by anicalbano** [comment]
> Most likely the wearables are missing asset bundles. @anicalbano please provide urns, so i can check. Very similar to this one: #1560

This issue is not happening anymore. I'll close it
