### ISSUE TITLE
[QA] Metadynelabs:  Incorrect Highlighting on Escape Button in Level 1

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1148]
### **Explorer Alpha build version:**

- **0.3.402-g7a23dc7e**
- **v0.11.0**

### **Issue Description:**
Upon almost completing level 1 in Metadyne Labs, when hovering over the button to activate the final escape door, a green rectangle is displayed, which is unintended and mismatch prod behavior. 

### **Steps to reproduce:**

1. Teleport to Metadyne Labs using /goto Metadynelabs.
2. Progress through the game to reach level 01.
3. Progress through level 1 until reaching the final button that opens the door.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/c3ef7f10-f456-44f4-954d-052bc76e0e07

### **Current behavior:**
![image](https://github.com/decentraland/unity-explorer/assets/146741383/31b7c708-cd66-4b16-bef2-74ed776fdced)

### **Platforms / OS:**
- [❌] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by m3taphysics** [comment]
Is this animation related? @lorux0

**Comment by anicalbano** [comment]
As mentioned by @olavra this is expected and not an issue

**Comment by m3taphysics** [comment]
https://github.com/decentraland/sdk/issues/1139
