### ISSUE TITLE
[QA] Loading Animation Not Displayed Properly

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1150]
### **Explorer Alpha build version:**
0.3.402-g7a23dc7e

### **Issue Description:**
The loading bar on the Metadynelabs minigame screen does not animate as expected. Initially, it appears with some green loading progress, then the progress disappears, leaving the bar empty until the game starts.

### **Steps to reproduce:**

1. /goto Metadynelabs.
2. Observe the loading animation on the Metadyne loading screen.

### **Expected behaviour:**
The loading bar on the Metadynelabs minigame screen should display a consistent loading animation, providing visual feedback to the user that the game is loading and indicating progress until the game starts.

https://github.com/decentraland/unity-explorer/assets/146741383/9a2f9bd5-1f42-4549-82a0-195d6e2f9a70

### **Current behaviour:**
The loading bar on the Metadynelabs minigame screen initially shows some green loading progress, but then the progress disappears, leaving the bar empty until the game starts.

https://github.com/decentraland/unity-explorer/assets/146741383/cdaf4c42-cf21-456d-8dce-79f66fa4610e

### **Platforms / OS:**
- [❌] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by m3taphysics** [comment]
This isn't related to the UI, I simulated a working UI and it updates as expected:

![image](https://github.com/decentraland/unity-explorer/assets/296469/787823ac-480e-43c7-82f2-baccebbd8af9)
