### ISSUE TITLE
[QA] Plaza Functionality Disrupted After Returning from Distant Location

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1151]
### **Explorer Alpha build version:**
0.3.402-g7a23dc7e

### **Issue Description:**
Upon returning to Genesis Plaza after jumping to any distant location, several functionalities become disrupted. The carousels (Best Rated, Events, Crowd) appear empty, there is no music playing, and the portal does not emit any sound. However, after visiting the Metadynelabs world and returning, Genesis Plaza starts working again.

### **Steps to reproduce:**

1. Open Genesis Plaza.
2. Jump to any other location far away.
3. Ensure no disruptions occur.
4. Return to Genesis Plaza.
5. Jump to Metadynelabs.
6. Return to Genesis Plaza.
7. Verify that functionalities are restored.

### **Expected behavior:**
Upon returning to Genesis Plaza from a distant location, all functionalities such as carousel content, music playback, and portal sound should resume as expected.

### **Current behavior:**
After returning to Genesis Plaza from a distant location, the carousels are empty, there is no music playing, and the portal does not emit any sound.

https://github.com/decentraland/unity-explorer/assets/146741383/af80a807-9fc7-4c6f-a662-844be6692574

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by m3taphysics** [comment]
@Ludmilafantaniella can you validate this again? I am sure this is fixed.
