### ISSUE TITLE
[QA] Login in with a different session do not reset name or avatar equipment

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#1163]
### **Explorer Alpha build version:**
When login with a different account during the same session, my character kept the previous player nametag and hair color...

![image](https://github.com/decentraland/unity-explorer/assets/41490935/16cd6607-ce8c-498a-a1d7-85b6cbe65319)

But its working as usual in the backpack

![image](https://github.com/decentraland/unity-explorer/assets/41490935/10b23054-d9f2-4d93-8eb2-5daa28acb710)

I even have some of the previous character wearables equipped
![image](https://github.com/decentraland/unity-explorer/assets/41490935/5eca9dcb-d8f1-4675-847d-47832a9a0f88)

### **Steps to reproduce:**

  1. Login with one account
  2. Logout without closing the application
  3. Login with a different account
  4. Go to backpack, equip any emote
  5. Check hair color and name, and other wearables that may have been empty on the current avatar

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
🟢 Could not reproduce on current versions
