### ISSUE TITLE
[QA] Clicking on Equip a emote, does not play it

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#1164]
### **Explorer Alpha build version:**
When mousing over a emote, an clicking on equip, it does equip it in the slot, but it does not reproduce it. Its maybe the intentional behaviour, but it looks wrong as maybe expected when equipped to reproduce it.

Play emote on equip

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
https://github.com/decentraland/unity-explorer/assets/139157886/6a722f80-6887-483a-a055-6e029332f4e5
