### ISSUE TITLE
[QA] Assets are mixing between Art Week and Music Festival scenes

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1191]
### **Explorer Alpha build version:**
**0.3.463-gf5b67b0c-main**

### **Issue Description:**

When going to the Art Week section streets, waiting for it to finish loading and then teleporting to the Music Festival zone, some assets from the former can be seen on the later, just like:
- Floors
- Billboards
- Maps on the streets
- Some scenarios that appear and disappear

### **Steps to reproduce:**

  1. `/goto 61,61`
  2. Wait for the scenes to load
  3. `/goto -61,61`
  4. Observe the scenes
  
#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/6e91abb9-c3d0-4882-9e90-607462747909

**Comment by m3taphysics** [comment]
@anicalbano can you verify this again as we fixed an issue with pooling? Otherwise its a high priority.

**Comment by anicalbano** [comment]
@m3taphysics will do!

**Comment by mikhail-dcl** [comment]
It's been fixed by @dalkia
