### ISSUE TITLE
[QA] Forest Plaza is not loading

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1192]
### **Explorer Alpha build version:**
**0.3.463-gf5b67b0c-main**

### **Issue Description:**

When going to Forest Plaza (North from Genesis Plaza), via walking, map or /goto, the scene is not loading

### **Steps to reproduce:**

  1. `/goto 1,75` or go via map (walking also works) 
  2. Check that the scene is not loading

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/4f751213-8014-4424-93a7-ad1f8295860b)

**Comment by sandrade-dcl** [comment]
Testing the same scene in the old renderer, it's not loading anything there:

![Image](https://github.com/decentraland/unity-explorer/assets/64659061/e4a9658b-d06c-4a9f-8022-ecc5067def9d)

**Comment by anicalbano** [comment]
Not a bug
