### ISSUE TITLE
[QA] Minimap fails to load on start of application

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-explorer#1198]
### **Issue Description:**
Issue from summit playtest.
Places API fails with error too many requests making the intialization flow break, which leads to minimap not being setup and displaying white image.
This later causes the whole UI to not be intractable.
The only workaround is to restart the application.

**Comment by sandrade-dcl** [comment]
Could be this issue the same as this one? https://github.com/decentraland/unity-explorer/issues/1036

**Comment by davidejensen** [comment]
@sandrade-dcl nope, it's a different issue, the problem with the minimap is related to the initialization phase, I'm fixing it now in a PR :)
