### ISSUE TITLE
[QA] BagWorlds world is not loading

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-explorer#1199]
### **Issue Description:**
Issue from summit playtest.
When loading `BagWorlds` world the loading fails with this error:
```
[JAVASCRIPT]: SceneError: TypeError: (intermediate value).json is not a function stackTrace:     at HostDelegate.<anonymous> (<anonymous>)
    at Object.error (Script [21]:43:45)
    at ri.getUserData (Script [19]:13:516)
    at async iw (Script [19]:16:37187)
    at async gi (Script [19]:16:37040)
 #0 GetStacktrace(int)
 #1 DebugStringToFile(DebugStringToFileData const&)
 #2 DebugLogHandler_CUSTOM_Internal_Log(LogType, LogOption, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
 #3  (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
```

**Comment by sandrade-dcl** [comment]
@aixaCode do you know if we have access to the code of the **BagWorlds** scene to see part of its logic?

**Comment by davidejensen** [comment]
I don't think so, it's a scene developed by decentral games, so maybe we can ask in the slack channel with them

**Comment by sandrade-dcl** [comment]
### Status update
After [fixing](https://github.com/decentraland/unity-explorer/pull/1212) the POST requests in our project (that was one of the causes why this issue happened), now the request is performed correctly BUT it always returns:
```
{"message":"Error fetching user data","details":{"body":{"message":"Invalid signature"}}}
```

Comparing the execution of this scene between the old renderer and E@, the problem should be in how are we dealing with the cases when a scene ask us about to sign with our wallet. In the old renderer, once the request is sent, the browser asks us, through Metamask, about to sign (see the attached screenshot) however in E@ we don't have this behavior implemented and this is why we are always receiving an `Invalid signature` error.

![Image](https://github.com/decentraland/unity-explorer/assets/64659061/d0222afe-37df-4cf5-b732-388e4fc4fe2d)

We'd need to implement that whole flow in E@.
