### ISSUE TITLE
Handle invisible components out-of-scene-bounds behaviour

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-explorer#1201]
Currently the scene shader discards rendering of meshes beyond their containing scene bounds.

The problem is that there are other (non-rendered/invisible) components that can't be handled that way, those being:
- Audio components
- Mesh Colliders

Some scenes may completely ruin experiences outside their own bounds if those cases are not handled (it happened many times in the past...).

We'll need some logic similar to the one used for sdk7 in the unity-renderer to handle those cases, a lot more info on what is implemented at https://adr.decentraland.org/adr/ADR-192.

**Comment by popuz** [comment]
keep in mind that for colliders there is a `CheckColliderBoundsSystem `and respective test: `ColliderBoundsCheckerShould`

**Comment by mikhail-dcl** [comment]
I believe Mesh Colliders are functional, or @pravusjif you have something else in mind?

**Comment by pravusjif** [comment]
Cool, I haven't tested it but if colliders are already handled with what Vitaly mentions (even GLTF colliders?) then we just need to implement something for Audio components (AudioSource and AudioStream).

**Comment by pravusjif** [comment]
Maybe for a first "quick" implementation we can avoid all the "scene bounds checking stuff" and just have a system muting/stopping all audio that is playing from a scene that is not the current one...
