### ISSUE TITLE
Add max height to scene shader outside-scene-bounds discarding logic

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-explorer#1202]
The maximum height a scene can use depending on its amount of parcels is not being taken into account by the scene shader that takes care of discarding the out-of-scene-bounds rendering.

Here are the current scene limitation values: https://docs.decentraland.org/creator/development-guide/sdk7/scene-limitations/

**Comment by m3taphysics** [comment]
We need the C# side integrating for the scene heights.
