### ISSUE TITLE
[QA] Soul Magic only has the UI visible

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1235]
### **Explorer Alpha build version:**
**0.3.477-g5ad20358-main**

### **Issue Description:**

Soul Magic Space is currently empty, but the UI of the scene and the games is appearing on screen just as showed in the screen attached.

### **Steps to reproduce:**

  1. `/goto 99,-112`
  2. Observe the UI when spawning at the scene

#### **Evidence:**

![image](https://github.com/decentraland/unity-explorer/assets/139157886/0abe340a-d6dc-4d93-aa9c-443f9a0cad1e)

**Comment by mikhail-dcl** [comment]
The scene gets stuck in our of async function of JS code...

This is the series of requests made from the old client:

![image](https://github.com/decentraland/unity-explorer/assets/118179774/4c44b0d5-3345-4f25-9e01-24f588d53668)


In the new one it does not proceed to `load_space`, `get_furtiniture`, etc.
This is likely the case why loading of GLTFs is not issued.

```
initObjs() {
            f6(e => {
                if (!e) {
                    this.role = "guest", this.room_owner = "";
                    return
                }
                this.role = e.role, this.room_owner = e.room_owner, this.rebuildSpace(e.space_datas)
            }), yp(e => {}), a.soulPlayer.sync_show_crafting(e => {
                e && (this.craftingDatas = e, this.refreshObjs())
            })
        }
```
