### ISSUE TITLE
[QA] The game in 100 Avatars Garden is not responding

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1238]
### **Explorer Alpha build version:**
**0.3.477-g5ad20358-main**

### **Issue Description:**

When going to 100 avatars garden, it is possible to play the current game (flip the cards), but even though we are able to play, the counter of points and the timer are not working.
Same happens with the rest of the games as the wack-a-mole and select the correct sticker.

### **Steps to reproduce:**

  1. `/goto -55,-121`
  2. Start playing the game

### **Expected behaviour:**
Progress of the game is being tracked and the timer works as expected

### **Current behaviour:**
The progress and time are not responsive

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/16b781b7-7912-432b-870c-53eac8cb2d49)

**Comment by anicalbano** [comment]
@sandrade-dcl still not working on the latest build (not current main, last week's version **0.3.477-g5ad20358-main**), at least the flipping card game.

Are you checking it in local?

![image](https://github.com/decentraland/unity-explorer/assets/139157886/62a4306a-7a50-4b18-9248-6bb0fb61fb02)

**Comment by sandrade-dcl** [comment]
Yep @anicalbano, I tested in local. So it seems it's something that is happening only in build :'(
Thanks Ani.
