### ISSUE TITLE
[QA] Some dialogues have YES NO all capitalized in buttons and some others have all lower case yes no 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1241]
### **Explorer Alpha build version:**

[0.3.477-g5ad20358-main]

### **Issue Description:**

Some dialogues have YES NO all capitalized in buttons and some others have all lower case yes no 

Notice this dialogue:
![image](https://github.com/decentraland/unity-explorer/assets/146749313/9b414c20-138a-43e6-9473-e742d170b3af)

And this other one: 
![image](https://github.com/decentraland/unity-explorer/assets/146749313/bad1787e-b0b6-4765-ac09-96936b2a182d)

### **Steps to reproduce:**

  1. Go to the bar
  2. Talk to octopus. Notice YES and NO will be all capitalized
  3. Talk to people on the sofa. yes and no will be in lower case

### **Current behaviour:**

Some dialogues have YES NO all capitalized in buttons and some others have all lower case yes no 

### **Expected behaviour:**

There should be consistency

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ x]  100%

### **Severity:**

- [ ] Cosmetic
- [x ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
Lets go with UPPER CASE

**Comment by anicalbano** [comment]
Working on current build v0.32

![image](https://github.com/user-attachments/assets/0b05064a-fd9b-41b9-b1d7-937f81dd8466)
![image](https://github.com/user-attachments/assets/9f8d14e1-6b12-4a40-a54f-b99f384b9a33)
