### ISSUE TITLE
[QA] When the user gets to the UI after logging in and appears on the sky platform, a strange sound is quickly triggered for a second

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1244]
### **Explorer Alpha build version:**

[0.3.477-g5ad20358-main]

### **Issue Description:**

When the user gets to the UI after logging in and appears on the sky platform, a strange sound is quickly triggered for a second

### **Steps to reproduce:**

  1. Log in with your wallet
  2. Wait until 100% is reached
  3. Pay attention when getting to the UI

### **Expected behaviour:**
No stranges sounds should be heard when getting to the UI

### **Current behaviour:**
A strange sound is heard when getting to the UI 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [x ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [x ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [x ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by LucasLioyQA** [comment]
@m3taphysics I could never reproduce it in unity-renderer, just in Alpha. Yesterday I could repro this many times, but I havent found it possible to repro this so far. I will be attaching a video after reproducing it, I will keep trying. It's a short sound effect which shouldn't be triggered which lasts a second once you get to the UI.

**Comment by anicalbano** [comment]
Not a bug, unable to repro
