### ISSUE TITLE
[QA] Sometimes green highlighting in borders isn't shown when hovering over some objects

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1248]
### **Explorer Alpha build version:**

[0.3.477-g5ad20358-main]

### **Issue Description:**

Sometimes green highlighting in borders isn't shown when hovering over some objects, like the ball in the basketball game: 

![image](https://github.com/decentraland/unity-explorer/assets/146749313/bdb69042-9141-4439-ae8a-ee9fe72e9d31)

### **Steps to reproduce:**

  1. Go to the basketball game
  2. Hover over the ball
  

### **Expected behaviour:**
It should have borders highlighted in green

### **Current behaviour:**
Sometimes the borders aren't highlighted in green

### **Severity:**

- [ ] Cosmetic
- [ X] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Unable to repro on latest versions (current v0.10.0)
