### ISSUE TITLE
[QA] Goerli - Leader Board (80,9):  clicking on dog and accumulating points on board do not work in both Alpha and old explorer 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1271]
### **Explorer Alpha build version:**

0.3.477-g5ad20358
v0.10.0

### **Issue Description:**

 Clicking on dog and accumulating points on board do not work in both Alpha and old explorer .

Check old explorer:
![dog old explorer](https://github.com/decentraland/unity-explorer/assets/146749313/fd8572ed-60cc-48a5-82ae-6d7595dfc1d9)

Check alpha:
![dog alpha doesnt work](https://github.com/decentraland/unity-explorer/assets/146749313/23a95ee7-9e43-4cb0-ba0d-6bc4e990e495)

### **Steps to reproduce:**

  1. Go to 80,9 in goerli in alpha or old explorer 
  2. Click on dog many times for 10 seconds
  

### **Expected behaviour:**
Score should be shown in board

### **Current behaviour:**
Score isn't shown 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Fixed on version v0.11.11 
![image](https://github.com/decentraland/unity-explorer/assets/139157886/ce707d81-9ac3-413b-a301-02dc77f7e605)
