### ISSUE TITLE
[QA] Goerli | Portal-Puzzle | Crosshair not following mouse

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1272]
### **Explorer Alpha build version:**
0.3.477-g5ad20358-main

### **Issue Description:**
The gun crosshair in prod, follows the movement of the gun, but in EA I have to keep the gun clicked to move it and there is no sight so it is not accurate shooting, I don't know where I am shooting the portal.

### **Steps to reproduce:**

1. / goto goerli  -->  escene (79,-4)
3. Pick up the gun
4. Observe the crosshair

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/8b628281-7275-4b42-b4f8-ee8c2306c983

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/2079ae2e-cd0f-4536-b84a-5815e11c8fcd

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz.
nvidia geforce RTX

**Comment by m3taphysics** [comment]
As discussed with @olavra and @nearnshaw this isn't currently a bug but its not desired behavior. When the scene creator chooses to enter first person, it should be locked to that mode and not allow the different free cursor features.
