### ISSUE TITLE
[QA] Goerli - Validate Player Authenticity (80, -8): wrong validations are taking place when interacting on scene and getting messages in both Alpha and old explorer

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1276]
### **Explorer Alpha build version:**

0.3.477-g5ad20358

### **Issue Description:**

Validate Player Authenticity (80, -8): no proper validations are taking place when interacting on scene and getting messages  in both Alpha and old explorer

Always the negative message is displayed, even when this message shouldn't be triggered. Proper validations aren't taking place. 

Notice this in Alpha:
![negative message alpha](https://github.com/decentraland/unity-explorer/assets/146749313/92e9e1d8-4dc3-42a7-9d67-0eaa63f72033)

Notice this also in old explorer:

![negative message old explorer](https://github.com/decentraland/unity-explorer/assets/146749313/82d41900-3e98-43ee-abac-bd6ca846dfb8)

### **Steps to reproduce:**

  1. Go to 80, -8 in goerli
  2. Click to interact on scene
  

### **Expected behaviour:**
Proper messages should be triggered when interacting on scene

### **Current behaviour:**
Always negative message is triggered, even when it is not supposed to 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
@nearnshaw says we should ignore this scene for now.
