### ISSUE TITLE
[QA][Art Week] Cubes Disappear and Rendering Issues at (52,52)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1285]
### **Explorer Alpha build version:**
v0.4.0

### **Issue Description:**
In the Decentraland Art Week scene at coordinates (52, 52), cubes disappear as the avatar approaches them. Sometimes, the entire render disappears, while other times, only the base remains visible. Additionally, when standing on the base, the countdown starts, but the interior of the cube does not render.

### **Steps to reproduce:**

1. Teleport to the Decentraland Art Week scene at coordinates (52, 52).
2. Approach the cubes in the scene.
3. Stand on the base of a cube

### **Expected behavior:**

- Cubes should remain fully visible as the avatar approaches them.
- The entire scene should render consistently without disappearing.
- When standing on the base the interior of the cube should render correctly.

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/7b31a302-d4b4-4f9d-9421-32991cd826f4

https://github.com/decentraland/unity-explorer/assets/146741383/0a82b7da-4d79-4ded-ad42-8474745837ad

### **Platforms / OS:**
- [❌] Windows 11
- [ ] Windows 10
- [❌] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by mikhail-dcl** [comment]
So after @dalkia 's fixes it works as expected. Though it might be confusing but there is a big difference in LODs and the real scene:

![image](https://github.com/user-attachments/assets/2be13573-a048-48c1-90c5-8aacd84f9021)


Apart from that technically it works

**Comment by dalkia** [comment]
@Ludmilafantaniella 
1) The 'flickering' is expected. Is not actual flickering, but rather the scenes loading
2) There was a problem with the ABs of the surroundings. Give it a go again, they should appear now. 

If everything is okay, go ahead and close it
