### ISSUE TITLE
[QA] [WonderZone Arena] Scene Not Loading Properly on Mac

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1287]
### **Explorer Alpha build version:**
V0.4.0

### **Issue Description:**
In the WonderZone Arena scene at coordinates (-33,54) on Mac, only the screen and elevators load, while the rest of the scene is missing.

### **Steps to reproduce:**

1. Launch the explorer on a Mac device.
2. Teleport to coordinates (-33,54) (WonderZone Arena).

### **Expected behavior:**
![image (1)](https://github.com/decentraland/unity-explorer/assets/146741383/e4a5d61a-4cbc-4f34-8d38-3445a70dc849)

### **Current behavior:**
<img width="1714" alt="Screenshot 2024-06-20 at 9 13 43 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/56f39363-6d71-4891-b73b-17c50e5e5165">

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5

**Comment by davidejensen** [comment]
It is now visible as before after the latest changes in AB server infra
