### ISSUE TITLE
[QA][WonderZone Town Square] Scene Missing on Mac

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1288]
### **Explorer Alpha build version:**
v0.4.0

### **Issue Description:**
In the WonderZone Town Square scene at coordinates (-34,57) on Mac, the entire scene is missing.

### **Steps to reproduce:**

1. Launch the explorer on a Mac.
2. Teleport to coordinates (-34,57) (WonderZone Town Square).

### **Expected behavior:**
![image (1)](https://github.com/decentraland/unity-explorer/assets/146741383/8d43a8a2-a0bf-4fb9-9a7e-dfc392b42aca)

### **Current behavior:**
<img width="1716" alt="Screenshot 2024-06-20 at 9 21 38 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/6201c143-3b47-445b-b1e3-293785905f15">

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [❌] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5

**Comment by davidejensen** [comment]
Fixed
