### ISSUE TITLE
[QA]Win & Mac[Muscle Doge Arena] Scene Missing

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1289]
### **Explorer Alpha build version:**
v0.4.0

### **Issue Description:**
In the Muscle Doge Arena scene located at coordinates (146,59), the entire scene is missing.

### **Steps to reproduce:**

1. Launch the explorer.
2. Teleport to coordinates (146,59) (Muscle Doge Arena).

### **Expected behavior:**

<img width="1721" alt="Screenshot 2024-06-20 at 10 09 46 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/e856bacb-c5e5-471b-a44b-33687d2c7a22">

### **Current behavior:**

<img width="1681" alt="Screenshot 2024-06-20 at 10 07 27 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/de17c491-32bf-47f8-9440-cc8f97c2fc3d">

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ❌] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by mikhail-dcl** [comment]
I believe it's from the same producer as https://github.com/orgs/decentraland/projects/59/views/1?sliceBy%5Bvalue%5D=mikhail-dcl&pane=issue&itemId=67201558
as it uses the same `soulmagic` server
