### ISSUE TITLE
[QA] Win & Mac | AnyMagik: Scene Missing

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1291]
### **Explorer Alpha build version:**
v0.4.0
v0.10.0

### **Issue Description:**
At coordinates (-62,1), the AnyMagik scene is completely missing.

### **Steps to reproduce:**

1. Launch the explorer.
2. Teleport to coordinates (-62,1) (AnyMagik scene).

### **Expected behavior:**

<img width="1711" alt="Screenshot 2024-06-20 at 10 25 55 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/832d441f-0698-4a57-bae3-e5989e942cae">

### **Current behavior:**

<img width="1691" alt="Screenshot 2024-06-20 at 10 22 51 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/92da9f5e-0c5d-4525-80b6-5a52c80ed4a2">

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [❌ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by mikhail-dcl** [comment]
The scene code itself is functional but Asset Bundles were not created

**Comment by mikhail-dcl** [comment]
Manifest is empty

```
{"version":"v18","files":[],"exitCode":9,"contentServerUrl":"https://peer.decentraland.org/content","date":"2024-05-20T17:44:28.886Z"}
```

**Comment by anicalbano** [comment]
Scene renders on current main, some assets are not working but will open new tickets for it. Closing this one.
