### ISSUE TITLE
[QA] Goerli | Simple-NPC: Dog Slides Instead of Walking in Scene

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1297]
### **Explorer Alpha build version:**
v0.4.0

### **Issue Description:**
In the Goerli scene Simple-NPC (80,-3), the avatar does not perform a walking animation but slides across the space instead.

### **Steps to reproduce:**

1. /goto goerli
2. Navigate to the Simple-NPC scene (80,-3)
3. Observe the giant Dog.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/b5c31684-c50f-4037-81be-47f2b4846cf8

### **Current behaviour:**

https://github.com/decentraland/unity-explorer/assets/146741383/fdff37e2-c110-479e-bf88-7aa56d631d36

#### ** 🖥️  Platforms**

- Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
- Macbook M1 Pro Sonoma 14.5

**Comment by anicalbano** [comment]
The dog is now walking as expected:

https://github.com/decentraland/unity-explorer/assets/139157886/3e9e30ea-2704-4bd3-b17e-28a05fbf1f41
