### ISSUE TITLE
[QA] dclonboarding.dcl.eth Scene Loads but Assets Lack Colliders, Causing User to Fall Through

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1324]
### **Explorer Alpha build version:**

- **v0.7.0**
- **v0.10.0**
- **v0.11.0**
- **v0.12.0**

### **Issue Description:**
It seems that the scene loads correctly, but the assets lack colliders, causing the user to fall through and see the scene from below. Please review the collider settings on the assets to ensure proper interaction with the environment.

### **Steps to reproduce:**

1. Launch the explorer.
2. /goto dclonboarding.dcl.eth 

### **Expected behavior:**
The scene should load correctly with all assets present and functioning as intended.

### **Current behavior:**
The scene loads, but it is empty with all assets missing.

https://github.com/decentraland/unity-explorer/assets/146741383/93548eb6-6c7e-4ec3-8823-6c3e48aee019

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
We wont be making this scene work but we are keeping it until we remove the SDK6 bridge.
