### ISSUE TITLE
[QA] Avatar does not execute the automatic dance in Dollhouse 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1328]
### **Explorer Alpha build version:**
v0.7.0

### **Issue Description:**
Avatar does not automatically execute the dance animation upon entering the Dollhouse scene at coordinates (-102, -97).

### **Steps to reproduce:**

1. Launch the explorer.
2. /goto -102, -97

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/131051c3-9761-4f55-b982-d0a076f4efaf

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/11dba4d1-e790-43c3-b8fd-e7ba1a9f3950

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [❌] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
@Ludmilafantaniella I cannot reproduce this, my avatar dances immedilatey now can you recheck? v0.11.0
