### ISSUE TITLE
[QA] Assets Missing in Teleperformance Scene (-93,109)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1330]
### **Explorer Alpha build version:**
v.0.7.0

### **Issue Description:**
In the Teleperformance scene located at (-93,109), many assets are missing. Only minimal assets are visible, rendering the scene incomplete.

### **Steps to reproduce:**

1. Launch the explorer
2. Navigate to Teleperformance scene using /goto -93,109

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/b348c9f4-86f0-4680-b9aa-7cda5c10242b

### **Current behavior:**
![capture_240628_115917](https://github.com/decentraland/unity-explorer/assets/146741383/8acc899d-7c5b-4af5-8d0a-d3e283047221)

### **Platforms / OS:**
- [❌] Windows 11
- [ ] Windows 10
- [❌] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
This scene now loads (albeit it has some issues) @Ludmilafantaniella can you verify **v0.11.0**
