### ISSUE TITLE
[QA] Goerli | Block-Fountain: Cubes Move Without Button Press and Board Button Inaction

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1335]
### **Explorer Alpha build version:**
v0.8.0

### **Issue Description:**
Cubes in the Goerli Block-Fountain scene move without requiring any button press. Additionally, pressing the board button does not trigger any action.

### **Steps to reproduce:**

1. /goto goerli
2. Navigate to (79,4) Block-Fountain scene
3. Observe cubes moving without prior interaction with the board.
4. Attempt to interact with the board buttons.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/9190562c-e90c-401d-976b-7e6923272617

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/58906edc-a522-43f8-986b-41a4afc518d4

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by nearnshaw** [comment]
With a build from today, I'm not seeing this issue anymore :)
