### ISSUE TITLE
[QA] dclonboarding.dcl.eth isn't rendering

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1341]
### **Explorer Alpha build version:**
v0.11.0

### **Issue Description:**
Teleportation to the DCL Onboarding world (dclonboarding.dcl.eth) is successful, but no assets load upon arrival. However, the world's music can still be heard.

### **Steps to reproduce:**

1. Launch the explorer.
2. Use command `/world dclonboarding.dcl.eth`
3. Observe that no assets load after teleportation, but the music from the world can be heard.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/57cc7011-dcce-4124-af24-00541ed864b8

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/e94f46fd-a176-44b4-8073-5d5a9c11dee0

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
I am assuming its the same as https://github.com/decentraland/unity-explorer/issues/1324
