### ISSUE TITLE
[QA] Claw Machine Assets Missing and Claw Operates in Continuous Loop

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1347]
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**
The assets of the claw machine from the Game Expo event are missing, and the claw continuously opens and closes in a loop.

### **Steps to reproduce:**

1. Navigate to the Game Expo (0,82)
2. Locate the claw machine.
3. Observe that the assets of the claw machine are missing.
4. Observe that the claw opens and closes in a continuous loop.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/a9f447b7-13ae-46c8-8ec0-060c7a36db33

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/10550f4a-17fb-4350-9a5d-7cb0d5307a83

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by lorux0** [comment]
Working with latest animation changes

https://github.com/user-attachments/assets/7c4198eb-8182-41c9-98ec-2e2c20480183
