### ISSUE TITLE
[QA] Goerli: Bullet-Hole Sprites Issues in Shooting Range

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1360]
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**
In Goerli Plaza at coordinates (84,-1) in the Shooting-Range-Advanced area, there are multiple issues with the bullet-hole sprites. When clicking on the ground, the bullet-hole sprite appears oversized. When shooting at the rotating targets, the bullet-hole sprite floats in the air instead of staying on the target as it rotates. Additionally, the bullet-hole sprites do not disappear after a few seconds, unlike in production.

### **Steps to reproduce:**

1. `/goto goerli` Navigate to coordinates (84,-1).
2. Enter the Shooting-Range-Advanced area.
3. Click on the ground and observe the bullet-hole sprite.
4. Shoot at the rotating targets and observe the bullet-hole sprite behavior.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/7ff22c3b-ae46-4a9a-91e0-2d1188f9fb6f

### **Current behavior:**
<img width="661" alt="Screenshot 2024-07-03 at 9 38 24 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/aa6910ea-d674-4594-82f9-b5fff12c57fe">
<img width="1723" alt="Screenshot 2024-07-03 at 9 24 24 AM" src="https://github.com/decentraland/unity-explorer/assets/146741383/ddc5ff52-83bf-4b60-8e16-da81a4103b81">

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by NickKhalow** [comment]
This fix should fix it too
https://github.com/decentraland/unity-explorer/pull/1407
