### ISSUE TITLE
goerli: Captcha in Simple-Giveaway-Scene Lacks Background Contrast and Is Incomplete

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1361]
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**
 In Goerli, within the simple-giveaway-scene (83,-4), the captcha appears without the necessary white background contrast, making it impossible to complete. In production, the captcha appears in a modal with a white background and can be completed, followed by the display of the wearable modal.

### **Steps to reproduce:**

1. `/goto goerli` Navigate to the simple-giveaway-scene (83,-4) 
2. Wait until the counter reaches 0
3. Observe the captcha.

### **Expected behavior:**

- The captcha should appear in a modal with a white background for contrast.
- The captcha should be completable, and the wearable modal should appear afterwards

### **Current behavior:**

- The captcha appears without a white background contrast.
- The captcha cannot be completed.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
Can you provide screenshots?
