### ISSUE TITLE
[QA] Goerli: Gnark Walking Mechanic Not Functioning Correctly 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1362]
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**
In Goerli, within the Gnark scene (74,-9), the Gnark character should stop walking and perform an animation (raising a fist and shouting) when the avatar stands in its path. However, instead of stopping and performing the animation, the Gnark character simply continues walking.

### **Steps to reproduce:**

1. `/goto goerli` Navigate to (74,-9).
2. Observe the Gnark character walking.
3. Position the avatar in the path of the Gnark character.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/1ed13ac9-e279-4060-af30-57958cb7b817

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/ce3d10db-5d96-4c99-be6e-9ed29fc1a795

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by nearnshaw** [comment]
When trying with a commit from today, I can't reproduce this issue. It would seem to be fixed there.

**Comment by m3taphysics** [comment]
@Ludmilafantaniella please re-test this issue.

**Comment by nearnshaw** [comment]
Weird, I was never able to reproduce this issue. Just tried with today's release and it works well for me. The same with older releases


https://github.com/decentraland/unity-explorer/assets/3507907/e7395f3f-cc71-4748-93b4-c72f0e9a2d95
