### ISSUE TITLE
[QA] Videos on Game Expo plaza are not working but have sound

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1365]
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**

By going around the Game Expo plaza (starting at 1,81) and going inside the different booths, we can see that the videos are not working. Instead there are only static images but still the sound can be heard.

### **Steps to reproduce:**

  1. `/goto 1,81`
  2. Walk around the Game Expo plaza an enter the  booths
  3. Check the video and sound of each booth

### **Expected behaviour:**
Videos are working with their propper sound

### **Current behaviour:**
Videos are not playing

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/dc1d7d88-029b-4ffa-b41f-9b724e555e53

**Comment by m3taphysics** [comment]
@anicalbano cannot reproduce this, the videos are working here. Can you recheck?

**Comment by anicalbano** [comment]
🟢 Videos are working as expected
