### ISSUE TITLE
[QA] Goerli | Wearables Scanner: Scanner Effect Missing and Door Not Opening

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1376]
### **Explorer Alpha build version:**

- **v0.11.0**

### **Issue Description:**
In the Wearables Scanner scene (76,-5), the scanner should scan the avatar and open the door if the avatar is wearing the Thug Life glasses. If not, it should display a red light and keep the door closed. In the current environment (EA), the scan effect is not visible, and the door does not open even when the avatar is wearing the Thug Life glasses.

### **Steps to reproduce:**

1. /goto goerli Wearables Scanner scene (76,-5).
2. Approach the scanner.
3. Equip the Thug Life glasses on the avatar.
4. Observe the scanner's behavior and the door.

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/ee695e75-6633-4507-80ae-f6e3560644b4

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/9f5b0e18-2121-4540-9c60-f31541d15c2a

#### **Additional Notes:**

- Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
- Macbook M1 Pro Sonoma 14.

**Comment by sandrade-dcl** [comment]
I'm trying and the door is opening correctly:

https://github.com/decentraland/unity-explorer/assets/64659061/a0cb0ce2-214f-4ac1-b25d-aea2892cde29

**Comment by sandrade-dcl** [comment]
**UPDATE**: It was working well for me because I had an old cache. After cleaning it, I was able to reproduce the issue 👍
