### ISSUE TITLE
goerli: the chest is already open when reaching the top

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1382]
### **Explorer Alpha build version:**
v0.11.0
### **Issue Description:**

On `/goto 80,-4` we must jump to reach the top of a structure that contains a chest. Said chest must be closed and only open when we click on it. 
Currently on alpha, the chest is already open when reaching the top and clicking it generates an open-close-open-close secuence.

#### **Evidence:**
**RENDER**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/b1159456-0bee-4f49-bf16-45d5e04e7a6f)

**ALPHA**

https://github.com/decentraland/unity-explorer/assets/139157886/e3e39b29-46fd-44de-9b49-86fe2a44d457

**Comment by anicalbano** [comment]
The issue re-appeared on v0.15.0

**Comment by lorux0** [comment]
Fixed here: https://github.com/decentraland/unity-explorer/pull/1541
