### ISSUE TITLE
[QA] Goerli | UI-Animations Progress Bar Displays Only One Digit

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1384]
### **Explorer Alpha build version:**

- **v0.11.0**

### **Issue Description:**
In the 'complex example' of the Goerli UI-Animations, the progress bar's number display is incorrect. The number inside the progress bar only shows one digit and resets to 0 every time the count exceeds 9.

### **Steps to reproduce:**

1.  `/goto goerli` at coordinates (72,-1)
2. Click the last box (complex example)

### **Expected behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/6ed895e7-0495-44c5-97ad-306697e5bbdd

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/3ca22087-58e5-4c76-915d-32d7520f9ce9

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
Fixed by #1405
