### ISSUE TITLE
Optimize Avatar Attach Setup / UpdateAvatarAttachTransform

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#1396]
### **Issue Description:**

We had to remove throttling to ensure the transforms are updated at the correct intervals. This means **SetupAvatarAttach** is also not throttled which has some overhead. We can remove this overhead by moving the setup to a different system.

https://github.com/decentraland/unity-explorer/pull/1391

**Comment by anicalbano** [comment]
Fixed in #2234
