### ISSUE TITLE
goerli: incorrect offset number rises avatar over the floor

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1424]
### **Explorer Alpha build version:**
v0.11.0
### **Issue Description:**

The offset number is incorrect on scenes  Avatar-swap `(75,-7)` & Advanced-avatar-swap` (76,-7)` the avatars appear to be floating over the floor.

**Comment by NickKhalow** [comment]
The incorrect offset is in unity-renderer, in current implementation it attaches fine but the model has internal offset due previous render specialities



![Image](https://github.com/user-attachments/assets/6b4ae912-3318-4edb-bfee-9889369fadd9)



![Image](https://github.com/user-attachments/assets/0e879e54-a02b-4b36-874e-b8cd4977d677)



![Image](https://github.com/user-attachments/assets/7b190309-af62-426e-aeb3-2e6ae974447e)



![Image](https://github.com/user-attachments/assets/81c44e24-d9ae-47bd-886b-52ebfb23a7dc)

**Comment by NickKhalow** [comment]
Fixed by this PR https://github.com/decentraland/unity-explorer/pull/1423
