### ISSUE TITLE
goerli: Text in Modal Appears Vertically in Simple Giveaway Scene

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1426]
### **Explorer Alpha build version:**
v0.12.0

### **Issue Description:**
In the Goerli scene "simple-giveaway-scene" (83,-4), the text within the modal appears vertically in a single line, extending through the modal and making it difficult to read.
⚠️ This issue is also happening on Prod.

### **Steps to reproduce:**

1. `/goto goerli` Navigate to simple-giveaway-scene at coordinates (83,-4)
2. Observe the text within the modal.

### **Expected behavior:**
The text within the modal should appear horizontally, wrapping properly within the boundaries of the modal.

### **Current behavior:**
![capture_240712_151530](https://github.com/user-attachments/assets/9cf153c2-7235-42be-83bb-4b41a33a7fbb)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by nearnshaw** [comment]
This is a scene-side problem, caused by the textWrapping change
I'm seeing the same broken text in prod
