### ISSUE TITLE
goerli: Editor-actions | Action Emote isn't working

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1427]
### **Explorer Alpha build version:**
v0.12.0

### **Issue Description:**
In (85,-9) when the avatar stand on the 'Emote' tile, the one that is between 'Puffer' and 'Move Player' tiles, nothing happens.
⚠️ This is also happening on Prod.

### **Steps to reproduce:**

  1. `/goto goerli`
  2. Navigate to Editor-actions (85,-9)
  3. Stand up on the 'Emote' tile that is between 'Puffer' and 'Move Player' tiles. 

### **Current behavior:**

https://github.com/user-attachments/assets/b1ee2abc-7117-437b-8898-c3bedc39ebcc

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by NickKhalow** [comment]
@m3taphysics I think it's a sdk issue, let's redirect it to them

_⚠️ This is also happening on Prod._

**Comment by nearnshaw** [comment]
I just pushed a fix to the Goerli Plaza repo
There was a problem in the scene. The action was not properly assigned to the trigger area. It used to work, must have broken doing some recent polish.
