### ISSUE TITLE
[QA] 100Avatars Garden Scene Assets Missing and Unplayable

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1429]
### **Explorer Alpha build version:**
v0.12.0

### **Issue Description:**
In the Goerli scene "100Avatars Garden" (-55,-121), the majority of the assets are missing, rendering the scene unplayable.

### **Steps to reproduce:**

1. /goto -55,-121
2. Observe the presence of assets and functionality of the scene.

### **Expected behavior:**
The assets in the 100Avatars Garden scene should be present, and the scene should be fully functional and playable.

### **Current behavior:**
![capture_240715_101758](https://github.com/user-attachments/assets/3e83abe7-02f7-4988-91e6-ea88cce35e0c)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
Fixed 🟢 

![Image](https://github.com/user-attachments/assets/7633e773-471d-46af-a57a-2591137a8bcc)
