### ISSUE TITLE
[QA] Platform Spawn Not Functioning in MetagamiMall 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1430]
### **Explorer Alpha build version:**

- **v0.12.0**

### **Issue Description:**
In the Goerli scene "MetagamiMall" (145,60), the platform spawn feature is not functioning as expected.

### **Steps to reproduce:**

1. Launch the explorer.
2. Navigate to the MetagamiMall scene at coordinates (145,60)
3. Attempt to use the platform spawn feature.

### **Expected behavior:**

https://github.com/user-attachments/assets/8a063855-36e0-4c9d-8735-14f23df26ea7

### **Current behavior:**

https://github.com/user-attachments/assets/a4afb3ab-ad4a-4002-9ff6-991e8ee32181

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
Platform spawning is currently working on version 0.13.0
