### ISSUE TITLE
[QA] Map Displayed as Square Instead of Round

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1452]
### **Explorer Alpha build versions:**
v0.12.0

### **Issue Description:**
In the Explorer Alpha (EA), the map, which should be displayed as round, appears as a square.

### **STR:** 

1. Launch the explorer
2. Observe the shape of the map.

### **Expected behavior:**
![capture_240717_181757](https://github.com/user-attachments/assets/ef6762bd-8925-4576-a098-30906a41430f)

### **Current behavior:**
![image](https://github.com/user-attachments/assets/6611c59a-cf96-4103-b67a-4e5ae5f5b3b5)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by sandrade-dcl** [comment]
I have confirmed that this issue was introduced [here](https://github.com/decentraland/unity-explorer/pull/1306). I will investigate what is the reason.
