### ISSUE TITLE
[QA] Client crashes when logging in with a certain addresss

### ISSUE THREAD

**Issue by nicorajcodcl** [decentraland/unity-explorer#1470]
### **Explorer Alpha build versions:**
0.13.0

### **Issue Description:**
After logging in with this address, the client crashes.
Address: 
0x08BF36607ca7912e45625dBe270D3b26604CEA1f
Crash view:
![image](https://github.com/user-attachments/assets/9427d71d-cafd-43ec-874e-eaa23700fc36)

This happened at the community summit (with the same wallet). The hypothesis at the time was that there was a wearable in that wallet that generates the crash. 

### **STR:** 

  1. Open the client
  2. Login with this address 0x08BF36607ca7912e45625dBe270D3b26604CEA1f
  3. Wait for the loading screen to complete and watch how none scenes are rendered

### **Expected behaviour:**
I should be able to log in with this wallet as with any other. 

#### **Additional Notes:**
Tested on Windows on July 19th

**Comment by popuz** [comment]
From Analytics, it didn't went further then step `6 - realm loaded` of initial loading flow

```
{
  "anonymousId": "044fa077-503a-434f-a7ae-4eb085c7aead",
  "context": {
    "dcl_eth_address": "0x08bf36607ca7912e45625dbe270d3b26604cea1f",
    "dcl_renderer_type": "Desktop",
    "ip": "1***.8***.8***.1***",
    "library": {
      "name": "Analytics-CSharp",
      "version": "2.4.2"
    },
    "os": "Microsoft Windows NT 10.0.22631.0",
    "platform": "Unity",
    "position": "(0.0000, 0.0050, 0.0000)",
    "realm": "baldr",
    "renderer_version": "v0.13.0-alpha-main",
    "runtime": "release",
    "session_id": "b***"
  },

  "event": "initial_loading",
  "properties": {
    "state": "6 - realm loaded"
  },
}
```
