### ISSUE TITLE
[QA] Halloween AI Treasure Hunt scene (-38, -134) not rendering

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1490]
### **Explorer Alpha build versions:**

- **v0.13.0**

### **Issue Description:**
In the Halloween AI Treasure Hunt scene at coordinates (-38, -134), the scene fails to render properly. The environment appears empty, though the background music plays, the initial modal is displayed, and fog is present. However, no other elements are visible.

⚠️ In Prod, the scene is rendering correctly.

### **STR:** 

1. Launch the explorer
2. `/goto -38, -134`  Halloween AI Treasure Hunt scene.
3. Observe the rendering of the scene.

### **Expected behavior:**
![Halloween-Prod](https://github.com/user-attachments/assets/94d9b309-9200-482a-b7ff-2fcadc05aa18)

### **Current behavior:**
![Halloween1](https://github.com/user-attachments/assets/74d479e6-bc23-4065-8444-9e566f481942)

####![Halloween](https://github.com/user-attachments/assets/aeb437d4-0d79-421b-a586-d8e7932857cd)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by dalkia** [comment]
Fixed, asset bundles were not built

**Comment by anicalbano** [comment]
Working on current version v0.14.0

![image](https://github.com/user-attachments/assets/1e80ba9c-a191-45f3-ab36-3858c1b2b3e0)
