### ISSUE TITLE
[QA] Butterfly Prawn Farming Game scene missing at (96, -132)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1491]
### **Explorer Alpha build versions:**

- **v0.13.0**

### **Issue Description:**
The Butterfly Prawn Farming Game scene is missing at coordinates (96, -132).

### **STR:** 

1. Launch the explorer
2. `/goto 96,-132`
3. Confirm if the Butterfly Prawn Farming Game scene is present.

### **Expected behavior:**

https://github.com/user-attachments/assets/b20d4fb6-854b-488a-b4d4-4b4b1c29486b

### **Current behavior:**
![Butterfly-Prawn](https://github.com/user-attachments/assets/225b7c0b-86ab-499c-ac2c-29d75b27b022)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by NickKhalow** [comment]
AB issue, should be rechecked
