### ISSUE TITLE
goerli: `86, -8` Incorrect render queue

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#1494]
Floor and door frames are renderer at `Transparent+` queue with ZWrite enabled which leads to cutting out Avatar-related elements such as `Name plate` and Wings.

![image](https://github.com/user-attachments/assets/a3271ac6-13ab-494e-827e-1fe1b7b60f97)

![image](https://github.com/user-attachments/assets/7be2b63f-c8c3-4f66-903f-09b0777233c4)

![image](https://github.com/user-attachments/assets/59a08f9e-8ae5-4931-92e3-150084f8d564)

![image](https://github.com/user-attachments/assets/88b231cc-2919-4cfa-975a-5c60691fcdef)

**Comment by m3taphysics** [comment]
This is an art asset issue
