### ISSUE TITLE
[QA] Color changing lights are not working on Seed scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1497]
### **Explorer Alpha build versions:**

- **v0.13.0**
- **v0.15.0**
- **v0.16.0**

### **Issue Description:**

On Seed scene `/goto -104,-95` the selection of color changing lights is not working. You cannot see the lights as in current Unity Render.

### **STR:** 

  1. Go to the top floor of the scene
  2. Open the button menu
  3. Turn on the Color changing lights option

### **Expected behaviour:**
The lights change color

### **Current behaviour:**
There are no lights on scene

#### **Evidence:**

**ALPHA**
https://github.com/user-attachments/assets/af1faad8-095b-4b67-bdf8-33449e68a007

**RENDER**

https://github.com/user-attachments/assets/84f174f5-b946-42b0-97e7-1137de6b4352

**Comment by sandrade-dcl** [comment]
The lights and stars are working fine in editor but not in the build :S In build they directly don't exist :S

### Unity Editor
https://github.com/user-attachments/assets/e72cab72-cd53-4508-917f-7253a513fc00

### Windows Build
https://github.com/user-attachments/assets/fc1a9e65-e98b-420f-bab7-01cb8882bf4a

**Comment by NickKhalow** [comment]
Fixed in the PR https://github.com/decentraland/unity-explorer/pull/1658
