### ISSUE TITLE
[QA] Strobe lights are not working on Seed scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1498]
### **Explorer Alpha build versions:**

- **v0.13.0**
- **v0.15.0**
- **v0.16.0**

### **Issue Description:**

On Seed scene /goto -104,-95 the selection of strobe lights on the upper floor is not working when activating the button

### **STR:** 

  1. Go to the top floor of the scene
  2. Activate the color changing lights 
  3. Attempt to activate the Strobe Lights

### **Expected behaviour:**
With the flow of the color changing lights, the strobe lights speeds up the changing process

### **Current behaviour:**
Due to issue #1497 the strobe lights are not working

#### **Evidence:**

**ALPHA**

https://github.com/user-attachments/assets/dda50f4c-5839-47ab-9e78-df4f1733d3d1

**RENDER**

https://github.com/user-attachments/assets/512502cf-1780-49c9-a0b7-2a5cbe434541

**Comment by NickKhalow** [comment]
Fixed with the previous PR, but couple of times I got not working UI

**Comment by NickKhalow** [comment]
https://github.com/user-attachments/assets/aec03c87-d268-4a99-9dd0-9a51c77e1784

**Comment by NickKhalow** [comment]
@Ludmilafantaniella Did you check it on windows? I rechecked it with mac and carpet is ok, but strobe lights won't work too. I'm on it

https://github.com/user-attachments/assets/2f4221f4-45a6-42cc-a77c-90aa28281caa

**Comment by m3taphysics** [comment]
This issue is build only, assigning to @GBirch33 as he is investigating simialr problems.

**Comment by NickKhalow** [comment]
The issue was with Addressables, fixed in PR [#1658](https://github.com/decentraland/unity-explorer/pull/1658)
