### ISSUE TITLE
[QA] Stars Moving option on Seed scene is barely noticeable

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1500]
### **Explorer Alpha build versions:**

- **v0.13.0**
- **v0.15.0**
- **v0.16.0**

### **Issue Description:**

Since there are less particles on Seed scene `/goto -104,-95` when activating the Stars Moving option, said movement can only be noticed with a few particles going around.

### **STR:** 

  1. On Seed scene, activate the option Stars Moving
  2. On the top floor, check the floor
  3. On ground floor, check around

### **Expected behaviour:**
Points of light should be moving around the avatar

### **Current behaviour:**
The particles are a lot less on the scene so those can barely be seen

#### **Evidence:**

**ALPHA**

https://github.com/user-attachments/assets/1ab99110-7683-4af9-b46c-4bc808a35b38

**RENDER**

https://github.com/user-attachments/assets/964d0227-189f-44cb-b414-aaac10c385da

**Comment by sandrade-dcl** [comment]
Same comment as [here](https://github.com/decentraland/unity-explorer/issues/1497#issuecomment-2252275841).
