### ISSUE TITLE
[QA] Wilderness P2E scene missing at (-24, 92)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1501]
### **Explorer Alpha build versions:**

- **v0.13.0**

### **Issue Description:**
In the Wilderness P2E scene at coordinates (-24, 92), the scene itself is missing. Only certain UI elements, such as icons for Twitter, Discord, and other in-game interfaces, are visible and interactive. The main scene content does not render.

### **STR:** 

1. Launch the explorer
2. Use `/goto -24,92` command on chat
3. Observe the absence of the main scene content.

### **Expected behavior:**
![Wilderness-P2E-Prod](https://github.com/user-attachments/assets/4bf0fc42-1c95-4537-a537-82544f238fc5)

### **Current behavior:**
![Wilderness-PDE-E@](https://github.com/user-attachments/assets/53f5e17a-2daa-4dfc-99f3-8c7d2b5f5643)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by davidejensen** [comment]
Closing in favor of #1757
