### ISSUE TITLE
[QA] Incomplete Dogebuster scene at (-40, -59)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1502]
### **Explorer Alpha build versions:**

- **v0.13.0**

### **Issue Description:**
In the Dogebuster scene at coordinates (-40, -59), only some assets are visible while the rest of the scene fails to render.

### **STR:** 

1. Launch the explorer
2. Write /goto -40,-59 in the chat
3. Observe the scene for missing elements.

### **Expected behavior:**

https://github.com/user-attachments/assets/d986d0c0-7f84-42a7-b797-b85906935af7

### **Current behavior:**
![DogbusterHQ-W@](https://github.com/user-attachments/assets/2f6c0633-c76f-4a23-9841-0b03176293ce)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
Currently working on v0.16
![image](https://github.com/user-attachments/assets/3606d851-3a3b-487c-95c3-dcd0caccf042)
