### ISSUE TITLE
[QA] Neon colors turn gray upon approach in 'Inner State' scene (58, -68) in DCLWW

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1510]
### **Explorer Alpha build versions:**

- **v0.13.0**

### **Issue Description:**
In the 'Inner State' scene at coordinates (58, -68) within DCLWW, neon colors that initially appear vibrant and bright turn gray when the player approaches. 

### **STR:** 

1. Launch the explorer
2. Navigate to coordinates (58, -68) in the 'Inner State' scene within DCLWW.
3. Observe the neon colors from a distance.
4. Approach the neon colors and observe the change to gray.

### **Expected behavior:**

https://github.com/user-attachments/assets/fcf191f5-a52c-4f3f-bc66-c6c4efb5f9fe

### **Current behavior:**
https://github.com/user-attachments/assets/d864e71a-4ee8-47e1-9b93-a8010da9011e

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by m3taphysics** [comment]
I think this is due to LOD's and it being an SDK6 scene but lets verify.

**Comment by sandrade-dcl** [comment]
After debugging the scene, I can confirm:

1. It's a **SDK7** scene.
2. It's using **LODs** and they are currently switching between them correctly: When we go far away from the scene, its LOD0 version loads (with more simple meshes, without animations, without collider, etc.), and when we go near the scene, it loads the original version (with more complex meshes, animations, colliders, etc.).
3. If we compare the LOD0 version with the oringial one, we see the creator decided to use **different materials**. This is why, for example for the lights that are above the columns, we see them with different bright.

![Image](https://github.com/user-attachments/assets/ec704f21-e83a-42b6-be3c-5c61a8cfcb5a)
![Image](https://github.com/user-attachments/assets/ebec89d3-4c3d-4bb7-8422-4f861ee82e46)
