### ISSUE TITLE
[QA] Waterfall appears black in Genesis Plaza

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1512]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
The waterfall in Genesis Plaza is displaying as black. This issue was introduced following the implementation of ticket fix #1506, which temporarily removed the real-time reflection probe.

### **STR:** 

1. Launch the explorer
2. Observe the waterfall.

### **Current behavior:**
![Cascada](https://github.com/user-attachments/assets/d5ac44eb-f23f-414c-8d4c-d62f6e0699bf)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
🟢 Fixed on latest versions
