### ISSUE TITLE
[QA] NFTs missing in DollHouse scene (-102, -97)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1513]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
In the DollHouse scene at coordinates (-102, -97), NFTs are not appearing on any of the floors.

### **STR:** 

1. Launch the explorer
2. `/goto -102, -97`  DollHouse scene.
3. Check each floor for the presence of NFTs.

### **Expected behavior:**
![NFTs1](https://github.com/user-attachments/assets/54fc5d9a-14b3-41ca-a8df-00d2c0a03ae8)
![NFTs](https://github.com/user-attachments/assets/67f07160-89ea-4717-996c-b4a35dae0ff1)
![NFTs2](https://github.com/user-attachments/assets/73eb9164-2311-4cfb-9469-7371060f2784)

### **Current behavior:**
![DollHouse-EA1](https://github.com/user-attachments/assets/420d6eb4-b974-43e8-b377-02806296ad00)
![DollHouse-EA](https://github.com/user-attachments/assets/45d25afe-10b4-4a2f-aaff-38dff4d625fc)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by popuz** [comment]
on prod `. zone` NFTs are also not loaded. Cors issue 
![image](https://github.com/user-attachments/assets/3b9dad30-854b-4c2a-a459-92014617dd9c)
