### ISSUE TITLE
[QA] Missing music in DollHouse scene (-102, -97)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1514]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
The DollHouse scene at coordinates (-102, -97) is missing background music.

### **STR:** 

1. Launch the explorer
2. `/goto -102, -97` DollHouse scene.
3. Listen for background music.

### **Expected behavior:**
Background music should play consistently in the DollHouse scene.

https://github.com/user-attachments/assets/9c91fe22-a37b-4268-b3de-ee2efaac8347

### **Current behavior:**

https://github.com/user-attachments/assets/cca6f22a-366c-47ca-9c84-76b7bc568abb

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by popuz** [comment]
on prod `.zone` it is also not playing. Cors issue.
