### ISSUE TITLE
[QA] Missing strobe lights, glitters, and disco ball in DollHouse scene (-102, -97)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1515]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
In the DollHouse scene at coordinates (-102, -97), strobe lights, glitters, and the disco ball are missing.

### **STR:** 

1. Launch the explorer
2. `/goto -102, -97` DollHouse scene.
3. Observe the presence of strobe lights, glitters, and the disco ball.

### **Expected behavior:**

https://github.com/user-attachments/assets/6c177470-4d5f-4db6-ad84-f401982adce3

### **Current behavior:**

https://github.com/user-attachments/assets/383895e4-8bb6-46b9-b6a9-975fd000dea0

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by popuz** [comment]
on prod `.zone` it is also missing (also chair and other assets in the room corners). Cors issue.
![image](https://github.com/user-attachments/assets/79feda0e-8117-4a6b-b726-910e86b984d1)
