### ISSUE TITLE
[QA] Missing videos in DollHouse scene (-102, -97)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1517]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
In the DollHouse scene at coordinates (-102, -97), videos are missing.

### **STR:** 

1. Launch the explorer
2. `/goto -102, -97` DollHouse scene.
3. Check for the presence of videos.

### **Expected behavior:**

https://github.com/user-attachments/assets/c3bf740b-6484-49e1-b8c2-d8d1246631b1

### **Current behavior:**

https://github.com/user-attachments/assets/3cd69678-8e22-439b-8d31-a7fe4ee7153d

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by popuz** [comment]
on prod `.zone` it is also not playing. Cors issue.
