### ISSUE TITLE
[QA] Missing bar and 'Bienvenidos' sign in DollHouse scene (-102, -97)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1518]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
In the DollHouse scene at coordinates (-102, -97), the bar and the 'Bienvenidos' sign with two hearts are missing.

### **STR:** 

1. Launch the explorer
2. `/goto -102, -97` DollHouse scene.
3. Look for the bar and the 'Bienvenidos' sign with two hearts.

### **Expected behavior:**
![DollHouse-entrada-Prod](https://github.com/user-attachments/assets/21a5d3e8-600a-4fa7-9c1b-7fcedba68fef)

### **Current behavior:**
![DollHouse-entrada-E@](https://github.com/user-attachments/assets/eb530024-0794-4c1f-89ba-643988bc24de)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by popuz** [comment]
on prod `. zone`  it is also missing. Cors issue
![image](https://github.com/user-attachments/assets/155d377b-9aa2-49b2-92e6-757a07a453fc)
