### ISSUE TITLE
[QA] Incorrect Display of 'You Win!' Message in Surz Scene

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1521]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
After winning a round in the Surz scene, a large "You win! Press E to keep playing" message appears. The expected behavior is for this message to appear in the center of the board in a normal size, not as a giant message.

### **STR:** 

1. Launch the explorer
2. Enter the Surz scene using the `/goto surz` command in the chat.
3. Start the game.
4. Win a round.
5. Observe the large "You win! Press E to keep playing" message.

### **Expected behavior:**
![image](https://github.com/user-attachments/assets/cb51f3f6-eae4-4a47-9af3-39ab5d3b5613)

### **Current behavior:**

https://github.com/user-attachments/assets/485e5d9d-1d70-43cb-98c2-7569a447b471

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by davidejensen** [comment]
Fixed with #1729
