### ISSUE TITLE
[QA] Yoga emotes not triggering on second floor of Nirvana Oasis (57, -66)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1534]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
In the Nirvana Oasis scene at coordinates (57, -66), avatars should automatically play Yoga emotes when reaching the second floor where the yoga mats are located. However, this functionality is not working in the EA.

### **STR:** 

1. Launch the explorer
2.` /goto 57, -66` Nirvana Oasis scene.
3. Move to the second floor where the yoga mats are located.
4. Observe the avatar's behavior upon reaching the yoga mats.

### **Expected behavior:**

https://github.com/user-attachments/assets/72bc3e79-57a8-4211-b8a6-ccc8012997a7

### **Current behavior:**

https://github.com/user-attachments/assets/cca04dbd-2209-4816-bc9e-e4208356c3fd

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by m3taphysics** [comment]
We do not have the scene code but we can verify if the SDK is even trying to play the emote.

**Comment by sandrade-dcl** [comment]
This is currently working:

![Image](https://github.com/user-attachments/assets/1c868641-e740-4f18-b6fc-5b5a1647c91a)
