### ISSUE TITLE
[QA] Scenes disappear when approached

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1535]
### **Explorer Alpha build versions:**

- **v0.14.0**

### **Issue Description:**
In DCLWW, several scenes are not rendering correctly. These scenes are visible from a distance but disappear as the player approaches them. Some of the affected scenes include:
- Scene at coordinates (53, -55)
- Scene at coordinates (53, -70)
- Scene at coordinates (53, 56)

### **STR:** 

1. Launch the explorer.
2. Navigate to coordinates (53, -55).
3. Observe the scene from a distance.
4. Approach the scene and observe the rendering behavior.
5. Navigate to coordinates (53, -70).
6. Observe the scene from a distance.
7. Approach the scene and observe the rendering behavior.
8. Navigate to coordinates (53, 56).
9. Observe the scene from a distance.
10. Approach the scene and observe the rendering behavior.

### **Expected behavior:**

https://github.com/user-attachments/assets/c62e1533-7620-423e-9045-d390200ba4b5

https://github.com/user-attachments/assets/595ab0bf-cfea-4e72-a423-6fbda9f9731d

### **Current behavior:**

https://github.com/user-attachments/assets/587a4cd0-b76e-4432-9cf7-565a1ef4ce5a

https://github.com/user-attachments/assets/59ed8cb8-86d8-42ba-a70a-3b83124ef2ad

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by m3taphysics** [comment]
We need to do a few things here @sandrade-dcl 

1. We need to verify if its an SDK7 and SDK6 scene, I would be keen to find a way to easily determine this.
2. We need to verify if it has asset bundles built for the scene.
3. We need to verify if it has LOD's built for the scene.

If we can know each of the above easily then it would be easier to diagnose these issues. Using some combination of the tools @dalkia has been working on.

**Comment by davidejensen** [comment]
I've investigated with @dalkia yesterday when he was explaining some flows of the AB converter and this is the results:

* Scene at coordinates (53, -55), we suspect the creator is doing something wrong with the scene position as it is correctly rendered when you are close but it's offset to a strange position, the assets are there and fine if we move the scene to the correct position, Juani said it is not the first time he encounters something like this
<img width="1723" alt="Screenshot 2024-08-13 at 09 40 33" src="https://github.com/user-attachments/assets/3497e3f0-1b68-4132-a23e-45867e80686c">

* Scene at coordinates (53, -70) build was re-run and now works fine
* Scene at coordinates (53, 56) build was re-run and now works fine
