### ISSUE TITLE
[QA] Autodance not triggering in The Inn (137, -3)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1556]
### **Explorer Alpha build versions:**

- **v0.15.0**

### **Issue Description:**
In the scene "The Inn" at coordinates (137, -3), the autodance feature does not start as expected. When the applause emote is triggered, the autodance should begin, but it fails to do so.

### **STR:** 

1. Launch the explorer.
2. Use the command /goto 137,-3.
3. Approach the video screen.
4. Observe the applause emote being triggered.
5. Wait for the autodance to start.

### **Expected behavior:**

https://github.com/user-attachments/assets/7d4b4a0f-e334-451f-bf09-faacd130311e

### **Current behavior:**

https://github.com/user-attachments/assets/13eaa3b9-6b6a-487f-96c1-dcf5e137f2b4

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by m3taphysics** [comment]
Verify on prod too.

**Comment by popuz** [comment]
Emotes are triggering in any surface of the scene that is above green field - tables, rocks, wooden floor. Also, when I manually move green floor a bit higher - emotes starts to work properly. Another approach that leads to this result is making floor collider convex, which makes avatar staying a bit higher, so emotes triggered normally again.

Probably they have some hardcoded values to not trigger emote if you are below some fixed y-value.

https://github.com/user-attachments/assets/2c7960a6-1ea5-460c-9956-cd9911361b7f
