### ISSUE TITLE
[QA] Metadynelabs | Robots appear distorted 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1557]
### **Explorer Alpha build versions:**

- **v0.15.0**
- **v0.16.0**

### **Issue Description:**
In the Metadynelabs world, robots appear visually distorted (exploded) while still functioning normally. This issue occurs inconsistently: sometimes the robots appear fine on the first entry but become distorted after restarting the level upon being killed. Other times, the robots are already distorted at the start of the level.

### **STR:** 

1. Launch the explorer.
2. Use the command `/world metadynelabs`.
3. Progress to level 11 or any level that has robots.
4. Observe the robots:
- Sometimes, the robots appear normal on the first entry.
- When the player is killed and the level restarts, the robots may appear distorted.
- Other times, robots are already distorted at the start of the level.

### **Current behavior:**
Robots appear visually distorted (exploded) while functioning normally, with the issue occurring inconsistently.

https://github.com/user-attachments/assets/a3be652b-da1c-4f6b-920f-9f2a251ab3c4

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by lorux0** [comment]
@Ludmilafantaniella can you please confirm if this happens on explorer-web?
