### ISSUE TITLE
Goerli | Multiplayer: Avatar animations not syncing in 'Avatar-Animations' scene (80, -1)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1635]
### **Explorer Alpha build versions:**

- **v0.16.0**

### **Issue Description:**
In the 'Avatar-Animations' scene at coordinates (80, -1), avatar animations work correctly on a single player's machine, but they do not sync across different machines in multiplayer mode. Animations performed by one player are not visible on other players' screens.

### **STR:** 

1. Launch the explorer.
2. Use the command `/goto goerli`
3. Navigate to the 'Avatar-Animations' scene at coordinates (80, -1).
4. As Player A, trigger an animation on your avatar.
5. As Player B, observe whether the animation is visible on the other machine.

### **Expected behavior:**
All avatar animations should be visible and synchronized across all players' screens in real-time.

in this scene, only thing that should be synced are the avatar animations.
The content of the scene itself doesn't have anything that requires syncing.
But when a player uses an emote, that should always be shared with others.
So, you won't see the snowballs between players, but all the emotes should sync.

### **Current behavior:**
Avatar animations performed on one machine are not visible on other machines.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

![image](https://github.com/user-attachments/assets/1990f10d-7af6-43f4-abcd-181e00974ea7)

**Comment by mikhail-dcl** [comment]
It's a known tech dept: we didn't have time to include animations into `Movement` message

**Comment by anicalbano** [comment]
Fixed by #1931
