### ISSUE TITLE
[QA] Background music persists after scene transitions in multiple locations

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1654]
### **Explorer Alpha build versions:**

- **v0.16.0**

### **Issue Description:**
Background music persists after transitioning between scenes in various locations. This issue occurs when moving from scenes like 'Casa Roustan', 'Doll House' (-102, -97), and 'Mataha Gallery' (68, 70) to any other scene (e.g., another world or Genesis Plaza). The background music from the previous scene continues playing, overlapping with the audio of the new scene. The music should stop when teleporting to a new location.

### **STR:** 

1. Launch the explorer
2. Go to one of the affected scenes (e.g., 'Casa Roustan', 'Doll House', or 'Mataha Gallery').
3. Teleport to another scene (e.g., another world or Genesis Plaza).
4. Observe if the background music from the previous scene continues playing.

### **Expected behavior:**
The background music from 'Casa Roustan' should stop when the player transitions to a new scene.

### **Current behavior:**

https://github.com/user-attachments/assets/986558f1-d152-4c2a-ba70-bcc79bc2bc9a

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
Fixed on latest v0.17.0

https://github.com/user-attachments/assets/526ae7c5-a630-4fd3-8a83-199a46859046
