### ISSUE TITLE
LiveKit: It is possible that REMOTE_AVATAR is never created

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#1661]
### **Explorer Alpha build versions:**
It is possible in some scenarios that REMOTE_AVATAR is never created and the player is invisible which causes chat to default-send through your own avatar.

See below:

![image](https://github.com/user-attachments/assets/bc444fa6-766c-4c00-a857-8975b703e4c6)

When it happened we verified we were in the same room, so that wasn't the issue. It was more so that the REMOTE_ENTITY failed to be created, no specific exceptions were noticed in this instance.

### **STR:** 

  1. Ask a kind friend to join you at 73,-7 in Goerli (you can use pre-defined parcels for speed)
  2. Take turns joining and rejoining
  3. Notice eventually you will not see the other player.

**Comment by mikhail-dcl** [comment]
We detected to inability to transmit messages unreliably under unknown circumstances.
