### ISSUE TITLE
[QA] Cannot connect to destination host

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1663]
### **Explorer Alpha build versions:**

- **v0.16.0**
- **v0.25.0**

### **Issue Description:**
While testing Explorer Alpha v0.16.0 on a MacBook Pro with an M1 Pro chip, I encountered significant rendering and performance issues. After teleporting, scenes often failed to render correctly or at all, requiring a restart to resolve. Additionally, the loading bar frequently froze at 20% or 60%, causing either a blank scene or failed teleport. The app's performance was sluggish, making it difficult to test scenes effectively.

### **LOGS:**
[Player.log.zip](https://github.com/user-attachments/files/16851401/Player.log.zip)
[Player-prev.log.zip](https://github.com/user-attachments/files/16851404/Player-prev.log.zip)

### **STR:** 

1. Launch Explorer Alpha v0.16.0 on a MacBook Pro M1.
2. Teleport between scenes.
- 100Avatars Garden -55,-121
- Meta GamiMall 145,60
- Metadynelabs world
- Teleperformance -96,108
- Dollhouse -102,-97
4. Observe rendering and performance issues.

### **Expected behavior:**

- Scenes render correctly and consistently after teleporting.
- Teleportation completes without freezing or display issues.
- Smooth and reliable app performance on Mac.

### **Current behavior:**
Teleperformance scene: After several restarts of the Explorer, it now loads as it does on Windows.

https://github.com/user-attachments/assets/5801525b-db2d-4eaf-8f75-6f411d90bec8

A video while testing. I think this is the only time I was able to teleport more than twice in a row and have the scenes load. If I’m not mistaken, in the 3rd/4th teleport you can see how the scene stops loading after teleporting.
[VIDEO EVIDENCE](https://drive.google.com/file/d/16t0AuB-6JFhd_RWsCWEiC8UPphKvdeq9/view?usp=drive_link)

#### **Additional Notes:**
	•	Model: MacBook Pro
	•	Chip: Apple M1 Pro
	•	Memory: 16GB
	•	Display: 16-inch (3456 × 2234)
	•	Storage: 335.12 GB available of 494.38 GB

**Comment by m3taphysics** [comment]
After some jumps I hit many exceptions. What is really strange is its almost like all requests stop working!

UnityWebRequestException: Cannot resolve destination host
Curl error 6: Could not resolve host: d1llt8x08lrx4z.cloudfront.net

I can no longer jump to olavra, or metadynelabs either. It cannot connect to them.

[Player.log](https://github.com/user-attachments/files/16851004/Player.log)

**Comment by m3taphysics** [comment]
Curl error 7: Failed to connect to api.segment.io port 443 after 4 ms: Error
Curl error 7: Failed to connect to api.segment.io port 443 after 0 ms: Error
Curl error 7: Failed to connect to api.segment.io port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 5 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 5 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 5 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 5 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 5 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 5 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 6 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error
Curl error 7: Failed to connect to ab-cdn.decentraland.org port 443 after 0 ms: Error

**Comment by m3taphysics** [comment]
Afte discussing with the Unity team / @dalkia we are going to try the following:

1. We know that it is caused with Asset bundles and caching, so we can play around and get some metrics as to understand how often the asset bundle cache is reused. We are able to unload it immediately in many instances where we know its not reused, which reduces the number of loaded AB's at runtime.
