### ISSUE TITLE
Goerli | Modal requires reload to display, reward not appearing in 'Simple Giveaway Scene' 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1680]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
In the 'Simple Giveaway Scene' at coordinates (83, -4), the countdown modal does not automatically display upon entering the scene. It only appears after using the `/reload` command. Additionally, after the timer reaches 00:00, the wearable reward does not appear as expected.

### **STR:** 

1. Launch the explorer.
2. `/goto goerli`
3. Navigate to (83, -4) 'Simple Giveaway Scene' 
4. Observe if the countdown modal displays automatically.
5. Use the `/reload` command in the chat to force the modal to appear.
6. Wait for the timer to reach 00:00 and check if the wearable reward appears.

### **Current behavior:**

https://github.com/user-attachments/assets/d0013cba-1ce4-4588-96b5-4569a34febe6

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by lorux0** [comment]
After the countdown finishes a box appears to claim the wearable. It is working OK on my end. @Ludmilafantaniella can you re-check it?:

<img width="1005" alt="Screenshot 2024-08-13 at 11 45 27" src="https://github.com/user-attachments/assets/a72bae0c-cfe8-4c52-927b-c06e2e0a83c8">

<img width="836" alt="Screenshot 2024-08-13 at 11 45 57" src="https://github.com/user-attachments/assets/add42cc2-ef92-4907-b10d-861600daa3fe">
