### ISSUE TITLE
Goerli | Light beams misaligned in 'Light Bounce Puzzle' (84, -4)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1682]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
In the 'Light Bounce Puzzle' scene at coordinates (84, -4), the light beams do not behave as they do in Prod. Instead of shooting light from an orb that bounces and activates runes, the light beam doesn't originate from the orb. Instead, two light beams appear: one from the rune and another horizontally across the middle of the scene, disrupting gameplay.

### **STR:** 

1. Launch the explorer
2. `/goto goerli`
3. Navigate to 'Light Bounce Puzzle' (84, -4)
4. Attempt to shoot light from the orb and observe the behavior of the light beams.
5. Note the incorrect positioning and behavior of the light beams.

### **Expected behavior:**

https://github.com/user-attachments/assets/6e6040e2-058e-4e0c-8274-0e32d0f22364

### **Current behavior:**

https://github.com/user-attachments/assets/340eef97-1389-4457-90ae-42f843ff1b71

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by m3taphysics** [comment]
I think this is due to the interaction in EA locking the camera and the scene using camera direction for the raycast. Confirming with @nearnshaw
