### ISSUE TITLE
[QA] Notification tooltip persists after switching icons or locations

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1686]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
When clicking on the notification icon in the sidebar and then selecting another icon (e.g., backpack, settings), the notification tooltip remains visible on the screen. The tooltip only disappears if you hover over the notification icon again. This issue persists even after changing locations. 

**Note:** this bug does not affect tooltips for other icons.

### **STR:** 

1. Launch the explorer
2. Click on the notification icon in the sidebar.
3. Click on another icon, such as backpack or settings.
4. Observe if the notification tooltip remains on the screen.
5. Change locations and check if the tooltip persists.

### **Expected behavior:**
The notification tooltip should disappear when clicking another icon or changing locations.

### **Current behavior:**

https://github.com/user-attachments/assets/38dfdd5c-f462-4026-9474-713333274e0c

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by anicalbano** [comment]
Unable to reproduce it on lates version (v0.46.0)
