### ISSUE TITLE
[QA] Alpha mask not applied to extra screens in 'NicoE' World

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1691]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
In the 'NicoE' World, extra screens that were added with a circular alpha mask are not displaying as intended. The alpha mask is not being applied, resulting in the screens showing the full display instead of the expected circular cutout.

### **STR:** 

1. Launch the explorer
2. Enter `/world NicoE` command on the chat
3. Locate the extra screens with the intended circular alpha mask.
4. Observe how the screens are displayed.

### **Expected behavior:**
![Screenshot 2024-08-07 at 4 30 17 PM](https://github.com/user-attachments/assets/7e692ff2-37f7-4b47-b89f-93eaac474a89)

### **Current behavior:**
![image](https://github.com/user-attachments/assets/3b899a2f-9f4f-4ece-8b8f-73f785713eb1)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by QThund** [comment]
It solves if I set the rendering queue to AlphaTest +2, although that causes another issue, geometry rendered behind loses the bloom FX.

**Comment by QThund** [comment]
Currently, the generic material that we use for most of the objects in the scene is not using the alpha texture that is being set in the code. The shader has to be expanded to support this feature as it did in the old version.

**Comment by GBirch33** [comment]
Problem with this solution is now we've got a shader which has both an alpha channel in the albedo/diffuse texture which applies alpha and also a totally separate 4 channel texture for alpha, when in reality this shader is already setup for what you need. If a material which was being use on old renderer has an alpha mask texture then copy across the alpha values in said texture into the alpha channel of the albedo/diffuse texture. We'd probably need to do this in the Asset Bundle converter really. Unless I'm missing something?

**Comment by QThund** [comment]
It's an "animated" texture, they use AVProvideo to fill it every frame, I don't know how does it work.

**Comment by AlejandroAlvarezMelucciDCL** [comment]
@QThund I had this issue assigned to me but I assigned to you since you already addressed the fix here https://github.com/decentraland/unity-shared-dependencies/pull/38
(Good job btw!)

**Comment by GBirch33** [comment]
The work for this is complete, shader created and SDK fixed up to match.
