### ISSUE TITLE
[QA]  Stuck upon teleporting in 'MetaZoo Intl' (95, 100)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1693]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
In the 'MetaZoo Intl' World at coordinates (95, 100), the player gets stuck and is unable to move after teleporting into the world.

### **STR:** 

1. Launch the explorer
2. Use `/goto 95, 100` command to enter the 'MetaZoo Intl'
3. Observe if the player gets stuck and cannot move.

### **Expected behavior:**

https://github.com/user-attachments/assets/fc29a28d-5f4f-45b5-8d40-7582212f9e42

### **Current behavior:**

https://github.com/user-attachments/assets/1a7e20dc-90d7-43eb-a8e4-aca28f7735ed

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by davidejensen** [comment]
Not much we can do, this is an SDK 6 scene that has the spawn point inside the wall, in old renderer the scene teleports the player after spawning, but in the new one it's just a static scene so we get stuck there, only fix would be the creator moving the spawn point
