### ISSUE TITLE
[QA]  'Angzaar Outpost' scene missing at coordinates (0, -82)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1695]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
The 'Angzaar Outpost' scene at coordinates (0, -82) is missing. 

### **STR:** 

1. Launch the explorer
2. Use the command `/goto 0,-82 ` Angzaar Outpost scene
3. Observe the missing scene.

### **Expected behavior:**

Uploading Angzaar Outpost - Decentraland - Opera 2024-08-08 18-01-42.mp4…

### **Current behavior:**
![image](https://github.com/user-attachments/assets/1a29691a-fe84-4ed8-b706-f31372a525bf)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by davidejensen** [comment]
![image (16)](https://github.com/user-attachments/assets/bf132833-6814-428b-aa21-011eff37e7a7)
Works after a rebuild :)
