### ISSUE TITLE
[QA] 'Space Traitor' scene missing at coordinates (-64, -34)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1696]
### **Explorer Alpha build versions:**

- **v0.19.0**

### **Issue Description:**
The 'Space Traitor' scene at coordinates (-64, -34) is missing.

### **STR:** 

1. Launch the explorer
2. Use the command `/goto -64,-34` 
3. Observe the missing or incorrect scene.

### **Expected behavior:**
![image](https://github.com/user-attachments/assets/7c493078-c09b-4a7c-a3df-b569135321f9)

### **Current behavior:**
![image](https://github.com/user-attachments/assets/2f20f98f-6165-4d73-8d00-9340e751e29c)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by m3taphysics** [comment]
@lorux0 lets verify if its some crash inside of the SDK. It may just be missing AB's.

**Comment by lorux0** [comment]
The LODs are working on my end. Needs re-checking.

![Image](https://github.com/user-attachments/assets/b9036d53-686f-47ed-9896-77714a5edcc3)

**Comment by anicalbano** [comment]
🟢 The scene is now visible on version 0.29.0. Closing the ticket
