### ISSUE TITLE
[QA] 'Failed to load il2cp' when downloading the client

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1727]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
Some users are encountering a fatal error with the message 'Failed to load il2cp' when attempting to download and launch the client for the first time.

### **STR:** 

1. Launch the Decentraland client installer.
2. Observe the download and initial data loading process.
3. Encounter the 'Failed to load il2cp' fatal error.

### **Expected behavior:**
The client should download and launch successfully on the first attempt without encountering the 'Failed to load il2cp' error.

### **Current behavior:**
A fatal error with 'Failed to load il2cp' appears during the initial client download, preventing the client from launching successfully.

### **Additional Notes:**

This video was shared on Discord by Bay, one of the people who experienced the issue: 

https://github.com/user-attachments/assets/9b0bdb46-edbe-4f65-ba0f-af2c2b3681c0

![fatalError message](https://github.com/user-attachments/assets/59609bc2-6449-47b5-9ce9-c0bb203c429d)

**Comment by m3taphysics** [comment]
I found a related issue here on a steam game: https://steamcommunity.com/app/1868140/discussions/0/3710432845032460502/

What machines are the reports coming from? Are they on an ARM machine or an old mac running parallels?

**Comment by Kaze-No-Kai** [comment]
1 user is with HP 27-cb0030ns - AMD Ryzen 5 5500U, 16 GB RAM, 512 GB SSD, AMD Radeon Graphics, Windows 11
2nd user with - Win 11 Pro, x64 AMD Ryzen 7 5700G, 32 GB RAM, 
3rd user is with an older pc  - Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz、1441 Mhz, Win 10, 4GB Ram, Intel HD 
None of these show as arm also no macs.

**Comment by aixaCode** [comment]
@Kaze-No-Kai Do the users have some antivirus software running?

**Comment by Kaze-No-Kai** [comment]
From the ones we checked with, they had no antivirus software running, will double check how it goes with the new build
