### ISSUE TITLE
[QA] LOD Loads Only When Very Close to Scenes

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1728]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
The LOD (Level of Detail) for scenes is currently set to load only when the user is very close to the scenes. This results in detailed textures appearing suddenly as the user approaches, rather than loading from a greater distance.

### **STR:** 

1. Launch the explorer.
2. Approach a scene and observe the LOD behavior.
- Scenes around street level at coordinates approximately -94, -96.
3. Note that the LOD only loads when very close to the scene.

### **Current behaviour:**
[VIDEO EVIDENCE](https://drive.google.com/file/d/1l5E7_-CiX5ArHRXQngFdqyqCS_07aNTx/view?usp=drive_link)

**Comment by m3taphysics** [comment]
Chatting with @olavra it looks to be transitioning on too short of a distance and sometimes when the LOD doesn't even exist yet.

**Comment by m3taphysics** [comment]
https://drive.google.com/file/d/1drkXfDScMzB3Rwjv8U5ArwNgy0a52sMw/view?usp=sharing
