### ISSUE TITLE
[QA] Vroomay World scene cut off screen

### ISSUE THREAD

**Issue by Juliendcl** [decentraland/unity-explorer#1736]
### **Explorer Alpha build versions:**
v0.20.0

### **Issue Description:**

Vroomway world scene is offset quite a lot. It's like the center is in the top left corner when it shouldn't be. So half the scene is cut off.
### **STR:** 

  1.Go to Vroomay World (type: /world vroomway ) 
 
### **Expected behaviour:**
We should spawn at the center of the scene

### **Current behaviour:**
 Feels like we pop up outside of it, but half of the scene has disapeared

#### **Evidence:**

https://drive.google.com/file/d/1H0N8iCPY-deTpD-tcoZVqGwN2u1LFJ0_/view

**Comment by davidejensen** [comment]
Fixed with https://github.com/decentraland/unity-explorer/pull/1758
