### ISSUE TITLE
[QA] Avatar moving on its own when pressin CAPS

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1743]
### **Explorer Alpha build versions:**
v0.20.0

### **Issue Description:**

When walking around or being on a static position, if we press CAPS key, the avatar starts moving by itself. Jumping doesn't fix the movement but we need to walk with WASD to stop it.

### **STR:** 

  1. Stay statick or move around
  2. Press CAPS key

### **Expected behaviour:**
Nothing should change

### **Current behaviour:**
The avatar moves by itself

**Comment by m3taphysics** [comment]
@anicalbano wrong video here?

**Comment by anicalbano** [comment]
> @anicalbano wrong video here?

Yes, sorry, I uploaded another video

**Comment by QThund** [comment]
Isn't this like that by design? @m3taphysics @anicalbano 
That movement is considered in the code, it's called "Auto-walk".

**Comment by QThund** [comment]
The feature will be removed.

**Comment by AlejandroAlvarezMelucciDCL** [comment]
> Isn't this like that by design? @m3taphysics @anicalbano That movement is considered in the code, it's called "Auto-walk".

Thanks for asking this and confirming, I was concerned it was not meant to be removed 💪
