### ISSUE TITLE
[QA] Cursor lock prevents interaction with emote wheel and backpack

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1748]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
When the cursor is locked by right-clicking, it becomes impossible to select an emote from the wheel after pressing 'B' and attempting to choose an emote by pressing 'E'. Similarly, pressing 'I' to open the backpack does not unlock the cursor, making it impossible to interact with items. The only workaround is to exit the backpack, unlock the cursor, and reopen the backpack to interact with wearables.

### **STR:** 

1. Launch the explorer
2. Right-click to lock the cursor.
3. Press 'B' and 'E' to attempt to edit the emote wheel.
4. Observe that you cannot select any emotes.
5. Press 'I' to open the backpack.
6. Attempt to interact with wearables.

### **Expected behavior:**
The cursor should automatically unlock when the emote wheel or backpack is opened, allowing for seamless interaction with emotes and wearables.

### **Current behaviour:**

[VIDEO](https://drive.google.com/file/d/1AhljrGxJSgiI3YqAAYkFbHS4TSpeVO_K/view)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by Juliendcl** [comment]
Happening also on Windows 10, AMD Ryzen 5 2600X, Nvidia GeForce RTX

**Comment by m3taphysics** [comment]
**Expected Behavior**: Mouse is unlocked when the emote wheel appears. It needs to go back to previous state when it is closed.
