### ISSUE TITLE
[QA] Eye, eyebrow and lip color changes with time of day

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1751]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
The color of the eyes and lips changes depending on the time of day. During certain times, the eyes and lips may take on a bluish or reddish tint. Default eyebrows are gray, default lips are gray, and eyes appear reddish. This issue causes inconsistent appearance of character features based on the time of day.

### **STR:** 

1. Launch the explorer
2. Observe the default appearance of eyebrows (gray), lips (gray), and eyes (reddish).
3. Use the /debug command to set sunset and nightfall
4. Check how the eyes and eyebrows look at different times of the day (day vs. night).

### **Expected behavior:**
The eyes and lips should maintain consistent color regardless of the time of day.

### **Current behavior:**
![Eyes-MouthColorIssue](https://github.com/user-attachments/assets/f23ebea8-5f6c-463a-9c26-9a20e7aa8435)

**Comment by Juliendcl** [comment]
![image](https://github.com/user-attachments/assets/6bbefd8d-fddd-4cbb-963c-199be3daf9d1)
![image](https://github.com/user-attachments/assets/c74a1e54-f712-4a8c-a5fe-cf02f910369c)
![image](https://github.com/user-attachments/assets/4c5721b8-50a7-4da3-92c2-fe7a8a26a3be)
