### ISSUE TITLE
[QA] Avatars not visible despite presence indicated on map

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1752]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
Even though the map indicates that there are other avatars nearby, they are not visible or readable in the scene.

### **STR:** 

1. Launch the explorer
2. Use the command /goto to navigate to any scene outside of Genesis Plaza with at least five other users.
3. Check the map to confirm the presence of other users.

### **Current behaviour:**
![image](https://github.com/user-attachments/assets/81e50a33-3d4b-4fc8-bb70-81265adb4081)

**Comment by NickKhalow** [comment]
points on map may don't disappear when avatar is
