### ISSUE TITLE
[QA] Pressing CAPS Lock Causes Avatar to Walk Automatically

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1753]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
When pressing the CAPS Lock key, the avatar starts walking by itself without any additional input. 

### **STR:** 

1. Launch explorer.
2. Navigate to any scene.
3. Press the CAPS Lock key on your keyboard.
4. Observe the avatar's movement.

### **Expected behaviour:**
The CAPS Lock key should not affect avatar movement and should only toggle between uppercase and lowercase text input.

### **Current behavior:**

https://github.com/user-attachments/assets/55b20819-7b1d-4633-96ae-32ff77afe402

**Comment by anicalbano** [comment]
Duplicated
