### ISSUE TITLE
[QA] "Less Rare" Filter Incorrectly Displays Exotic Wearables First

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1755]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
When selecting the "Less Rare" filter in the backpack dropdown, wearables with the "EXOTIC" rarity category are displayed at the beginning of the list, after "Base" wearables. The correct order should be:

1. Base
2. Common
3. Uncommon
4. Rare
5. Epic
6. Legendary
7. Exotic
8. Mythic
9. Unique

### **STR:** 

1. Ensure you have wearables of each rarity category.
2. Open the backpack.
3. From the dropdown filter, select 'Less Rare'.
4. Observe the order of the displayed wearables.

### **Current behavior:**

[VIDEO](https://drive.google.com/file/d/1-ou2CZCxdp43_ajwX05PhHPmgq4Qcrqw/view)

![image](https://github.com/user-attachments/assets/f62d513c-0dee-4895-99e3-414b8b35fcab)

**Comment by lorux0** [comment]
This is not a problem in the client. Instead it should be fixed in the server, since its the one setting the order of the elements.
