### ISSUE TITLE
[QA] -54,61 scene Emission affects nearby scenes

### ISSUE THREAD

**Issue by Juliendcl** [decentraland/unity-explorer#1760]
### **Explorer Alpha build versions:**
v0.20.0

### **Issue Description:**

Light from the scene affects nearby scenes as if they were part of the scene
### **STR:** 

  1. Go to -54,61
  2. Wait for the light projector to go yellow
  3. Look around, the light effect is applied to the surrounding scenes 

### **Expected behaviour:**
The surroundings parcels should not be affected by the light effects

### **Current behaviour:**
The surroundings parcels are affected by the lights of the scene 

#### **Evidence:**
https://drive.google.com/file/d/1CNbsgAOy1eJ1cicFsiKqFKho7Q066Ui9/view

**Comment by olavra** [comment]
Duplicate emission problem of  #1725

**Comment by GBirch33** [comment]
This isn't an emission problem, this scene literally has lights added which are almost as bright as a small sun!

![image](https://github.com/user-attachments/assets/1e347ce4-56a1-4bba-918c-710fe1acf6d9)

**Comment by GBirch33** [comment]
Since when could people add lights to a scene?

**Comment by GBirch33** [comment]
I take it back...there are 3 lights and one is purely directional, as if it's a sun!

![image](https://github.com/user-attachments/assets/5fe31404-07d0-4d13-9e9a-430d2d2c0a69)

**Comment by m3taphysics** [comment]
We shouldnt allow supporting of lights in GLTFs there is a shape up for this.

**Comment by AlejandroAlvarezMelucciDCL** [comment]
Do we know more about how those light made it through?

**Comment by AlejandroAlvarezMelucciDCL** [comment]
I talked with Ashley and Aga, this will be fixed as part of the Dynamic Lights shapeup. I'll make sure to update this issue when's done.

**Comment by AlejandroAlvarezMelucciDCL** [comment]
I submitted a fix and redeployed the scene, it should be fixed please re-test 🙇‍♂️

**Comment by DafGreco** [comment]
This issue is not currently happen on the latest released version. Closing ticket !
