### ISSUE TITLE
[QA] Soul Magic - Buttons unresponsive on minigame

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1763]
### **Explorer Alpha build versions:**
v0.20.0

### **Issue Description:**

On the playing field section `/goto -130,-80` it's not possible to make any movements with the cards, since the button contents are empty and unresponsive as shown on the following screenshot:

#### **Evidence:**
![image](https://github.com/user-attachments/assets/e6079bc8-1858-44af-a755-85681e767ac7)

**Comment by m3taphysics** [comment]
We have no way to get to this stage anymore in soul magic.
