### ISSUE TITLE
[QA] Rishi's Palace (22,-75) Scene Overly Bright, Details Not Visible

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1778]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
In the scene Rishi's Palace (22,-75), the assets appear overly bright, resulting in a washed-out look that obscures the details of the scene. The brightness levels are so high that it is difficult to perceive the edges and finer details of the platforms and other elements.

### **STR:** 

1. Launch the explorer
2. Use the command /goto 22,-75.
3. Observe the visual quality of the scene, particularly the brightness and visibility of details.
4. Compare with Prod

### **Expected behavior:**

https://github.com/user-attachments/assets/db14c9de-f82a-4177-9f57-e70e919677b4
![PROD-RishiGirl-scene](https://github.com/user-attachments/assets/11fbe6fa-b3e8-45ea-83b9-cb458c1e3de2)

### **Current behavior:**
![RishiGirl 22,-75-](https://github.com/user-attachments/assets/cbeb7220-139f-4ceb-ac87-fa76eab3ad06)
![RishiGirl 22,-75](https://github.com/user-attachments/assets/1dbb03ff-3fc7-4e60-bed7-e7efc92959ef)
![RishiGirl](https://github.com/user-attachments/assets/c49b1a9c-a5c6-49bf-a34e-6588279e7332)

**Comment by olavra** [comment]
This is the same issue we are having with the emission / bloom PP on wearables.
