### ISSUE TITLE
[QA] Client Initialization Fails

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1780]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
Several users are reporting issues when trying to launch the client. Upon clicking the launcher, they encounter either a 'Failed to Initialize Player' error or an 'Install Failed - Retry' error.

[Discussion THREAD](https://decentralandteam.slack.com/archives/C052EKZT2G7/p1723572919203519)

### **LOGS** 
[main.log](https://github.com/user-attachments/files/16623349/main.log)

### **STR:** 

1. Click on the launcher to open the client.
2. Observe if the error message appears during initialization.

### **Current behavior:**
![image](https://github.com/user-attachments/assets/c8c85860-81ca-4423-9329-ead633478e3b)

![image](https://github.com/user-attachments/assets/f27fffc7-6765-4871-8977-ed7375350ece)

**Comment by cyaiox** [comment]
Hey @Kaze-No-Kai! 

the users facing this issue can access this website: https://github.com/decentraland/unity-explorer/releases without problems?

or are they using a VPN or DNS that could block or limit access to github?

**Comment by Kaze-No-Kai** [comment]
Let me double check how it is with the new build

**Comment by aixaCode** [comment]
New version of launcher has been released, we will be testing this again with next test.

**Comment by aixaCode** [comment]
Could not reproduce with new version
