### ISSUE TITLE
[QA] Unable to see other user's passport card

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1786]
### **Explorer Alpha build versions:**
v0.20.0

### **Issue Description:**

There are some isolated cases in which the passport card of other users cannot be open. The option "view profile" does not appear when hovering over them.

### **STR:** 

  1. There must be an X number of users connected
  2. Hover over and check the profile cards
  3. At some point, it might happen that one profile card will not be visible

#### **Evidence:**

https://github.com/user-attachments/assets/aa106351-ec90-4252-9d44-5314983aaaef

#### **Additional Notes:**

Since the preconditions are unknown, it might be hard to reproduce

**Comment by aixaCode** [comment]
@anicalbano @Ludmilafantaniella Is this still happening?
