### ISSUE TITLE
[QA] UI Visibility Issues with Emote Wheel Open

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1794]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**

- Cannot Hide UI While Emote Wheel is Open:

1. Press 'U' on the keyboard to hide the UI.
2. Open the emote wheel by pressing 'B' on the keyboard.
3. Attempt to unhide the UI by pressing 'U' again.

- Cannot Unhide UI While Emote Wheel is Open and Hidden:

1. Open the emote wheel by pressing 'B' on the keyboard.
2. Try to hide the UI by pressing 'U' on the keyboard.

### **Current behaviour:**
https://drive.google.com/file/d/1sXq5LINfej8AdojohL7R3ZFPElc0VLj4/view

**Comment by mikhail-dcl** [comment]
The same as https://github.com/decentraland/unity-explorer/issues/1719
