### ISSUE TITLE
Notifications System / Nethereum Web signing allocates high amounts of memory for message signing

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#1798]
### **Explorer Alpha build versions:**
Main

### **Issue Description:**

Whenever we sign a web request we have to generate and encode a UTF8 string which is very memory inefficient and causes large allocations depending on the message size that has to be encoded.

```
NethereumAccount.cs ->         public string Sign(string message) =>            signer.EncodeUTF8AndSign(message, key);
```

![image](https://github.com/user-attachments/assets/fe58e266-58cd-4da7-b2ae-d4b716af849b)

### **STR:** 

Can be observed at intervals in the profiler.

![image](https://github.com/user-attachments/assets/d4b32bbc-7cec-4708-a1e5-aa3fdf172cb5)

### **Expected behaviour:**

Memory allocation is zero or minimal.

**Comment by mikhail-dcl** [comment]
1. We need to move `SignRequest` from the main thread, it will be require refactoring as currently it's bound to `UnityWebRequest` which is unaccessible from the background threads
2.  The majority of allocations are within `Netherium` library itself. Unfortunately there is no non-allocating API, thus, we have multiple-level string manipulation and LINQ. The source code is available we will need to do it much better on our own providing the corresponding extensions for the types participating in the calculation. Everything seems to be pretty much readable and open.

**Comment by m3taphysics** [comment]
I am not so sure we should try optimize the nethereum library unless its a very small change (doesn't feel like it is) we should evaluate alternative options for retrieval of the notifications data?

**Comment by NickKhalow** [comment]
I suggest to consider to use a rust library implementation with memory efficiency, also it could be more performant with CPU usage
