### ISSUE TITLE
[QA] Player teleported to black box instead of game pod in Metadyne

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1812]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
Sometimes when teleporting to Metadyne (/world metadynelabs), the player is placed inside a black box instead of the intended game pod. This issue disrupts the expected spawn point.
❗ This is a low repro issue and occurs inconsistently.

#### **LOGS**
[Player.log](https://github.com/user-attachments/files/16644303/Player.log)

### **STR:** 

1. Launch the explorer.
2. Teleport to Metadyne using `/world metadynelabs`.
3. Observe the player's spawn location.

### **Expected behavior:**

https://github.com/user-attachments/assets/ae525128-b31f-4c5d-a34b-5cb600d8c850

### **Current behavior:**

https://github.com/user-attachments/assets/390b3831-6393-4a6c-b7b5-dd5cbd060187

**Comment by m3taphysics** [comment]
Have not seen this for quite some time.
