### ISSUE TITLE
[QA] Cube spawning and color changing fails in Boedo.dcl.eth

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1813]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
When teleporting to Boedo.dcl.eth, the spawn cubes and color change feature do not work. Cubes fail to spawn, and any attempts to change their color are unsuccessful.

### **STR:** 

1. Launch the explorer.
2. Teleport to `boedo.dcl.eth`.
3. Attempt to spawn a cube.
4. Attempt to change the color of the cube.

### **Current behaviour:**

https://github.com/user-attachments/assets/cfcf0e68-8b64-44ef-9b08-64813baf3713

**Comment by dalkia** [comment]
@Ludmilafantaniella In the video, you are outside of the scene. Give a step to the right and youshould be able to spawn cubes / change colurs.

@aixaCode We should make a PR to disable tooltips. They are definitely confusing
