### ISSUE TITLE
FPS Drop when spawning multiple avatars

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-explorer#1816]
### **Issue Description:**

As more avatars are spawned, a noticeable drop in FPS occurs. 
Since the client is often CPU-bound, this decline suggests that some systems are generating CPU overhead, increasing frame time. 
This issue is also happening in worlds, which are less intensive on the GPU side.
### **STR:** 

1. Launch the client.
2. Spawn multiple avatars.
3. Observe the drop in FPS.

### **Expected behaviour:**
Spawning avatars should have less impact on CPU performance.

**Comment by m3taphysics** [comment]
Drastically Improved with this chnge: https://github.com/decentraland/unity-explorer/pull/1855

**Comment by m3taphysics** [comment]
Closing as a duplicate of #1876
