### ISSUE TITLE
[QA]Material transparency issue allows visibility through assets

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1826]
### **Explorer Alpha build versions:**

- **v0.20.0**

### **Issue Description:**
There is a material transparency issue at coordinates -3,132 where you can see through assets even though they should be opaque. This issue is noticeable when viewing avatars and materials through the blue panel in the middle of the scene.

### **STR:** 
1. Launch the explorer.
2. Teleport to coordinates -3,132.
3. Observe avatars and materials through the blue panel in the middle of the scene.

### **Expected behavior:**
The asset should be opaque and not allow visibility through it.

### **Current behavior:**
You can see through the asset even though it should be opaque.

https://github.com/user-attachments/assets/27b62722-d5db-45d4-81a7-0352bc777a5b

https://drive.google.com/file/d/1b6uid3DDJ3I8yfY6TgieLv0qh5TiMLmO/view

**Comment by anicalbano** [comment]
Fixed in current v0.39.0

https://github.com/user-attachments/assets/46eec816-3ba1-4dea-98e3-40fb753b33f9
