### ISSUE TITLE
[QA] Meta Residence Tower not loading

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1827]
### **Explorer Alpha build versions:**

- v0.21.0

### **Issue Description:**
The Meta Residence Tower fails to load when visiting the scene at coordinates 117,-26. 

### **STR:** 
1. Launch the explorer.
2. Teleport to coordinates 117,-26.
3. Observe whether the Meta Residence Tower loads in the scene.

### **Expected behavior:**
![Metaresidence-PROD](https://github.com/user-attachments/assets/e80ca2ca-ec45-40b3-aa02-b5fb211a9d90)

### **Current behavior:**
![MetaResidenceTower](https://github.com/user-attachments/assets/c8db61e5-88e6-43f6-8c7d-0d99cb7e11d3)

**Comment by davidejensen** [comment]
Fixed with the recent changes in AB converter infra
