### ISSUE TITLE
[QA]  Missing hands in backpack/passport preview with certain hoodies or jacket wearables

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1836]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
When previewing certain hoodies or jacket wearables, the hands are missing in the backpack preview. 
This issue occurs specifically with items like the one found at the following URN: [https://decentraland.org/marketplace/contracts/0xa7d07275cadc9938c311e117d78c34a35a811050/items/0](https://decentraland.org/marketplace/contracts/0xa7d07275cadc9938c311e117d78c34a35a811050/items/0). 

```
Wearable Link: https://nft-api.decentraland.org/v1/items?contractAddress=0xa7d07275cadc9938c311e117d78c34a35a811050&itemId=0
Wearable URN: urn:decentraland:matic:collections-v2:0xa7d07275cadc9938c311e117d78c34a35a811050:0
```

#### **LOGS:**
https://drive.google.com/file/d/19QBYgtapqII5eJMTFCVF6EAC3ECPqMKz/view

### **Current behavior:**
![image](https://github.com/user-attachments/assets/14567133-4eba-48e2-ac57-08c2e2b62f34)
![image](https://github.com/user-attachments/assets/44c8c448-5698-4812-95f0-77be51cd423a)

#### **Additional Notes:**
Neither the support team nor I were able to reproduce the issue with the wearables we had.

**Comment by sandrade-dcl** [comment]
I've been able to hardcode the wearable `urn:decentraland:matic:collections-v2:0xa7d07275cadc9938c311e117d78c34a35a811050:0` into my current assigned wearables and the issue doesn't reproduce:

![Image](https://github.com/user-attachments/assets/64587311-2b6b-4855-8a92-27a57643a9ec)
