### ISSUE TITLE
[QA] LaLigaLand scene not loading properly at -149,64 (SDK7)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1838]
### **Explorer Alpha build versions:**

- **VO.21.0**

### **Issue Description:**
The LaLigaLand scene at coordinates -149,64 is not loading properly.

### **STR:** 

1. Launch the explorer.
2. Teleport to coordinates -149,64.
3. Observe the loading behavior of the LaLigaLand scene.

### **Expected behavior:**
![Laliga-PROD](https://github.com/user-attachments/assets/5c64fc32-45ac-4681-a0c6-b09e72c4a254)

### **Current behavior:**
![LaLigaLand-EA](https://github.com/user-attachments/assets/5e4be910-7016-4d72-8969-7ac0095e7529)

**Comment by davidejensen** [comment]
on windows the scene was working, after the last conversion it works on mac as well
