### ISSUE TITLE
[QA] Bubbles - FBRN x Zom Emote not working 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1841]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
The Bubbles - FBRN x Zom Emote is not functioning in Client 2.0. This issue persists across multiple instances, as shown in the provided video. The emote works in previous versions but fails in Client 2.0.

#### **Player LOGS:**
[FBRN_log_Explorer.zip](https://github.com/user-attachments/files/16680034/FBRN_log_Explorer.zip)

### **STR:** 

1. Launch Client 2.0.
2. Equip the Bubbles - FBRN x Zom Emote.
3. Attempt to use the emote and observe.

### **Current behavior:**
https://drive.google.com/file/d/1J6iyRcDLtbSzoCOqnt8zxVNzrldp0-Eb/view

**Comment by lorux0** [comment]
@Ludmilafantaniella I need the urn of the wearable

**Comment by lorux0** [comment]
Is this one? https://decentraland.org/marketplace/contracts/0x97822560ec3e3522c1237f85817003211281eb79/items/0

**Comment by lorux0** [comment]
The emote is not following the naming conventions: https://docs.decentraland.org/creator/emotes/props-and-sounds/#naming-conventions

It is using `.Prop` instead of `_Prop`.
The creator should fix this problem.
