### ISSUE TITLE
[QA]  Avatar gets stuck inside GP bar

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1843]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
When interacting with the GP bar, the avatar can get stuck after jumping or running through the bar multiple times. This issue causes the avatar to be immobile, requiring a respawn to resolve the situation.

### **STR:** 

1. Launch the explorer.
2. Go to the GP bar.
3. Run through the bar and jump on it a few times.
4. Observe if the avatar gets stuck inside the bar.

### **Current behavior:**

https://github.com/user-attachments/assets/b6d309d6-0149-4d18-a644-269e9874cc12

#### **Player LOGS:**
[Player.zip](https://github.com/user-attachments/files/16680363/Player.zip)

**Comment by aixaCode** [comment]
@ShibuyaMartin can you please take a look at Genesis Plaza colliders?

**Comment by ShibuyaMartin** [comment]
fixed

**Comment by anicalbano** [comment]
Checked on windows and Mac and we cannot replicate the issue. Closing it now! ✔️
