### ISSUE TITLE
[QA] Summary of Emote Issues

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1847]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
1. **Carnaval Muse**: Displays a strange ghost head.
2. **Feelin' Myself**: Does not load or play at all.
3. **Planting Seeds**: The plant remains at 100% size instead of growing from low to maximum.
4. **Triangle Tryout**: Shows a quad on the ground that should not be present.
5. **Siesta en la Fiesta**: Loads partially, and the animation gets mixed with a previously selected one.

### **WEARABLE URNs:** 

1. **Carnaval Muse**
URN: https://decentraland.org/marketplace/contracts/0x5f6ca7e5c8055c4cb8736d065f619cdd0cf28752/items/4

2. **Feelin' Myself**
URN: https://decentraland.org/marketplace/contracts/0xa80aea22d0fe9d34ca72ce304ef427bbefee1f11/items/2

3. **Planting Seeds**
URN: https://decentraland.org/marketplace/contracts/0xca53b9436be1d663e050eb9ce523decbc656365c/items/1

4. **Triangle Tryout**
URN: https://decentraland.org/marketplace/contracts/0xe79cadd6fb15a626a48d2bbb60d4450eb196c84d/items/9

5. **Siesta en la Fiesta**
URN: https://decentraland.org/marketplace/contracts/0xfcc2c46c83a9faa5c639e81d0ad19e27b5517e57/items/0

### **LOGS:**
[Player Log METATIGER-Emoteissues.zip](https://github.com/user-attachments/files/16681967/Player.Log.METATIGER-Emoteissues.zip)

### **Current behaviour:**

https://github.com/user-attachments/assets/e63662a7-2574-4ccc-b8d6-4feca86f7d40

![image](https://github.com/user-attachments/assets/069df3a0-cde3-401d-b9af-12e9a7104c30)

https://github.com/user-attachments/assets/3d345ce3-d5db-45fa-9189-581377d553a0

https://github.com/user-attachments/assets/a08a75c5-b0c5-4435-a327-eec82bac2d7c

https://github.com/user-attachments/assets/e16ede40-5bb7-478a-81b2-ff33afdf1cec

https://github.com/user-attachments/assets/0c47fdbf-84b1-4d6f-8acc-d19dd85e0eab

**Comment by lorux0** [comment]
Emote was missing AB for windows
- urn: `urn:decentraland:matic:collections-v2:0xa80aea22d0fe9d34ca72ce304ef427bbefee1f11:2`
- hash: `bafkreigl3xc76fimf577cqkhrgz5ww46hnnys3kplxmgggn6o5lkszn5mm`

It is working fine on my end

https://github.com/user-attachments/assets/dec1774d-0bac-4730-8713-d7461649a4ef

**Comment by lorux0** [comment]
Added a new rule for **Carnaval Muse** so skinned mesh renderers starting with `f_` in hierarchy are invisible. This change could break other emotes specially those 2.0 which may contain props.

https://github.com/user-attachments/assets/7baa2255-657d-43bc-b23c-24c87d7dd25f
