### ISSUE TITLE
[QA] Avatar gets stuck in bushes around the Plaza

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1850]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
The avatar gets stuck in the bushes surrounding the Plaza when running through or jumping on them. The issue is easier to reproduce by running quickly (using directional arrow + Shift) and then jumping onto the bushes.

### **STR:** 

1. Launch the explorer.
2. Go to the Plaza.
3. Run quickly through the bushes, around the main building, using the directional arrow + Shift.
4. Jump onto the bushes and observe if the avatar gets stuck.

### **Expected behavior:**
The avatar should be able to move freely through and over the bushes without getting stuck.

### **Current behavior:**

https://github.com/user-attachments/assets/fd85d55c-03db-405b-96aa-f3a89a965fc2

#### **LOGS:**
[Player.zip](https://github.com/user-attachments/files/16693117/Player.zip)

#### **Additional Notes:**

Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by aixaCode** [comment]
@ShibuyaMartin Could you take a look?

**Comment by ShibuyaMartin** [comment]
fixed!

**Comment by anicalbano** [comment]
Cannot replicate on both Win and Mac ✔️ closing the ticket as it works and didn't created any other issue :)
