### ISSUE TITLE
First person camera and Third person camera are not synchronized

### ISSUE THREAD

**Issue by NickKhalow** [decentraland/unity-explorer#186]
When character running in other direction different from initial 

1. Open DynamicSceneLoading
2. Turn your view about 90-120 degrees
3. Switch camera
5. You will see that now you are facing other direction

Expected that camera saves same direction despite turning between 1'st and 3'rd person view

You can find a video below
https://github.com/decentraland/unity-explorer/assets/71646502/d0c46d51-298c-4064-8e51-6d8eeed16f57

**Comment by anicalbano** [comment]
Solved in newest builds
