### ISSUE TITLE
[QA] Sometimes Web page partially minimizes when switching from client in full screen mode

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1867]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
When using a single monitor setup with graphic settings set to full screen, switching from the client back to an open web page after some time causes the web page to partially minimize. The user is forced to manually minimize and maximize the web page to restore it to full screen.

❗ I marked it as low priority since there's no 100% reproducible.

### **STR:** 

1. Set up a single monitor and configure the client's graphic settings to full screen.
2. Open a web page in the background.
3. Switch to the client and use it for a while.
4. Exit back to the web page.
5. Observe the web page partially minimizing.

### ❌ **Actual Result**

The web page partially minimizes when switching back from the client in full screen mode.

### **VIDEO EVIDENCE** :

https://github.com/user-attachments/assets/7ad553ba-24bc-4f22-88cc-7e52ad200e17

### ✅ **Expected Result**

The web page should remain fully maximized when switching back from the client.

#### **Player LOGS:**
[OfficialCryptoCube-LOGS.log](https://github.com/user-attachments/files/16729531/OfficialCryptoCube-LOGS.log)

**Comment by aixaCode** [comment]
This seems to be a problem with that configuration of OS, it's out of scope for the client
