### ISSUE TITLE
[QA] Avatar missing from backpack preview after reopening

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1875]
### **Explorer Alpha build versions:**

- **v0.21.16-alpha-main**

### **Issue Description:**
When opening the backpack by pressing 'B' and 'E', exiting, and reopening it again, the avatar preview is missing. Emotes and wearables load as expected, but the avatar itself does not appear in the preview.

### **STR:** 

1. Launch the explorer.
2. Press 'B' and 'E' to open the backpack.
3. Exit the backpack.
4. Press 'B' and 'E' again to reopen the backpack.
5. Observe that the avatar is missing from the preview, while emotes and wearables still load.
6. Exit the backpack
7. Press 'I' to reopen the backpack
8. Observe that the avatar is missing from the preview, while emotes and wearables still load.

### **Expected behavior:**
The avatar should be visible in the backpack preview upon reopening it.

### **Current behavior:**

https://github.com/user-attachments/assets/9c16f34a-e12c-45f1-86b1-9e29454886bd

![Editor Flags PR1870 - Main](https://github.com/user-attachments/assets/9f2b0777-878b-48c8-b1fb-11ad780cfe9e)

### Notes

- The issue occurs specifically after reopening the backpack.
- Was tested on the Main version that contains the last changes made

**Comment by anicalbano** [comment]
Unable to reproduce on v0.28.0
