### ISSUE TITLE
[QA] Testing Session | Low FPS in Genesis Plaza/Bar with multiple players

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1876]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
Players experience low FPS (10-15 fps) when in the Genesis Plaza/Bar scene, even with high-spec PCs. The issue occurs when there are 20-25 people in the scene. FPS significantly improves when moving outside the scene.

### **STR:** 

1. Launch the explorer and go to Genesis Plaza/Bar.
2. Ensure there are 20-25 players in the scene.
3. Observe the FPS while inside the scene.
4. Move outside of Genesis Plaza/Bar and observe the FPS improvement.

### **Expected behavior:**
FPS should remain stable both inside and outside the Genesis Plaza/Bar scene, regardless of the number of players.

### **Current behavior:**
![BeforeRestart](https://github.com/user-attachments/assets/25d9c531-59c7-41aa-ac07-2b617556c908)

<img width="429" alt="Nikki  - Low FPS in GP" src="https://github.com/user-attachments/assets/fcdcbfcd-fb74-4fe6-b64c-51cc24c208e0">

**Comment by m3taphysics** [comment]
Drastically Improved with this change: https://github.com/decentraland/unity-explorer/pull/1855 (pending merge)
