### ISSUE TITLE
[QA] Testing Session | Missing avatars for some players with many participants

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1877]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
During a testing session with approximately 25 participants, some players initially saw only name tags and not the full avatars as more participants joined. This issue affected only certain avatars; some loaded correctly while others displayed only the name tag. 

### **STR:** 

1. Launch the explorer and join a session with around 25 participants.
2. Observe that all avatars load correctly and that no avatars are missing, ensuring there are no ghost name tags.

### **Expected behavior:**
All players should see full avatars consistently without needing to restart the application.

### **Current behavior:**
![image](https://github.com/user-attachments/assets/436ccdbb-2f69-4251-91cd-e202b4c56fc3)

### Notes

- The issue was resolved after relaunching the client.

**Comment by lorux0** [comment]
This issue is potentially fix on this pr: https://github.com/decentraland/unity-explorer/pull/2399
We will wait until the next group testing session to re-validate it.

**Comment by anicalbano** [comment]
Fixed on v0.38 live, all avatars are visible:

![image](https://github.com/user-attachments/assets/5ce8eeee-583c-4d6a-b378-68dc7b42f9b3)
