### ISSUE TITLE
[QA] Testing Session | Avatars and backpacks stop loading with many participants

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1878]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
During a testing session with around 25 participants, avatars stopped loading in the backpack and other users' avatars were missing when opening their passports. Initially, avatars and passports loaded correctly, but as more participants joined, the issue worsened, leading to more missing avatars and backpacks. 

### **STR:** 

1. Launch the explorer and join a session with around 25 participants.
2. Observe the avatars in the backpack and other users' passports.
3. Note if avatars stop loading in the backpack and if other users' avatars are missing in the passports as the number of participants increases.

### **Expected behavior:**
Avatars should load correctly in the backpack and passports consistently, even with a high number of participants, without needing to restart the application.

### **Current behavior:**

![avatarmissing1](https://github.com/user-attachments/assets/fab8858f-c13d-4283-a144-8c88b95dbd40)

![avatarMissing](https://github.com/user-attachments/assets/fa3d526d-7505-4b58-8273-4850857aaf89)

https://github.com/user-attachments/assets/27463899-b729-4ad7-88e0-3b529bbf3395

### Notes

- The problem worsens as more participants join the session.
- The issue is mitigated after relaunching the client.

**Comment by m3taphysics** [comment]
Hoping lazy loading improves the situation.

**Comment by lorux0** [comment]
This issue is potentially fix on this pr: https://github.com/decentraland/unity-explorer/pull/2399
We will wait until the next group testing session to re-validate it.
