### ISSUE TITLE
[QA] High hiccups and loading issues in Angzaar Outpost scene (0,72)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1879]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
The Angzaar Outpost scene (0,72) shows significant performance issues, particularly with high hiccups in the performance report. The scene has the highest hiccups in the thousand frames average, which impacts its loading and overall performance.

### **STR:** 

1. Launch the explorer.
2. Teleport to the Angzaar Outpost scene (-9,-91). Or walk in from Genesis Plaza.
3. Observe the performance and loading issues within the scene.

### **Expected behavior:**
The Angzaar Outpost scene should load smoothly with minimal hiccups and consistent performance.

### **Current behavior:**

![image](https://github.com/user-attachments/assets/4192ce14-3839-48bd-9fc9-284056d7f28e)

### Notes

- During a testing session with approximately 25 participants, many players experienced the screen displaying 'loading' indefinitely, which aligns with the performance issues reported.

**Comment by popuz** [comment]
coordinates for the scene are `-9,-91` 
![Image](https://github.com/user-attachments/assets/925a6410-6d03-43ca-9c20-9efced6bcb40)

**Comment by sandrade-dcl** [comment]
The scene loading is currently completely broken in both old and alpha renderer.

Both are throwing this error when the scene try to send a request to `https://lkdcl.co/dcl/angzaar/test/authorize/0x1b8ba74cc34c2927aac0a8af9c3b1ba2e61352f2/main`:

### Explorer Alpha
```
Curl error 60: Cert verify failed. Certificate has expired. UnityTls error code: 7
```

```
[SCENE_FETCH_REQUEST] (-9, -91): Exception occured on loading GenericGetRequest from https://lkdcl.co/dcl/angzaar/test/authorize/0x1b8ba74cc34c2927aac0a8af9c3b1ba2e61352f2/main with RequestEnvelope:
WebRequestType: GenericGetRequest
WebRequestArgs: GenericGetRequest
CommonArguments: CommonArguments: https://lkdcl.co/dcl/angzaar/test/authorize/0x1b8ba74cc34c2927aac0a8af9c3b1ba2e61352f2/main with attempts 3 with timeout 30 with downloadHandler 
Args: DCL.WebRequests.GenericGetArguments
Cancellation Token cancelled: False
ReportCategory: DCL.Diagnostics.ReportData
Headers: WebRequestHeadersInfo: EMPTY
SignInfo: NONE
Attempt Left: 0
```

### Old web renderer (production)
![Image](https://github.com/user-attachments/assets/6641a110-f89b-4b4a-9baf-400ea233de07)
![Image](https://github.com/user-attachments/assets/8a2b5adb-840c-4171-a1de-522ab3828691)

**Comment by NickKhalow** [comment]
It's mostly UI hiccups

![Image](https://github.com/user-attachments/assets/6e92accd-d2f2-4557-848b-728d8d3d0ab7)
![Image](https://github.com/user-attachments/assets/a1ba0220-5f8d-4d07-98ed-21f06ea463be)
![Image](https://github.com/user-attachments/assets/e77b804e-6f55-45e7-8be1-b4f0c8b99bb5)

**Comment by NickKhalow** [comment]
Closed due the scene is broken

**Comment by m3taphysics** [comment]
The scene is no longer available.
