### ISSUE TITLE
[QA] Nametag overlapping the verified icon

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1880]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
Sometimes, users' nametags appear outside the box and overlap the verified icon. This issue was observed during a testing session with around 25 participants after one of the relaunches. The specific STR to reproduce the issue is not clear.

### **STR:** 

1. Launch the explorer and join a session with multiple participants.
2. Observe the nametags and verified icons for different users.
3. Note if any nametags appear outside the box and overlap the verified icon.

### **Expected behavior:**
Nametags should remain within their designated box and not overlap with the verified icon.

### **Current behavior:**
![NAMETAG](https://github.com/user-attachments/assets/f5e84563-50e8-4f34-8554-6b338b439601)

### Notes

- Issue was observed during a testing session with approximately 25 participants.
- Specific STR to reproduce the issue is not defined.

**Comment by aixaCode** [comment]
If it's hard to repro, it could be related to pooling issue

**Comment by QThund** [comment]
It's been impossible to reproduce so far.
