### ISSUE TITLE
[QA] Trees losing bark texture

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1884]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
In the scene, yellow trees and the little pink tree on the roads have lost their bark texture. 

### **STR:** 

1. Launch the explorer and navigate to the roads with yellow trees and the little pink tree. Eg: (-107,2) or (-32,29)
2. Observe the bark texture on these trees.

### **Expected behavior:**
The yellow trees and the little pink tree on the roads should display their bark texture correctly.

### **Current behavior:**
![capture_240826_113343](https://github.com/user-attachments/assets/cec4abf9-053d-406c-9af5-21f346bbb2ac)
![2024-08-26 16_13_57-Window](https://github.com/user-attachments/assets/be4f1fd3-cb0e-4114-afa3-56b916cb9ee1)
![2024-08-26 16_11_34-Window](https://github.com/user-attachments/assets/31c2ee2a-6f06-4fa6-b5c5-2319bbd6aef4)

**Comment by anicalbano** [comment]
🔴 In olavra world, you can see in the distance that some of the barks are still white and we need to get closer to them in order to show the correct texture

https://github.com/user-attachments/assets/6496b386-c8e6-40ef-a0a9-ee18ba049fce
