### ISSUE TITLE
[QA] testenviroment scene is empty 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1885]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**

Testenvironment scene is missing on EA. On [Prod](https://decentraland.org/play/?realm=TestEnvironment.dcl.eth), the `testenvironment` world loads correctly with visible assets.

### **STR:** 

1. Launch the explorer.
2. Teleport to the `testenvironment` world.
3. Observe that the world is empty with no assets.

### **Expected behavior:**
![TestEnvironment-Prod](https://github.com/user-attachments/assets/1a8e48dd-31b1-48cd-9b17-e147e86d3f81)

### **Current behavior:**
![testEnvironment-EA](https://github.com/user-attachments/assets/5d2279a3-4456-481b-94ad-55c6ddcd5663)

**Comment by m3taphysics** [comment]
After speaking to @AlejandroAlvarezMelucciDCL and @pravusjif we do not use this world/scene (it may be SDK6)  

It should be deployed https://sdk-team-cdn.decentraland.org/ipfs/sdk7-test-scenes-main-latest realm at the 54,-55 position
