### ISSUE TITLE
Batch the skinning compute shader

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-explorer#1888]
This [PR ](https://github.com/decentraland/unity-explorer/pull/1855) showed that we have benefit of batching all the avatar matrix job into one instead of  multiple one.

The same optimization could be done for the compute shader part of skinning; since right now we have one compute shader skinning per avatar

**Comment by m3taphysics** [comment]
Pending: https://github.com/decentraland/unity-explorer/pull/1855 (pending merge)
