### ISSUE TITLE
[QA] Knights of Antrom (144,-7) scene missing

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1889]
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
The scene "Knights of Antrom" at coordinates (144,-7) is missing. It does not load or appear as expected. In the production environment (Prod), the scene is available and loads correctly.
❗` This is an SDK7 scene.`

### **STR:** 

1. Launch the explorer in EA.
2. Teleport to coordinates (144,-7).
3. Observe that the "Knights of Antrom" scene does not appear.

### **Expected behavior:**
The "Knights of Antrom" scene should be present and load correctly at coordinates (144,-7) in EA, as it does in Prod.
![KnightsofAntrom-PROD](https://github.com/user-attachments/assets/76cdcc11-db97-4c50-a6e4-8f2577785286)

### **Current behavior:**
The "Knights of Antrom" scene is missing and does not load at coordinates (144,-7) in EA.

![KnightsofAntrom-EA](https://github.com/user-attachments/assets/1713a318-bf53-420f-8d47-a8ca3e2c6c63)

**Comment by davidejensen** [comment]
Fixed with latest conversion after the recent AB server changes
