### ISSUE TITLE
[QA] Changing cube colors not in sync for all users

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#1923]
### **Explorer Alpha build versions:**
v0.21.0

### **Issue Description:**

`/goto boedo` when in multiplayer, the cube is not always showing the colors changing for some players present on scene, while it can be seen in sync for the other players.

### **STR:** 

  1. `/goto boedo`
  2. Other players should join and change the color of the cube

### **Expected behaviour:**
The cube changes to the same color for all the players present on scene

### **Current behaviour:**
For some players, the cube changing colors is out of sync

#### **Evidence:** (In this case, it was changing for me, but not for Misha)
![image](https://github.com/user-attachments/assets/922d6c13-936d-4f77-b0dc-496f053eb0d6)
![image](https://github.com/user-attachments/assets/c8e919a5-c907-4eb1-b26b-2e89c9d1edac)

**Comment by m3taphysics** [comment]
Assigniing this to you @gonpombo8 until we have a solution to sync the scene as part of the OnEnter events.

**Comment by m3taphysics** [comment]
Multiplayer changes are being done by @mikhail-dcl we can re-test this when its ready
