### ISSUE TITLE
[QA] Lock ups occurring on explorer with and without activity of the player

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1947]
### **Explorer Alpha build versions:**

Not version specific, the issue started on v0.23.0 onwards (currently 0.27.0)

### **Issue Description:**
There are two different cases in which we can experience the the lock that forces the user to close the app:

- During certain activity, cases like playing minigames (can be checked on 2048 `/goto 43,100` or Bubble Shooter `/goto -121,-60`). This specific case is harder to reproduce, since it might take a minimum of 30 minutes.
- By going to Goerli and walking around for a period of time bigger than 10 minutes
- By staying idle for a minimum of 10 mines (the time is an estimation, it can take a little longer)

### **STR:** 

Lock ups during activity: move around or play games.
Lock ups during inactivity: staying idle on Genesis Plaza during the mentioned amount of time should work.

#### **LOGS (Idle stance):**
[Player-prev.zip](https://github.com/user-attachments/files/16805621/Player-prev.zip)

[Player.zip](https://github.com/user-attachments/files/16805622/Player.zip)

#### **LOGS (During activity):**
[Player.log](https://github.com/user-attachments/files/17013221/Player.log)

#### **Additional Notes:**
- Clearing cache improves performance temporarily, but the lock ups reoccur after some time.

- Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
- Windows 10 Pro 64-bit AMD Ryzen 7 3700 8 Core AMD Radeon RX 5700 XT

**Comment by mikhail-dcl** [comment]
Possible traces:

https://decentraland.sentry.io/performance/trace/507ad5bb94be4ef1a8a691a6987818ab/?fov=0%2C338000&node=trace-root&project=4506075736047616&query=os.name%3AmacOS&referrer=issue-stream&source=performance_transaction_summary&stream_index=2&tab=events&timestamp=1725310038

**Comment by m3taphysics** [comment]
Should be fixed with #2089
