### ISSUE TITLE
RendererPipeline - Performance spikes

### ISSUE THREAD

**Issue by NickKhalow** [decentraland/unity-explorer#1953]
### **Issue Description:**

These spikes occur in random time running the game. It happens both in the editor and the build.

![image (21)](https://github.com/user-attachments/assets/d7c1ae49-8d82-4775-9b2a-6bc85279670d)
![image (20)](https://github.com/user-attachments/assets/a9c8de6a-4199-4ff9-8068-537b4d05e45c)

### **STR:** 

  1. Launch build/editor with profiler
  2. Run around the world for ~5 mins and look at your charts

#### **Additional Notes:**
Occured on Mac, M1 Pro

**Comment by m3taphysics** [comment]
Can you investigate to see if this happens for you @QThund ? You can now access profile builds here too: https://github.com/decentraland/unity-explorer/actions/workflows/build-profile-nightly.yml

**Comment by QThund** [comment]
It's the Garbage Collector.

**Comment by QThund** [comment]
According to Misha's research in the past, it would be so expensive to change how the CRDT messages ahre processed to avoid these allocations, so this task should be postponed.

**Comment by m3taphysics** [comment]
It is going to be very difficult to optimize the libraries from ClearScript
