### ISSUE TITLE
[QA] Launcher stuck at loading screen 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#1961]
### **Explorer Alpha build versions:**
N/A

### **Issue Description:**
When getting into the launcher of DCL, the user gets stuck at the loading screen and never finish loading 

### **STR:** 

  1. Download the latest version of the launcher 
  2. Open the launcher 
  3. Verify that the loading screen never finishes loading 

### **Expected behaviour:**
The user surpasses the loading screen and it's able to log in  with the metamask account 

### **Current behaviour:**
The user is not able to surpass the loading screen of DCL 

#### **Evidence:**
Log of the user : [Player.log](https://github.com/user-attachments/files/16847517/Player.log)
https://github.com/user-attachments/assets/5c3a39f2-8c10-49ba-8e69-9e6289e9da23
Wallet : 0x3e5502a2b5Ea9b1C8355F0125f5755De32aC0C12 

#### **Additional Notes:**
Windows 11 pro

**Comment by sandrade-dcl** [comment]
Apparently fixed from v0.25 on.

**Comment by DafGreco** [comment]
Fixed from 0.25 onwards
