### ISSUE TITLE
[QA] App crashes after teleporting to another scene 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#1976]
### **Explorer Alpha build versions:**
v0.25.2 / v0.25.3

### **Issue Description:**
Whenever a user wants to teleport to any part of the map the app crashes right after teleporting. 

### **STR:** 

  1.Open v.0.25.2 
  2.Verify that you'll appear on the genesis plaza
  3.Teleport to another scene
  4. Validate that the app crashes right after teleporting  

### **Expected behaviour:**
The app should not crash after teleporting to another scene 

### **Current behaviour:**
The app crashes after teleporting to a scene 

#### **Evidence:**

https://github.com/user-attachments/assets/80de82bd-b5bc-47ad-8426-17a81ce7848d

https://github.com/user-attachments/assets/2ff256a6-c498-4663-81ac-c0fc1ac2dd92

 
[Player.log](https://github.com/user-attachments/files/16875386/Player.log)

#### **Additional Notes:**
Windows 11 pro
RAM 16,0 GB

**Comment by m3taphysics** [comment]
@DafGreco I cannot reproduce this in v0.25.10-alpha-main (latest main build) can you try again?

https://github.com/decentraland/unity-explorer/actions/runs/10744302873

**Comment by DafGreco** [comment]
This issue is no longer happening on version 0.25.10. Closing this ticket for now with evidence attached. 

https://github.com/user-attachments/assets/a6b3351c-b3a1-4227-8221-ae6d29b69a31
