### ISSUE TITLE
[QA] A grey overlay appears on the backpack 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#1995]
### **Explorer Alpha build versions:**
0.25.21

### **Issue Description:**
When tapping multiple times the letter M and I, you are able to see a grey overlay when opening the backpack again. 

### **STR:** 

  1.Open the build 0.25.21
  2. Validate that you will appear on the Genesis Plaza 
  3. Press M and I multiple times 
  4. Verify that a grey overlay appears on the backpack

### **Expected behaviour:**
No grey overlay should appear when tapping those keys at the same time for multiple times 

### **Current behaviour:**
A grey overlay appears on the backpack when pressing the keys ''M'' and ''I'' multiple times 

#### **Evidence:**

https://github.com/user-attachments/assets/6f37b834-a543-4265-aa6c-48adf198dd8b

#### **Additional Notes:**
Windows 11pro 
RAM 16 GB

**Comment by anicalbano** [comment]
Unable to repro on latest versions (current v0.46.0)
