### ISSUE TITLE
[QA] App crashes after teleporting to Neon City 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2008]
### **Explorer Alpha build versions:**
This issue was found on version  0.25.30

### **Issue Description:**
As a user I wanted to travel to Neon city but when I tried to use the command to teleport , the Screen turned black and a exception appeared 

### **Reproduction:**
5/5
 

### **STR:** 
1. Open v0.25.30
2. Go to Tower of Hanoi first 23,-25
3. Once you are in Tower of Hanoi , travel to Neon City -6,77
4. Play with the puzzles 
5. Validate that the app crashes right after touching the puzzles

### **Expected behavior:**
App should not crash after teleporting to Neon City 

### **Current behavior:**
The app crashes after teleporting to Neon city 

#### **Evidence:**
[Player.log](https://github.com/user-attachments/files/16948223/Player.log)

https://github.com/user-attachments/assets/5c018e7e-b7c3-41e1-9feb-b77990b9dfb8

#### **Additional Notes:**
Windows 11 PRO 
RAM 16 GB

**Comment by sandrade-dcl** [comment]
Impossible to reproduce it in the last `main` build.
@DafGreco could you please re-check it in the latest version?

**Comment by DafGreco** [comment]
Not able to reproduce it anymore on the latest build 0.25.23 
Attaching evidence and closing the issue :

https://github.com/user-attachments/assets/001a6a35-7955-47d5-b07d-83b24abc01ac
