### ISSUE TITLE
Onboarding Scene - Modal and Barrier Issues After First Chat with Tobor

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2012]
### **Explorer Alpha build versions:**

- **v0.25.21**

### **Issue Description:**
After completing the first conversation with Tobor (NPC), a modal with the instructions 'Space - Jump' should appear. Tobor continues moving while the first barrier lowers. However, the modal does not appear, and the barrier remains in place until the player jumps, which then causes the barrier to disappear.

### **STR:** 

1. Launch the explorer.
2. Go to **/world cryptonico.dcl.eth**
3. Start the tutorial scene and engage in the first conversation with Tobor (NPC).
4. After the conversation ends, observe that the 'Space - Jump' modal doesn't appear and the barrier doesn't lower.
5. Jump over the barrier to see it disappear.

### **Expected behavior:**
- The 'Space - Jump' modal should appear immediately after the conversation with Tobor.
- The barrier should lower as Tobor continues his path.

https://github.com/user-attachments/assets/4bbb5015-5fcb-43ba-8bf1-86eeeb5683c7

### **Current behavior:**
- The 'Space - Jump' modal does not appear.
- The barrier remains until the player jumps over it.

https://github.com/user-attachments/assets/d74d49b2-cab8-436f-90e0-fa934350116e

### 📂 Scene Repository
https://github.com/agustincarriso/dcl-sdk7-onboarding

**Comment by sandrade-dcl** [comment]
This is not an issue in the Explorer Alpha. After comparing the different versions of the onboarding scenes, I found differences on this part of the flow between them:
- `dclonboarding.dcl.eth` (current production onboarding SDK6 scene): The behavior is exactly what Ludmi show in the video, the barrier disappear and the "space jump" UI appears right after the conversation with Tobor.
- `onboardingdcl.dcl.eth` (onboarding SDK7 scene curently used in Explorer Alpha): The behavior here is a bit different, the barrier doesn't disappear and the "space jump" UI doean't appear until Tobor doesn't move to its new position.
- `cryptonico-dcl.eth` (onboarding SDK7 scene that is exactly the same as `onboardingdcl.dcl.eth` but deployed in another into another name for testing purposes): Here the behavior is the same as in `onboardingdcl.dcl.eth`.

**Summarizing**: It seems the flow implemented in both scenes (SDK 6 and SDK7) is different in this part of the gamplay. The developers of the new SDK7 onboarding scene should make it behaves in the same way as the old SDK6 one.
