### ISSUE TITLE
Onboarding Scene - Bridge/barrier Issues 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2013]
### **Explorer Alpha build versions:**

- **v0.25.21**

### **Issue Description:**
In the tutorial scene, all bridges are supposed to open fully to allow progression. However, they briefly open and then close immediately. This issue prevents proper navigation through the tutorial.

### **STR:** 

1. Launch the explorer.
2. Go to **/world cryptonico.dcl.eth**.
3. Complete the second conversation with Tobor.
4. Observe the bridge that should open to proceed to the mission with Bezier.

### **Expected behavior:**
- All bridges should fully open and remain open to allow seamless navigation through the tutorial.

![image](https://github.com/user-attachments/assets/1c51974b-ec9f-4efc-ac3b-8db8acc06205)

https://github.com/user-attachments/assets/3ad9a9a1-3104-4157-b24f-245a59006e91

### **Current behavior:**
- All bridges in the tutorial scene do not fully open; they open briefly and then close immediately.

https://github.com/user-attachments/assets/bc1abf14-b9ee-4e5b-99c4-20fb2c22689b

https://github.com/user-attachments/assets/1a3e9cdb-c86f-43be-adcb-8780cb7a8da6

### 📂 Scene Repository
https://github.com/agustincarriso/dcl-sdk7-onboarding

**Comment by m3taphysics** [comment]
@popuz its worth asking @lorux0 to see if its an animation issue as he has done a lot of work with scenes & animations.

**Comment by popuz** [comment]
sure. Current state that it is not blocking, but still with animation issues presented (half-closed)
Image](https://github.com/user-attachments/assets/e5fd4761-192f-4fa3-afb0-23411924e597)

**Comment by popuz** [comment]
@m3taphysics , problem is in the sdk code itself. `Weight `of the bridge animation is `0.5` while it should be `1`. When I force `weight `to always be `1`, it works without the issue. This either an oversight or a misunderstanding of `weight `parameter from the creator. Can you re-direct it to the creators?

![Image](https://github.com/user-attachments/assets/37e8fb80-ec95-47a3-bd14-5c3e329546c1)

**Comment by DafGreco** [comment]
Fix deployed on `onboardingdcl` 
Fix verified on onboardingdcl ✔️ 


https://github.com/user-attachments/assets/74692f17-d711-40f6-9a85-f0d4ebe90c7e
