### ISSUE TITLE
Onboarding Scene - Several modals display issues after Bezier mission completition

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2014]
### **Explorer Alpha build versions:**
- **v0.25.21**

### **Issue Description:**
Upon completing the Bezier mission in the tutorial scene, the following issues occur:

1. The "Congratulations! You got a new emote" modal is not properly aligned. The text and thumbnail of the emote are oriented towards the top and should be more centered.
2. After completing the captcha and clicking the submit button, an empty modal appears. The emote is then displayed without a frame and only shows the shortcuts F and E. The action is not displayed, and the emote is not highlighted.
3. Pressing 'E' causes several overlapping issues:
   - A notification pops up at the top with an empty thumbnail.
   - In the center, the emote image appears, but the icon in the upper-left corner shows a white box.
   
### **STR:** 

1. Launch the explorer.
2. Navigate to the world: `/world cryptonico.dcl.eth`.
3. Complete the mission with Bezier.
4. Observe the "Congratulations! You got a new emote" modal for alignment issues.
5. Complete the captcha and click the submit button.
6. Note the empty modal and the display issues with the emote.
7. Press 'E' and observe the overlapping notification and emote display issues.

### **Expected behavior:**
- The "Congratulations!" modal should be properly centered.
- After captcha completion, the modal should be removed, leaving only the notification for the emote reward with correct effects.
- The emote icon should be properly displayed without any overlapping issues, and the notification should show correctly.

**PROD COMPARISON**

https://github.com/user-attachments/assets/f5c056cb-429a-4e05-a9d2-39c7f1606832

### **Current behavior:**

https://github.com/user-attachments/assets/02372303-9636-4e17-9b99-6c71107204d0

![notificacion emergente](https://github.com/user-attachments/assets/4e8c02bd-c190-4f60-bcaa-c16e1167056e)
![icono emote](https://github.com/user-attachments/assets/f1a73cb5-8b4b-4903-b584-900f0af6b34b)
![claim emote](https://github.com/user-attachments/assets/d8117b57-b948-49b8-a831-4ed7a0f71a31)

### 📂 Scene Repository
https://github.com/agustincarriso/dcl-sdk7-onboarding

**Comment by sandrade-dcl** [comment]
@popuz FYI: I already started this [PR](https://github.com/decentraland/unity-explorer/pull/2034) with some fixes related to the Reward Panel. It's still pending to fix the conversation modals (as far as I was able to investigate, the problem seems to be in how the UITransforms are being sorted, but maybe there are also problems in how they are being released). Maybe we will need help from Misha since he was refactoring a lot this part.
