### ISSUE TITLE
[QA] Player gets stuck after jumping in Tower of Hanoi (61,-22)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2022]
### **Explorer Alpha build versions:**

- **v0.25.25**

### **Issue Description:**
In the Tower of Hanoi scene (61,-22), a player can get stuck by jumping towards the back panel of the game area.

### **STR:** 

1. Launch the explorer and teleport to Tower of Hanoi (61,-22).
2. Click Play to begin the game.
3. Jump towards the back panel.

### ❌ Actual Result

- The player gets stuck after jumping towards the back panel and can only escape by moving left.

https://github.com/user-attachments/assets/9a94409e-88b8-45d4-9319-b6f0c59e50eb

### ✅ Expected Result

- The player should not get stuck after jumping in the game area and should be able to move freely.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by anicalbano** [comment]
🟢 Fixed on current build v0.28.0
