### ISSUE TITLE
Onboarding Scene - Portal animation issue in the last Tobor mission

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2037]
### **Explorer Alpha build versions:**
-*v0.25.25*

### **Issue Description:**
In the final mission of the onboarding scene with Tobor, after talking to him, the portals should activate for jumping. The animation of the portals briefly shows them opening but then they turn gray as if they're deactivated. However, if the player approaches, the tooltip appears and clicking opens the modal correctly.

### **STR:** 

1. Launch the explorer.
2. Enter the onboarding scene `/world cryptonico.dcl.eth`.
3. Proceed to the final mission with Tobor.
4. Talk to Tobor and observe the portals after the conversation.

### **Expected behavior:**

https://github.com/user-attachments/assets/3875c067-6b0d-4717-b26a-f74e1b1cac38

- The portal should remain visibly open after the animation instead of turning gray, indicating it is active and ready for interaction.

### **Current behavior:**

https://github.com/user-attachments/assets/5089421c-16f3-4b74-b5cd-90cfe2012769

- The portal animation shows briefly that the portals open, but they turn gray afterward, giving the impression they are deactivated.
- Despite appearing closed, interacting with the portal still opens the modal correctly.

### 📂 Scene Repository
https://github.com/agustincarriso/dcl-sdk7-onboarding

**Comment by DafGreco** [comment]
Portals can be visible now. Closing ticket with evidence 

https://github.com/user-attachments/assets/2d4efadd-5c39-427e-97c5-7ff5c52241ff
