### ISSUE TITLE
On boarding scene - There's no instruction on how to use the keyboard keys 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2039]
### **Explorer Alpha build versions:**
v0.25.26

### **Issue Description:**
During the On boarding , there's an instruction on how to use the keyboard to talk to Tobor 

### **STR:** 

  1. Open v0.25.26 
  2. Once you are in genesis plaza type : /goto cryptonico.dcl.eth in the chat 
  3. Once you are in the on boarding validate that you are not able to see the keyboard instructions at the beginning of the First time user experience.

### **Expected behaviour:**
A keyboard and a mouse should display on the beginning of the FTUE (on boarding)

### **Current behaviour:**
There's no instructions of how to talk to tobor at the beginning 

#### **Evidence:**

https://github.com/user-attachments/assets/793eda30-c931-4ab8-a193-df20c0ff7d6f
What is missing on the FTUE : 
![image](https://github.com/user-attachments/assets/908e8258-74b1-405b-9cdc-d2bb1b673ef9)

#### **Additional Notes:**
Windows 11 pro 
16 GB RAM 

📂 Scene Repository
https://github.com/agustincarriso/dcl-sdk7-onboarding

**Comment by sandrade-dcl** [comment]
@DafGreco the "HowTo" UI is currently appearing correctly 👍 Could you please re-check?

**Comment by DafGreco** [comment]
We were able to confirm that the Howto UI is currently displaying on the screen before the On boarding appears. Closing with evidence : 

https://github.com/user-attachments/assets/fed3826d-abad-46d4-a2d6-4e19148da84e
