### ISSUE TITLE
[QA] Metadynelabs - First-Person Mode Not Enforced and Toggle Allowed

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2046]
### **Explorer Alpha build versions:**

- **v0.26.2**

### **Issue Description:**
In the Metadynelabs world, players spawn in third-person mode instead of first-person, which should be the default. Additionally, players can switch between first and third-person views during gameplay, but it should remain locked in first-person throughout the experience.

### **STR:** 

1. Launch the explorer.
2. Enter the world `/world Metadynelabs`.
3. Check the camera view upon entry.
4. Try switching between first and third-person during gameplay.

### **Expected behavior:**

https://github.com/user-attachments/assets/b2c5a4c5-c019-4ee2-a135-70c2a798f8b4

### **Current behavior:**

https://github.com/user-attachments/assets/3989a923-ef7d-4bc4-8b3e-70c555c9e580

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by popuz** [comment]
hi @Ludmilafantaniella. I tried from Editor and build, but it works fine for me. Maybe there are some specific steps (for example, related to your progress)? Can you try from the account with zero progress on the game?
