### ISSUE TITLE
[QA] App crashes in different instances during the On boarding 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2049]
### **Explorer Alpha build versions:**
0.27.0

### **Issue Description:**
App crashes on different instances of the game during the On boarding 

### **STR:** 

Instance 1: I went to /cryptonico world and it crashed on the 2nd station
Instance 2 : I went to /cryptonico world and it crashed on the 3rd station
Instance 3: I tried for a third time and it crashed In genesis plaza (like a minute after landing there)

### **Expected behaviour:**
App should not crash in different instances of the game during the On boarding  

### **Current behaviour:**
App is crashing in different instances of the game during the On boarding 

#### **Evidence:**
[Player (1) - copia.log](https://github.com/user-attachments/files/16991425/Player.1.-.copia.log)
[Player-prev.log](https://github.com/user-attachments/files/16991426/Player-prev.log)

#### **Additional notes :**
Windows 11 PRO

**Comment by sandrade-dcl** [comment]
I was not still able to reproduce it at the moment (using `v0.27.11-alpha-main`)
