### ISSUE TITLE
[QA] No Reward Given After Completing Mini-Games in 100Avatars Garden

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2056]
### **Explorer Alpha build versions:**

- **v0.27.0**

### **Issue Description:**
In the 100Avatars Garden scene, completing the mini-games does not grant the expected reward. Tested with two different accounts on two different games (Hammercide and Sticky Business).

### **STR:** 

1. Launch the Explorer.
2. `/goto -55,-121` (100Avatars Garden scene).
3. Complete the available mini-game (Hammercide or Sticky Business).
4. Check for the reward.

### **Expected behavior:**
- Players should receive the reward upon completion of the mini-game.

https://github.com/user-attachments/assets/83d84b3e-19b3-401a-9f52-61d20663add7

### **Current behavior:**
- No reward is given after completing the mini-game.

https://github.com/user-attachments/assets/f92a826e-eb10-47ac-9456-edf524c00aa9

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
100 Avatars appears to no longer be working.
