### ISSUE TITLE
[QA] On "Crowd" section of the carrousel the boards go outside bounds

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2083]
### **Explorer Alpha build versions:**
**v0.27.11**

### **Issue Description:**

On Genesis Plaza, the section **Crowd** of the carrousel is showing the boards outside bounds when passing through them from left to right.

### **STR:** 

  1. Go to Crowd section of the carrousel on Genesis Plaza
  2. Start pressing E or move from left to right with the arrows
  3. Observe

### **Expected behaviour:**
The boards should hide when passing through them

### **Current behaviour:**
The boards are still visible

#### **Evidence:**

![image](https://github.com/user-attachments/assets/adaedb47-881d-4744-a9b3-01b8f1dbcc3f)

**Comment by m3taphysics** [comment]
@anicalbano does this happen on unity-renderer?

**Comment by anicalbano** [comment]
@m3taphysics only on Alpha, but it's quiet hard to reproduce
