### ISSUE TITLE
[QA] SDK Camera Control + Avatar Mod Area issue on Mac

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2094]
### **Explorer Alpha build versions:**

- **v0.28.0**

### **Issue Description:**
Camera controls in the SDK aren't working right on Mac. Issues with switching virtual cameras and using the Avatar Modifier and Camera Mode Areas are messing up the camera system and affecting testing.

### **LOGS:**
[Player.log.zip](https://github.com/user-attachments/files/17046372/Player.log.zip)

### **STR:** 

1. /goto pravus world.
2. Press 'E' to cycle between the scene virtual cameras.
3. Enter the Avatar Modifier Area and exit it while in third-person camera mode. Verify that the Avatar is hidden only when inside the area.
4. Being in third-person camera mode, enter the Camera Mode Area and confirm that the camera is forcefully changed to first-person camera. Check that you cannot change the camera mode within that area and that it resets when exiting.

### **Expected behavior:**
- Pressing 'E' should successfully cycle between virtual cameras.
- The Avatar should be hidden only when inside the Avatar Modifier Area.
- The camera mode should forcefully switch to first-person in the Camera Mode Area and reset when exiting. Changing the camera mode should be restricted within the area.

### **Current behavior:**
- Pressing 'E' does not cycle through virtual cameras.
- The Avatar is not hidden when exiting the Avatar Modifier Area.
- The camera mode does not consistently switch to first-person in the Camera Mode Area; it may work intermittently.

https://github.com/user-attachments/assets/287da849-ec20-444d-91c5-f57c97d8816b

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5
Technical Details of My Mac:
	•	Model: MacBook Pro
	•	Chip: Apple M1 Pro
	•	Memory: 16GB
	•	Display: 16-inch (3456 × 2234)
	•	Storage: 335.12 GB available of 494.38 GB

**Comment by pravusjif** [comment]
The strange behaviour here is that more than 1 (AvatarModifierArea besides the MainCamera/VirtualCamera) Explorer Alpha systems on the scene are like waiting a long time before starting to work...

I just tried again and here you can see that after 25~ seconds the scene systems start working and the Avatar Modifier Area starts working:

https://github.com/user-attachments/assets/9eaa27c9-8127-47ae-ab4f-7deb8ac2fc8b

**Comment by davidejensen** [comment]
Not happening to me, asked for a re-test to QA

**Comment by anicalbano** [comment]
🍏 Re tested! It's working as expected now 😄 

https://drive.google.com/file/d/1U2PGO_5ERQCrPxfb9I7USp497vDU_9qu/view?usp=drive_link
