### ISSUE TITLE
[QA] Sound and effects stop working on Dollhouse when using /reload

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2104]
### **Explorer Alpha build versions:**
v0.28.0

### **Issue Description:**

When in Dollhouse scene (-102,-97) with more than 3 players, if the command `/reload` is used , the sound stops working and the particles of the rooftop dance floor disappear. The auto-dance of the emotes keeps playing.

### **STR:** 

  1. Go to Dollhouse with more players
  2. Type the command /reload after a few minutes

### **Expected behavior:**
The scene reloads as expected and everything must be working as usual

### **Current behaviour:**
Functionalities of the scene stop working

**Comment by 102898Is** [comment]
try this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by anicalbano** [comment]
- Could not reproduce on current main (ahead of v0.28.0).
- Re-tested with 4 users, one in Mac
