### ISSUE TITLE
[QA] Missing Asset for Wearables Notification During Onboarding

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2107]
### **Explorer Alpha build versions:**

- **v0.28.0**

### **Issue Description:**
The notifications for wearables received during the onboarding process are missing the ribbon asset in the lower-right corner, displaying a blank white square instead. 

### **STR:** 

1. Launch the explorer.
2. `/goto cryptonico` onboarding scene
3. Complete all onboarding missions to receive the reward.
4. Once in Genesis Plaza, wait for the reward notifications to appear.
5. Click on the bell icon in the left-side sidebar.
6. Observe if the received rewards show a white square instead of the corresponding ribbon asset.

### **Expected behavior:**
The notifications for the received rewards should display the appropriate reward ribbon icon in the lower-right corner.

![expectednotifi](https://github.com/user-attachments/assets/0c6f108d-1a3f-4b4a-9f54-9f6335fdeff8)

### **Current behavior:**
The notifications for the received rewards display a blank white square in the lower-right corner instead of the correct reward ribbon icon.

![capture_240919_100605](https://github.com/user-attachments/assets/32adcd84-264e-4d0e-b37d-5bb12e575c2c)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by sandrade-dcl** [comment]
Fixed in https://github.com/decentraland/unity-explorer/issues/2152

**Comment by DafGreco** [comment]
Fix verified 🟢 
Sanity Check performed :
- Emotes 
- Backpack
- Worlds 
- Teleport 
-On boarding
- scenes
