### ISSUE TITLE
[QA] Metadynelabs: Avatar Stuck After Account Switch

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2125]
### **Explorer Alpha build versions:**

- **v0.28.x**

### **Issue Description:**
an issue was encountered when switching accounts to access level 02 due to the levels carousel not functioning. Upon logging in with a different account, the avatar became stuck, displaying only the head. This problem occurs specifically after switching accounts, but it can be resolved by traveling to another location and then returning.

💡 Suggestion: I believe the issue stems from accounts having different progress in Metadynelabs. To resolve this, why not ensure that when a user logs out from a world and then logs in with a different account, they start in Genesis Plaza instead of returning to the world?

### **STR:** 

1. /goto metadynelabs
2. Log out of the current account.
3. Log in with a different account.
4. Observe the avatar upon logging in.

### **Expected behavior:**
The avatar should be fully visible and functional after switching accounts.

### **Current behavior:**

https://github.com/user-attachments/assets/645a1f9c-7939-41ef-ac9a-92bae61f10f3

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
I like the suggestion, but lets verify
