### ISSUE TITLE
Rollback on realm fail

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-explorer#2127]
We dont have any kind on fallback mechanisma in case any of the steps fails for realm change (on `IRealmNavigator`). Right now, if it does, the realm could be in a ver inconsistent state

We should think of the architecture needed to rollback back to the safe latest stage

**Comment by m3taphysics** [comment]
We should chat with @dalkia and @mikhail-dcl regarding solutions and also please expand on the problems this causes with @dalkia
