### ISSUE TITLE
Timeout livekit issues

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-explorer#2128]
(Currently tested only in mac)

Right now, when doing a realm change, its very easy to fall into a livekit timeout issue; either on the disconnect or reconnect step. Its easily reproduceable in build, after the third or fourth teleport livekit remains in a possible "Stopping" or "Starting" infinite state.

This was mitigated by adding a timeout in [StopRoomAsyncTeleportOperation](https://github.com/decentraland/unity-explorer/blob/main/Explorer/Assets/Scripts/Global/Dynamic/TeleportOperations/StopRoomAsyncTeleportOperation.cs) and [RestartRoomAsyncTeleportOperation](https://github.com/decentraland/unity-explorer/blob/main/Explorer/Assets/Scripts/Global/Dynamic/TeleportOperations/RestartRoomAsyncTeleportOperation.cs).

We should find a way to recover if this occurs

**Comment by NickKhalow** [comment]
Unable to repro again with @dalkia, the ticket is considered as closed
