### ISSUE TITLE
Unable to recover initial memory state in GP

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-explorer#2129]
(Tested in Mac)

Do the following steps

1. Start out in Genesis Plaza and check out the memory.
2. Teleport away to any given scene, and see the memory increase.
3. Go back to GP and press the FULL button in the Memory debug window.

Memory should be about the same, but there is a clear difference. We have to find out why since this indicates there is a leak

Example in MAC

Initial state
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/20984e0d-5f1a-422a-b6f0-664b1363d0e6">

Teleport to scene `-145,69`
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8d6b7e41-a270-4783-8232-f33aa9460a80">

Went back to GP and pressed FULL
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/719f3976-86c0-4cde-92d5-28fd61c5d529">

Memory is now at around `8100MB` vs `7700MB` from start. There are an extra 400MB that shouldnt be there

**Comment by QThund** [comment]
It seems that it does not happen when teleporting between worlds (I mean, when not visiting Genesis).

**Comment by QThund** [comment]
Detected memory leaks, textures related to NFTs are not referenced by any object. Steps to reproduce:

1. Enter Genesis.
2. Go to Olavra.
3. Go to Genesis.
4. Go to Olavra. Take first snapshot with Memory Profiler.
5. Go to Genesis.
6. Go to Olavra. Take second snapshot.
7. Compare both snapshots in Memory profiler.
However, it does not happen always, sometimes textures are referenced by some objects.

![Image](https://github.com/user-attachments/assets/d7dd7075-f4a3-413f-9ce6-72bc02ebce84)

**Comment by QThund** [comment]
After Misha's changes (currently in a branch) that situation should be solved.

**Comment by QThund** [comment]
Maybe a decision has to be made regarding whether those images should stay in memory when moving to another world or not.

**Comment by QThund** [comment]
These accumulation of images related to NFTs were detected in Misha's branch. He has already fixed it.
![Image](https://github.com/user-attachments/assets/e19e8fc2-a06b-47f9-a630-2752058b15db)

**Comment by QThund** [comment]
This duplication of textures has been detected, although the number does not grow when moving to other worlds.
![Image](https://github.com/user-attachments/assets/cdcff432-b7e6-4a70-99d5-73ecd69215fb)
