### ISSUE TITLE
[QA] Assets Broken During Onboarding with High User Load

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2140]
### **Explorer Alpha build versions:**

- **v0.29.0**

### **Issue Description:**
When multiple users access the onboarding simultaneously, certain assets break, such as the keyboard instructions displaying as a giant white square. Additionally, the "Getting Started" modal is missing elements like the close button, and the "Space" key prompt is absent in the first mission modal for Tobor.

### **LOGS**
[onboarding.zip](https://github.com/user-attachments/files/17098859/onboarding.zip)

### **STR:** 

1. Launch the explorer.
2. Go to the onboarding world via `/goto onboardingdcl`.
3. Trigger a high number of users accessing the onboarding at the same time.
4. Observe the following:
   - Keyboard instructions display as a giant white square.
   - The "Getting Started" modal is missing elements (e.g., close button).
   - The first mission modal for Tobor is missing the "Space" key prompt.
   - Check the rest of the onboarding modals.

### **Expected behavior:**
- The keyboard instructions should display correctly without visual glitches.
- The "Getting Started" modal should have all elements, including the close button.
- The "Space" key prompt should appear in the Tobor mission modal.

### **Current behavior:**
![Screenshot 2024-09-23 at 3 37 46 PM](https://github.com/user-attachments/assets/d6d19b0a-8877-42d2-a546-a15dcd2360c4)
![capture_240923_111248](https://github.com/user-attachments/assets/236567f6-0000-4c13-8e51-31a40b5e9cb1)

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5

![image](https://github.com/user-attachments/assets/051fc12a-06f5-41c2-bc5c-d09b8edffd37)

**Comment by m3taphysics** [comment]
Could not reproduce in test @Ludmilafantaniella
