### ISSUE TITLE
 [QA] Walkabout Wanderer Badge Not Tracking Progress

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2172]
### **Explorer Alpha build versions:**

- **v0.29.0**

### **Issue Description:**
The Walkabout Wanderer badge is not tracking progress as expected. This badge should track the number of steps walked, with the first badge being awarded at 10,000 steps. However, despite walking extensively through Genesis Plaza, the progress remains at zero.

### **STR:** 

1. Launch the explorer.
2. Walk through the streets of Genesis Plaza for at least 2min.
3. Monitor the progress towards the Walkabout Wanderer badge.

### **Expected behavior:**
The Walkabout Wanderer badge should track steps walked.

### **Current behavior:**
The Walkabout Wanderer badge does not track steps walked.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by Kaze-No-Kai** [comment]
Moves Master badge also does not track progress on Mac, ver 0.32
