### ISSUE TITLE
[QA] Feet are still visible when using the skeleton wearable

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2180]
### **Explorer Alpha build versions:**
0.29.0

### **Issue Description:**
When using the lower body skeleton wearable you are still able to see the feet when it should 

```
Wearable Link: https://nft-api.decentraland.org/v1/items?contractAddress=0xee77b0a104cd6db1bbbcfa2f13076f234647c017&itemId=2
Wearable URN: urn:decentraland:matic:collections-v2:0xee77b0a104cd6db1bbbcfa2f13076f234647c017:2
```

### **STR:** 

  1. Open 0.29.0
  2. Use the skeleton wearable in you lower body part 
  3. Validate that the feet can still be visible 

### **Expected behavior:**
No feet should be visible when using the skeleton wearable

### **Current behavior:**
When using the lower body skeleton wearable you are still able to see the feet when it should 

#### **Evidence:**
![image (3)](https://github.com/user-attachments/assets/07f745f4-ca5e-4f41-a576-ac909c801b56)

#### **Additional Notes:**
Happens on Mac and Windows

**Comment by sandrade-dcl** [comment]
I've been able to hardcode the wearable `urn:decentraland:matic:collections-v2:0xee77b0a104cd6db1bbbcfa2f13076f234647c017:2` into my current assigned wearables and the issue doesn't reproduce:

![Image](https://github.com/user-attachments/assets/fa7bd5c9-5a58-4431-b1b5-254d6aec05ce)

**Comment by sandrade-dcl** [comment]
I've been able to buy this wearable in Sepolia so now I have it into my Backpack. I have run the app in Sepolia environment and the issue doesn't happen.

![Image](https://github.com/user-attachments/assets/6676a917-c06b-462a-be5b-a31aed53e177)
