### ISSUE TITLE
Add mouse sensitivity sliders

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#2196]
Different input devices like mouse, trackpads or ball mouse have different DPIs, that may also be affected by the operative system (windows / mac). As we cant default it to each one, lets throw a couple of sliders for people to customize it:

In settings, under a new "Controls" section, add 2 sliders:
- Vertical mouse sensitivity
- Horizontal mouse sensitivity

This values will range from 0.1 to 2, being defaulted on 1. 

This is an additive value on top of the default sensitivity value.

**Comment by m3taphysics** [comment]
Adding this as high as it ruins the experience on som devices.
