### ISSUE TITLE
[QA] Minigames - Lighting Emission Appears Too Strong

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2216]
### **Explorer Alpha build versions:**

- **v0.30.0**

### **Issue Description:**
The lighting emission in Tower of Hanoi appear excessively strong, making it difficult to view certain areas clearly.

### **STR:** 

1. Launch the explorer.
2. Go to Tower of Hanoi (61,-22) with strong lighting (specify location if needed).
3. Observe the lighting emission and its effect on visibility.

### ❌ Actual Result
The lighting emission is too strong, overwhelming the scene.

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/7cc3bad0-1f3b-490d-bb85-61c608f2ae3e">

### ✅ Expected Result
The lighting emission should be appropriately balanced to avoid visual discomfort.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
@Ludmilafantaniella can you re-check this?
