### ISSUE TITLE
[QA] Minigames - Multiplayer Queue Overlap in Tetris (-121,-59)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2217]
### **Explorer Alpha build versions:**

- **v0.30.0**

### **Issue Description:**
In the Tetris multiplayer game at (-121,-59), two users can play at the same time, but their game queues overlap, causing one user to see the other’s pieces.

### **STR:** 

1. Launch the explorer.
2. Go to Tetris at (-121,-59) with another player.
3. Start playing simultaneously.
4. Observe if one player sees the other’s pieces.

### ❌ Actual Result
Both users' queues overlap, and one player can see the other's pieces.

### ✅ Expected Result
Each player should see only their own game pieces, with no overlap.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by dzsunyec** [comment]
I placed a virtual camera for the player and teleport the avatar to the side of the screen, so multiple avatars never block the view at least. I'm also now hiding all other avatars around the game screen when you enter a game, so they don't overlap.

This being said, two players should never be able to jump into the same game unless we deploy it in a single-player mode we recently added. This is an ongoing issue with the SyncEntites used for the multiplayer queue, which remains unsolved to this day.
