### ISSUE TITLE
[QA] Minigames - Player's Face Blocks Game View in Word Search, Liquid Labyrinth, and Salad Slash

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2218]
### **Explorer Alpha build versions:**

- **v0.30.0**

### **Issue Description:**
In the Word Search game at (-75,-46), when entering the game while another player is active, the first person sees the face of the other player instead of focusing on the game.

### **STR:** 

1. Launch the explorer.
2. Go to Word Search at (-75,-46).
3. Enter the game while another player is already playing.
4. Observe if the other player's face is visible in first person.
5. Goto Liquid Labyrinth (-139,-28)
6. Repeat step 3 and 4.
7. Goto Salad slash (17,-114)
8. Repeat step 3 and 4

### ❌ Actual Result
The first person sees the other player's face instead of focusing on the game.

### ✅ Expected Result
The game should display only the Word Search interface, not the other player's face.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by ai47patos** [comment]
This issue is related to the multiplayer queue issue that allows multiple players to jump into the play zone, however we are working on avoiding players obstructing the vision of the game regardless the situation, this change is already present in multiple of the games already.
