### ISSUE TITLE
[QA] Minigames - Camera Gets Stuck in Recall Rush if Not in First-Person (36,86)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2219]
### **Explorer Alpha build versions:**

- **v0.30.0**

### **Issue Description:**
In Recall Rush at (36,86), if the player is not in first-person view before entering the game, the camera gets stuck upon entering the game.

### **STR:** 

1. Launch the explorer.
2. Go to Recall Rush at (36,86).
3. Ensure you're not in first-person view.
4. Enter the game and observe the camera behavior.

### ❌ Actual Result
The camera gets stuck if not in first-person view.

https://github.com/user-attachments/assets/a9028538-e563-426d-908a-08e824b93b95

### ✅ Expected Result
The camera should adjust smoothly regardless of the player's perspective when entering the game.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
This doesn't happen on current explorer so its something we should evaluate.

**Comment by popuz** [comment]
Checked - still happening. Should it be even possible to change camera inside these games?

**Comment by Pejosonic** [comment]
Maybe is something related to colliders, getting the camera stuck outside the game area.
I think we can stop forcing first person camera on this game.

**Comment by Pejosonic** [comment]
Depoloyed new version of this game with some changes in colliders. This problem should be fixed.
