### ISSUE TITLE
[QA] Minigames -  Quests in Recall Rush Not Reporting Progress and No Reward Granted (36,86)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2221]
### **Explorer Alpha build versions:**

- **v0.30.0**

### **Issue Description:**
In Recall Rush at (36,86), completing quests does not report any progress, and no rewards are granted to the player upon completion. This prevents players from receiving the expected rewards after finishing the quests.

### **STR:** 

1. Launch the explorer.
2. Go to Recall Rush at (36,86).
3. Complete the assigned quests.
4. Observe if progress is reported and if rewards are granted.

### ❌ Actual Result
No progress is reported for completed quests, and no rewards are granted.

https://github.com/user-attachments/assets/82d018e2-28b5-4470-9fe0-e441bd764921

### ✅ Expected Result
Quest progress should be correctly reported, and players should receive the corresponding rewards upon completion.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by DafGreco** [comment]
I was able to reproduce this issue on v.0.33.0 . I was playing and it never gave me the progress. The progress was given to me when I opened and close the app.

![image](https://github.com/user-attachments/assets/abf48872-4a9e-40b0-9618-c26017a0ab89)

**Comment by ai47patos** [comment]
Can confirm this issue, the mission data for Recall Rush is wrong

**Comment by ai47patos** [comment]
Fixed the issue, I just tried and completed the task of reaching 5 steps in Recall Rush
