### ISSUE TITLE
[QA] Minigames - PX UI Breaks on Mac, Displays White Square Asset

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2222]
### **Explorer Alpha build versions:**

- v0.30.0

### **Issue Description:**
On Mac, the entire PX UI occasionally breaks, displaying a white square asset instead of the intended interface elements. This issue occurs after setting a destination to a minigame, exiting the map, re-entering, and teleporting close to the destination.

### **LOGS:**
[Broken UI.zip](https://github.com/user-attachments/files/17167323/Broken.UI.zip)

[Player-prev.log.zip](https://github.com/user-attachments/files/17167349/Player-prev.log.zip)

### **STR:** 

1. Set a destination to a minigame on the map.
2. Exit the map and re-enter it.
3. Click "Exit Set Destination."
4. Teleport close to the minigame.
5. Open the map and select the game again (set destination).
6. Walk towards the minigame.
7. Observe the PX UI before entering the scene and after spending a few minutes in it.

### ❌ Actual Result
The PX UI breaks, displaying a white square asset instead of the proper interface.

<img width="945" alt="UI BROKEN2" src="https://github.com/user-attachments/assets/cf2a2aee-8225-4e82-abe8-28bbcaac8358">
<img width="1029" alt="Screenshot 2024-09-27 at 1 55 16 PM" src="https://github.com/user-attachments/assets/72debcf1-436b-4e78-a60f-36dca061827a">

### ✅ Expected Result
The PX UI should function correctly, displaying the appropriate interface elements without breaking.

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
@fcolarich lets check through the logs on this one - it could be related to "cannot connect to destination host" which is closely related to memory. We may need @davidejensen's help since its Mac Only.

**Comment by davidejensen** [comment]
Will start trying to repro it now :)

**Comment by davidejensen** [comment]
Via unity I managed to repro the issue in main by loading a lot of stuff, once the memory usage goes into yellow the release of resources is removing the images used by the UI, I also tested it on this https://github.com/decentraland/unity-explorer/pull/2182 PR where the issue is actually resolved!
