### ISSUE TITLE
[QA] Windows Links in PRs Not Working

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2223]
### **Explorer Alpha build versions:**

- **v0.30.0**

### **Issue Description:**
The links generated for Windows builds in PRs are not functioning, preventing users from accessing or downloading the necessary files for testing.

### **STR:** 

1. Open any PR that includes a link for a Windows build.
2. Click on the Windows link.
3. Observe whether the link works or leads to the intended download.

### **Current behaviour:**

https://github.com/user-attachments/assets/02a1640a-4b07-4786-9510-6fe77f857e1b

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by aixaCode** [comment]
@Ludmilafantaniella Do you still experience this issue? I was not able to repro
