### ISSUE TITLE
[QA] Unusable 'BUY' Button on Equipped Base Wearables

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2239]
### **Explorer Alpha build versions:**

- **v0.29.0**

### **Issue Description:**
Equipped base wearables in the passport display a 'BUY' button that is grayed out and unresponsive. This button serves no function, suggesting it should be removed from the base wearables section.

### **STR:** 

1. Launch the explorer.
2. Equip base wereables.
3. Open the passport hover over the equipped base wearables.
4. Observe the 'BUY' button and try to interact with it.

### ❌ Actual Result
The 'BUY' button is grayed out and cannot be interacted with, serving no purpose.

https://github.com/user-attachments/assets/a0bb129e-5c8d-48eb-992d-ad3c05729194

### ✅ Expected Result
The 'BUY' button should be removed from equipped base wearables, as it does not fulfill any function.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by sandrade-dcl** [comment]
@Ludmilafantaniella This is the normal behavior and how it was designed from Product. We cannot buy base wearables and for this reason we deactivate the button.
