### ISSUE TITLE
Cap memory usage at 12gb (or 75% of 16gb)

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#2242]
### **Explorer Alpha build versions:**
Our unloading and cache system will grow indefinately until we hit the current specified 75% of the total memory allowance. We should cap this at 12gb and aim to hit a minimum PC spec of 16gb.

By default all machines can be set to 16gb maximum usage, but then this can be adjusted in the menu if you wish to allow faster load times by having more data cached.

- Implement memory cap at 16gb (or 12gb which is 75% of 16gb)
- Add an additional option to select higher usage in the configuration menu.

**Comment by m3taphysics** [comment]
Awaiting @olavra's decision on the adjustable menu item.

**Comment by popuz** [comment]
12 GB could be indeed a good cap, because it seems to be more or less the average peak
![Image](https://github.com/user-attachments/assets/219d773b-1358-4a90-b69c-9ebcdc1a744e)
