### ISSUE TITLE
[QA] Scenes Disappear When Moving Away and Then Approaching

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2262]
### **Explorer Alpha build versions:**

- **v0.29.0**

### **Issue Description:**
Users have reported that some builds in specific scenes, such as Doll House and Word Search, may disappear when moving away from them and then approaching again. This issue appears to resolve only after reloading the client.

### **STR:** 

1. Go to the Doll House scene at coordinates (-102, -97).
2. Move away from the scene.
3. Approach the scene again and observe if it disappears at some point.
4. Repeat steps 1-3 in the Word Search scene at coordinates (-75,-46).

### ❌ Actual Result
The scene may disappear when moving away and then approaching again.

### ✅ Expected Result
The scene should remain visible regardless of the distance from the avatar.

#### **Evidence:**

https://github.com/user-attachments/assets/bd8c8cb1-b90e-4f0d-bae5-3d355c4ae822

https://github.com/user-attachments/assets/3e8c4657-9320-4221-a0ea-adc4d9f4fb24

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by Vitsky4079** [comment]
This issue came back, here are the reports we had last night:

Evidence: 
Uploading decentraland-20241207-01584601_39DOYGIX.mp4…

Logs: 
[Player (3).log](https://github.com/user-attachments/files/18048555/Player.3.log)

**Comment by Vitsky4079** [comment]
Evidence:
https://github.com/user-attachments/assets/8c9e2d16-86ac-4ba7-8a19-b22e4c53486e

Logs:
[main (2).log](https://github.com/user-attachments/files/18048564/main.2.log)
