### ISSUE TITLE
[QA] Visual Distortion in Pictures at Rishi's Palace (22,-75)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2263]
### **Explorer Alpha build versions:**

- **v0.29.0**

### **Issue Description:**
In the SDK7 scene "Rishi's Palace" (22, -75), users have reported a strange wave effect appearing in the images on the side walls when moving the camera or getting closer to the pictures.

### **STR:** 

1. Go to Rishi's Palace at coordinates (22, -75).
2. Approach the images on the side walls.
3. Move the camera and observe if a strange wave effect appears on the images.

### ❌ Actual Result
A wave-like visual distortion appears on the images when the camera is moved or when the avatar gets closer to the pictures.

https://github.com/user-attachments/assets/ff679b63-eb20-4312-8b93-24e2dda32cd1

### ✅ Expected Result
The images should remain stable without any visual distortions, regardless of camera movement or proximity.

https://github.com/user-attachments/assets/eb017867-0ce7-4419-8583-9d6984e518b4

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
Adjusted to high as this is happening in many places

**Comment by QThund** [comment]
https://github.com/user-attachments/assets/238ba3a7-7a85-4a12-98cd-50caf71df597

**Comment by QThund** [comment]
It has to do with the _Parallax parameter of the material.

**Comment by aixaCode** [comment]
It this the same as this one https://github.com/decentraland/unity-explorer/issues/2255?

**Comment by QThund** [comment]
> It this the same as this one [#2255](https://github.com/decentraland/unity-explorer/issues/2255)?

Yes, it is the same issue.
