### ISSUE TITLE
[QA] Scene Rooms Communication: Lack of Reconnection Policy

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/unity-explorer#2266]
### **Issue Description:**
Sometimes you are disconnected from the Scene Room, and there is no reconnection mechanism.(You see the Poor Scene Room connection in the button next to the minimap).
This cause some issues in the multiplayer experience because you see other players playing the game, and you can still play the game because you are alone in the scene and you don't receive any scene messages because you are not connected.

In the DEBUG panel, at the ROOM SCENE level, it saids stopped connection or something like that (sorry i didn't take a photo).

### **STR:** 

  1.
  2.
  3.

### **Expected behaviour:**
You should be reconnected to the scene room, or at least show a message that you are not connected.

**Comment by NickKhalow** [comment]
Could you provide the repro steps?

**Comment by NickKhalow** [comment]
It may be related to the socket issue, put it on hold for a while
