### ISSUE TITLE
[QA] Newly deployed SDK7 scene GLBs are not visible

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2291]
### **Explorer Alpha build versions:**
0.29.0

### **Issue Description:**
Newly deployed SDK7 scene GLBs are not visible

### **STR:** 

  1. Open 0.29.0
  2. Go to casa roustand 
  3. Validate that the scene does not load

### **Expected behavior:**
The scene should load properly when teleporting 

### **Current behavior:**
Newly deployed SDK7 scene GLBs are not visible

#### **Evidence:**

https://github.com/user-attachments/assets/c3b4264a-2bfc-4112-9ce1-5caface48af8

#### **Additional Notes:**
This issue happens on both platforms 

Specifications:
- OS - Windows 11
- Processor - Intel Core i9-14900K
- Graphic Card - NVIDIA GeForce RTX 4070 Ti 12GB
- RAM - 64GB, DDR5, 6400MHz 
- Internet Speed - 5072.36 Mbps

**Comment by davidejensen** [comment]
![Image](https://github.com/user-attachments/assets/5f68a480-ed0a-498c-9f57-858b652a1506)

working fine after latest ab build
