### ISSUE TITLE
Nametags are displayed while the avatar is loading

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#2304]
When the avatar of other players are loading, the nametag is being rendered in the floor (no height on the bounding box).

If give a couple of options:

A) The nametags are hidden until the avatar is fully loaded
B) Render the base mesh of the avatar with a hologram shader while the avatar is loading.

If you, whoever you are, want to approach it on option B, let me know and I will create a simple hologram shader for you.

**Comment by QThund** [comment]
It's very probable this issue was already fixed here @m3taphysics :
https://github.com/decentraland/unity-explorer/pull/2194
