### ISSUE TITLE
[QA] Crashes When Clicking on Profile Badges (Intermittent)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2312]
### **Explorer Alpha build versions:**

- v0.32.0

### **Issue Description:**
A user has reported that clicking on their profile badges consistently causes the application to crash. This issue may be related to a recent change in windowed mode, as the user switched from fullscreen to windowed mode using Alt+Enter before experiencing the crash. Further investigation is needed to determine the underlying cause.

### **STR:** 

1. Launch the explorer.
2. Change to windowed mode using Alt+Enter (optional, based on user behavior).
3. Click the [P] shortcut and select windowed mode.
4. Click on the profile --> Tab badges.
5. Interact with multiple profile badges.
6. Leave the application idle for 1-2 minutes.
7. Click another profile badge.

## ❌ Actual Result
The application crashes intermittently after resuming interaction with the badges following a brief idle period.

### ✅ Expected Result
The application should remain stable, and profile badges should be interactable without causing crashes, even after a brief idle period.

### 📜 Logs
[Player.zip](https://github.com/user-attachments/files/17247767/Player.zip)
[Player.log](https://github.com/user-attachments/files/17247777/Player.log)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by sandrade-dcl** [comment]
Still not able to reproduce it in v0.32.

**Comment by DafGreco** [comment]
I was able to reproduce this issue on latest version. 
I opened a badge notification and click on it a few times and it crashed. 

https://github.com/user-attachments/assets/d5bf76a4-2b24-4707-adc4-5e69b1e066da

Waiting for Macos Confirmation in order to add this as a potential STR
