### ISSUE TITLE
Animation / Character Armature Leak

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#2317]
### **Explorer Alpha build versions:**
![image](https://github.com/user-attachments/assets/f0fce755-547e-4caf-be24-db0914d66679)

### **Issue Description:**
Left the editor overnight and came back to hundreds of the same cloned armature.

![image](https://github.com/user-attachments/assets/cd6a5576-033c-4a5e-b688-902d883e2233)
![image](https://github.com/user-attachments/assets/4c05a20a-72bd-4947-9635-a32263be7446)

### **STR:** 

  1. Leave unity running
  2. Host an event
  3. Wait 24hrs

OR

1. Potentally use @NickKhalow's new bot tool to ensure avatars are being destroyed correctly after flooding with bots.

**Comment by QThund** [comment]
Tried to reproduce the issue using bots, unsuccessfully.

**Comment by m3taphysics** [comment]
Cannot reproduce.
