### ISSUE TITLE
[QA] Olvara.dcl.eth: When running, avatars at times fall through the ground at lower levels

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#232]
### **Explorer Alpha build version:**

0.3.16

### **Issue Description:**

When running, the avatars are at times falling through the ground at lower levels, this appears to be an issue with the new locomotion, foot placement doesn't appear to be functioning. This has been found in the following world: Olvara.dcl.eth

### **Steps to reproduce:**

  1. Go to this world: Olvara.dcl.eth
  2. Try to run as shown on the video
 
### **Expected behaviour:**

When running, the avatars shouldn't fall through the ground at lower levels

### **Current behaviour:**

When running, the avatars are falling through the ground at lower levels

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ x]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ x] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [x ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ x] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**

This issue can be clearly seen [here](https://drive.google.com/file/d/1zWlUvQGipnomKCjWBecza_BcSV07kOXU/view?usp=drive_link)

#### **Additional Notes:**

M1 chipset

**Comment by anicalbano** [comment]
Solved in newest builds
