### ISSUE TITLE
[QA] Stream does not work properly on TheInn

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2333]
### **Explorer Alpha build versions:**
0.32.0

### **Issue Description:**
Can not stream video on screen on client but can stream on browser on screen in SDK7 - The Inn 138,-3 

### **STR:** 

  1. Open 0.32.0
  2. Go to the Inn (138,-3)
  3. Stream a video 
  4. Validate that the stream is not working and shows a white screen instead 

### **Expected behaviour:**
The Inn should be able to stream whenever the client wants to stream a video 

### **Current behavior:**
Can not stream video on screen on client but can stream on browser on screen in SDK7 - The Inn 138,-3 

#### **Evidence:**
![image](https://github.com/user-attachments/assets/f9d113d9-6569-489f-8c9c-035f2be2e630)

#### **Additional Notes:**
Happens on Windows and Mac

**Comment by fcolarich** [comment]
Merged into release branch!
