### ISSUE TITLE
[QA] Users Appear Beyond Map Border When Jumping into the Sea (-155,0)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2339]
### **Explorer Alpha build versions:**

- **v0.32.0**

### **Issue Description:**
When users jump into the sea at coordinates -155,0, they appear beyond the map border instead of remaining within the defined limits of the scene.

### **STR:** 

1. Connect two different accounts to the Launcher (one Mac and the other on Windows).
2. Use the command `/goto -155,0` on one account account.
3. `/goto -152,0` on the second account
4. User from step 2 in the direction of the sea.
5. The second user observes the first avatar's position as it jumps into the sea.

### ❌ Actual Result
The avatar that jumps into the sea appears beyond the map border, as observed by the second user.

![image](https://github.com/user-attachments/assets/c00740cb-6aa8-4408-9730-130b5f9ad85b)

### ✅ Expected Result
The jumping avatar should remain within the map limits and not appear beyond the border, as seen by both users.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by aixaCode** [comment]
This will be fixed by https://github.com/decentraland/unity-explorer/issues/2254 when we release new version

**Comment by m3taphysics** [comment]
Lets recheck this
