### ISSUE TITLE
Memory: Qualify JS Code for unloading

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#2343]
## Existing behavior

- JS code (as a string) takes around 1-5MB for each scene.
- They are cached by scene coordinates in `MemoryJsSourcesCache`
- This cache is never cleaned up, making everything hang in memory for the whole session

## Expected Behavior
- Cache is cleaned when the realm has changed (it's a good moment for cleaning up as much as possible)
- JS Code scene is referenced only when the corresponding scene facade is alive (you can use the generic `StreamableRefCountData` for this)
- Cache is suitable to release unreferenced JS code upon receiving memory pressure via `CacheCleaner`

**Comment by AnsisMalins** [comment]
I went for the dumbest possible solution to ensure I can get it in before Friday. Simply clear out the cache when cache cleaner runs. As far as I've tested it, it works fine, and nothing breaks.

Big picture though, why the heck is JS code strings? Why aren't we passing the raw byte stream straight into the V8 engine and caching the compiled result instead?
