### ISSUE TITLE
[QA] Falling Animation Persists at Genesis City Bar

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2356]
### **Explorer Alpha build versions:**

- **v0.32.0**

### **Issue Description:**
When the avatar descends to the bar using the Genesis City waterfall, the falling animation briefly continues upon reaching the bottom. The animation should stop once the avatar arrives at the bar.

### **STR:** 

1. Launch the explorer and navigate to Genesis City.
2. Guide the avatar to the waterfall and descend to the bar using it.
3. Observe the avatar's behavior as it reaches the bottom.

### ❌ Actual Result
The avatar continues showing the falling animation briefly after reaching the bar.

### ✅ Expected Result
The falling animation should stop immediately when the avatar reaches the bar.

#### **Evidence:**

https://github.com/user-attachments/assets/243e06ae-acf6-4038-81d4-675e3800d429

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by DafGreco** [comment]
This issue is not happening anymore on latest dev.
**Evidence :**

https://github.com/user-attachments/assets/490e908e-cf56-4cab-967e-0bf9135c9be6
