### ISSUE TITLE
[QA] Minigames - Tower of Hanoi Queue System Breaks 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2376]
### **Explorer Alpha build versions:**

- **v0.33.0**

### **Issue Description:**
In the Tower of Hanoi scene (61,-22), the queue system breaks easily, causing players to be kicked out randomly when entering the scene.

### LOGS:

[Player-prev (2).zip](https://github.com/user-attachments/files/17310364/Player-prev.2.zip)
[Player-prev.zip](https://github.com/user-attachments/files/17310367/Player-prev.zip)

### **STR:** 

1. Launch the explorer and `/goto 61,-22`
2. Have players stand outside the Tower of Hanoi scene.
3. Have them run in one by one, pressing the queue button.

### ❌ Actual Result
Players get kicked out randomly when entering the scene and pressing the queue button.

https://github.com/user-attachments/assets/470b1dc3-62b1-46ce-b0c6-2f05cfebbbb7

### ✅ Expected Result
Players should be able to join the queue without being kicked out randomly.

📝 Issue found during 10/09 team testing session

**Comment by ai47patos** [comment]
Similar issue to https://github.com/decentraland/unity-explorer/issues/2378
Should have been fixed with the new queue update
