### ISSUE TITLE
[QA] Minigame - Peer Can Desync and Join the Game Twice

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2378]
### **Explorer Alpha build versions:**

- v0.33.0

### **Issue Description:**
A peer can enter another player's game while it is in progress. This issue occurs when a user teleports quickly and clicks "Play" before the Room SID loads.

**Preconditions:** Have the debug menu open.

1. Go to the Tower of Hanoi scene (61,-22).
2. User A enters the game.
3. User B teleports to Alavara.
4. User B teleports to (60,-22) and runs quickly to the minigame.
5. User B clicks "Play" before the Room SID in the debug menu loads.

### ❌ Actual Result
User B can join the game in progress with User A and potentially desync by entering the game twice.

https://github.com/user-attachments/assets/e95f4fa5-087d-46ad-9239-c7b2712464d3

### ✅ Expected Result
User B should not be able to join User A's game while it is in progress.

### 📜 Logs
[Player.zip](https://github.com/user-attachments/files/17310694/Player.zip)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by ai47patos** [comment]
We added some changes to the minigames library that improves the queue sync propagation, hopefully it can reduce greatly the appearance of this issue.

**Comment by ai47patos** [comment]
There is a new queue system in place that have fixed this issue, I failed to reproduce it with this new system
