### ISSUE TITLE
[QA] Minigame - Colliders Missing in Various Games Allow Players to Exit Play Area

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2381]
### **Explorer Alpha build versions:**

- **v0.33.0**

### **Issue Description:**
In the following games, players can exit the play area while playing due to missing colliders on the sides (or front in Math Kittens). 

- Recall Rush (36,86)
- Tower of Hanoi (61,-22)
- Math Kittens (-85,-97)

1. Launch the game.
2. Move towards the edges of the play area (sides or front).
3. Exit the play area.

### ❌ Actual Result
Players can exit the area during gameplay due to missing colliders.

https://github.com/user-attachments/assets/9caf3928-231f-4620-b474-1c1f683247e7

https://github.com/user-attachments/assets/fd3f0c45-ca3f-44ff-b87c-1917a3268c9c

https://github.com/user-attachments/assets/f32bc0ac-6363-4e65-8260-3954e5ba4fdb

### ✅ Expected Result
Players should not be able to exit the play area at any time during gameplay.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by ai47patos** [comment]
Confirmed this is the expected behavior of this games.
