### ISSUE TITLE
[QA] Memory Limit the game to 4 or 2  

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2408]
### **Explorer Alpha build versions:**
0.34.0

### **Issue Description:**
When the user limits the memory limit to 4 or 2 , the user is not able to teleport anywhere and the loading screen is stuck at 76% 

### **STR:** 

  1. Open 0.34.0
  2. Open the settings 
  3. Tap the memory limit and change it to 4 or 2 
  4. Teleport to another scene 
  5. Validate that the user cannot teleport due to being stuck at 76% 

### **Expected behavior:**
The user should not be stuck on the loading screen or not being able to teleport 

### **Current behavior:**
When the user limits the memory limit to 4 or 2 , the user is not able to teleport anywhere and the loading screen is stuck at 76% 

#### **Evidence:**

https://github.com/user-attachments/assets/fbc592d3-0e93-452a-aa7e-c23bda5f5ef7

#### **Additional Notes:**
Windows 11 pro 
16GB RAM 
-
Macbook pro
Chip m3
Memory: 16GB
Macos : Sonoma v14.5
Display: 14 inch (3024 x1964)
SSD 1TB

**Comment by dalkia** [comment]
https://github.com/decentraland/unity-explorer/pull/2371/files#diff-5116fc119319321b684cdee4c328d1cc121894502bd19cd61ee557787b588db4

Minimum is now 10GB, this issue is not relevant anymore
