### ISSUE TITLE
[QA] Minigames - Salad Slash Lacks Colliders for Active Gameplay

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2413]
### **Explorer Alpha build versions:**

- **v0.34.0**

### **Issue Description:**
The Salad Slash minigame (17,-114) does not have colliders to separate the ongoing game from other users in the queue. This absence leads to interference, as players can pass through the screen and disrupt the active gameplay, unlike the behavior observed in other game challenges.

### **STR:** 

1. Navigate to the Salad Slash minigame at coordinates (17,-114).
2. Start a game session.
3. Observe that other users can move through the gameplay area, causing disruptions.

### ❌ Actual Result
Users in the queue can traverse the active gameplay area, interfering with the current game session.

### ✅ Expected Result
Colliders should be present to prevent users from entering the gameplay area during an active session, ensuring uninterrupted gameplay.

#### **Evidence:**

https://github.com/user-attachments/assets/f6168dc8-025f-4de5-83eb-453e8d6e294d

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by dzsunyec** [comment]
Oh, this probably means that adding the hideAvatarArea after someone walked into that area, might not affect the players already inside :( . Ok I guess I'll have to hide everyone there all the time.
