### ISSUE TITLE
[QA] "Open for Business" Badge Progress Bar Overflow

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2414]
### **Explorer Alpha build versions:**

- **v0.34.0**

### **Issue Description:**
A user reported that the "Open for Business" badge appears maxed out in their passport, with the progress bar filled and exceeding the limits of the badge slot. Pejo confirmed the issue, indicating it is a UI problem. The badge status is accurate on the GET badges endpoint, showing correct completion data.

`{
                "id": "profile_pro",
                "name": "Profile Pro",
                "description": "Added information to Profile",
                "category": "Socializer",
                "isTier": false,
                "completedAt": "1725657465224",
                "assets": {
                    "2d": {
                        "normal": "https://assets-cdn.decentraland.org/profile_pro/2d/normal.png"
                    },
                    "3d": {
                        "normal": "https://assets-cdn.decentraland.org/profile_pro/3d/normal.png",
                        "hrm": "https://assets-cdn.decentraland.org/profile_pro/3d/hrm.png",
                        "basecolor": "https://assets-cdn.decentraland.org/profile_pro/3d/basecolor.png"
                    }
                },
                "progress": {
                    "stepsDone": 1,
                    "nextStepsTarget": null,
                    "totalStepsTarget": 1,
                    "lastCompletedTierAt": null,
                    "lastCompletedTierName": null,
                    "lastCompletedTierImage": null
                }
            }`

### **STR:** 

1. Access the user's passport with wallet ID: 0x29fb0d1b0836f9963f963b0bb07c49d2d61370b4.
2. Locate the "Open for Business" badge.
3. Observe that the progress bar is filled and extends beyond the designated badge slot.

### ❌ Actual Result
The progress bar for the "Open for Business" badge overflows beyond the limits of the badge slot in the user's passport.

![image](https://github.com/user-attachments/assets/88c9dfef-eb23-47b4-b307-fd4277f3561b)

### ✅ Expected Result
The progress bar should accurately reflect the completion status without exceeding the badge slot's limits.

**Comment by lorenzo-ranciaffi** [comment]
![Screenshot 2024-10-14 at 15 16 15](https://github.com/user-attachments/assets/db0837f8-aa88-4602-8763-39162cf136de)
It looks like the information we've got from the backend is faulty.

I think we still could clamp the progress bar size to its maximum value so that it won't be rendered out of bounds @m3taphysics

**Comment by DafGreco** [comment]
This issue has been fixed on PR 2420
![image (2)](https://github.com/user-attachments/assets/74af3cf0-a774-49a1-8fb1-d18ecae3c2ad)
