### ISSUE TITLE
[QA] Avatar won't rotate after teleporting 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2417]
### **Explorer Alpha build versions:**
0.34.17

### **Issue Description:**
After teleporting to a scene and returning to Genesis plaza , the avatar is not able to rotate anymore when opening the backpack

### **STR:** 

  1. Open 0.34.17 
  2. Go to Casa Roustan
  3. Return to Genesis Plaza using the map 
  4. Once you are on Genesis Plaza open the backpack 
  5. Validate that you are not able to rotate the avatar anymore

### **Expected behavior:**
The avatar should rotate after teleporting 

### **Current behavior:**
After teleporting to a scene and returning to Genesis plaza , the avatar is not able to rotate anymore when opening the backpack

#### **Evidence:**

https://github.com/user-attachments/assets/37cd3655-5656-4e1e-8685-1f33515467fd

#### **Additional Notes:**
this issue happens on Mac and Windows

**Comment by fcolarich** [comment]
I have tried to replicate this, as well as a similar issue with the backpack not opening after a teleport, but I could only reproduce it twice and with no clear repro steps... it happens after a teleport, but other than that, I got nothing to go on... 
SO I will leave this in the backburner until we get more specific repro steps.

**Comment by DafGreco** [comment]
I was able to see how the rotation works properly on 0.39.0 on Windows and Macos ! Closing ticket
