### ISSUE TITLE
[QA] Minigames | Red Exclamation Mark Hidden Behind Daily Quest UI

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2421]
### **Explorer Alpha build versions:**

- **v0.34.0**

### **Issue Description:**
The UI for the Daily Quest (shaped like a rocket, located next to the minimap) displays a red exclamation mark, indicating available quests. However, the exclamation mark is partially hidden behind the rocket UI, making it difficult to notice. The exclamation mark should appear in front of the rocket icon for better visibility.

### **STR:** 

1. Launch the Explorer with Daily Quests enabled.
2. Look at the rocket-shaped Daily Quest UI next to the minimap.
3. Observe the red exclamation mark partially hidden behind the rocket UI.
4. Click in the rocket to open the modal.
5. Observe the exclamation mark partially hidden and won't dissapear.

### ❌ Actual Result
The red exclamation mark is hidden behind the rocket-shaped UI.

### ✅ Expected Result
The red exclamation mark should appear in front of the rocket-shaped UI for proper visibility.

#### **Evidence:**

![image (1)](https://github.com/user-attachments/assets/6bb81039-bdc5-4889-978b-0fdeaefc25cc)
![image](https://github.com/user-attachments/assets/601cea6b-8cca-4f98-bd2e-e30f6ecdb460)

**Comment by ai47patos** [comment]
Saw the issue the same day of this post, today with the launch of the 0.35 I can't replicate the issue any more
