### ISSUE TITLE
[QA] Minigames | Daily Quest Completes Math Kittens Mission Early

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2423]
### **Explorer Alpha build versions:**

- **v0.34.0**

### **Issue Description:**
The Daily Quest mission stated "Reach level 6 on Math Kittens." However, upon reaching level 5, the mission was marked as completed, even though one more level was required to properly finish the task.

### **STR:** 

1. Start the "Reach level 6 on Math Kittens" mission in the Daily Quest.
2. Play Math Kittens and progress until reaching level 5.
3. Observe that the quest is marked as completed at level 5 instead of level 6.

### ❌ Actual Result
The mission is marked as completed when reaching level 5.

![image](https://github.com/user-attachments/assets/51648dd7-82fa-44ae-ac24-0a4a207148b1)

https://github.com/user-attachments/assets/ed6950af-10ac-415e-9fb6-6231e02fd4ab

### ✅ Expected Result
The mission should only be marked as completed upon reaching level 6.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by anicalbano** [comment]
Addign comment: same case with lvl 8, the quest ends at lvl 7:
![image](https://github.com/user-attachments/assets/01e9bda0-5aa2-4172-abd2-6753ba321410)

**Comment by ai47patos** [comment]
I have located the issue, I will update it as soon as I can

**Comment by ai47patos** [comment]
It is a visual bug of the game level tracker, a fix is on the way from the dappcraft team
