### ISSUE TITLE
[QA] Minigames | Avatar softlocks after teleporting during minigame

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2427]
### **Explorer Alpha build versions:**

- **v0.34.0**

### **Issue Description:**
While playing any of the listed minigames, teleporting to another location causes the avatar to become unresponsive to directional keys, resulting in a softlock. The only way to resolve this issue is by closing and reopening the Explorer. This issue affects multiple games and occurs consistently when teleporting mid-game.

Affected minigames:
- Recall Rush (36,86)
- Salad Slash (17,-114)
- Tetris (-121,-59)
- Word Search (-75,-46)
- Memory Grid (81,-30)

### **STR:** 

1. Start any of the listed minigames.
2. Play for a few moments.
3. Teleport to any other location.
4. Observe that the avatar is unresponsive to directional keys.

### ❌ Actual Result
The avatar becomes unresponsive after teleporting during a minigame, requiring the user to close and reopen the Explorer to regain control.

### ✅ Expected Result
The avatar should remain responsive after teleporting during a minigame, allowing continued movement without needing to restart the Explorer.

#### **LOGS:**
[Player-prev.zip](https://github.com/user-attachments/files/17366896/Player-prev.zip)

[Player.zip](https://github.com/user-attachments/files/17366897/Player.zip)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by QThund** [comment]
This happens because there is no mechanism to reset the StunComponent of the player's character when it is teleported.

**Comment by pravusjif** [comment]
Probably fixed by https://github.com/decentraland/unity-explorer/pull/2506, should be re-checked.

**Comment by anicalbano** [comment]
It was indeed fixed by #2506 , closing the ticket
