### ISSUE TITLE
[QA] Cannot open user passports, especially from Mac to Windows

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2469]
### **Explorer Alpha build versions:**

- **v0.36.0**

### **Issue Description:**
The passport feature is inconsistent between Mac and Windows. On Mac, user passports sometimes fail to open, while on Windows (tested on v0.36.0 in Genesis Plaza), passports are accessible. After visiting the DollHouse, passports cannot be opened on either platform.

### **STR:** 

1. Test on Mac, attempt to open passports of other users.
2. Test on Windows in Genesis Plaza (v0.36.0), and confirm passports open correctly.
3. Visit DollHouse on both Mac and Windows.
4. Attempt to open user passports again on both platforms.

### ❌ Actual Result
On Mac, user passports sometimes fail to open, especially after visiting DollHouse. Afterward, passports cannot be opened on either platform.

https://github.com/user-attachments/assets/c4ae4e54-7e70-4e7c-b5dc-77080b26b8b3

### ✅ Expected Result
User passports should open consistently across both Mac and Windows platforms, even after visiting different locations like DollHouse.

#### **LOGS:**
[Windows - Player-prev.zip](https://github.com/user-attachments/files/17401514/Player-prev.zip)
[Mac- Player-prev.log.zip](https://github.com/user-attachments/files/17401552/Mac-.Player-prev.log.zip)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by aixaCode** [comment]
Other case of this issue

https://github.com/user-attachments/assets/6ad8aad0-5510-4e54-9e9a-7df863febddb

**Comment by aixaCode** [comment]
Here is the issue
https://github.com/user-attachments/assets/60cf79f2-de6d-4955-a98f-772a64b684bc
