### ISSUE TITLE
[QA] Minigames | Word list not displaying correctly in Word Search (-75,-46)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2472]
### **Explorer Alpha build versions:**

- **v0.35.0**

### **Issue Description:**
When starting the Word Search minigame, the panel sometimes displays a word list that doesn't match the words needed to find in the game. After exiting and restarting the game, the issue resolves with a new, correct word set. The issue has a very low repro rate.

This issue was reported by Romi during the Internal Testing Session

### **STR:** 

1. Go to Word Search at coordinates (-75,-46).
2. Start a game session.
3. Observe the word list displayed in the panel.
4. Exit and restart the game session.

### ❌ Actual Result
The word list initially displayed is incorrect and doesn’t match the game.

### ✅ Expected Result
The word list should always correctly display the words to search for in the game.

**Comment by ai47patos** [comment]
This issue is the same as https://github.com/decentraland/unity-explorer/issues/2473
