### ISSUE TITLE
[QA] Minigames | Incorrect letter assignment in Word Search (-75,-46)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2473]
### **Explorer Alpha build versions:**

- **v0.35.0**

### **Issue Description:**
While playing the Word Search minigame solo, the game started normally, but after finishing all the words, the board shuffled, and not all letters were reassigned correctly. Some words were missing, while close approximations appeared instead. This issue can be reproduced with various word lists.

### **STR:** 

1. Go to Word Search at coordinates (-75,-46).
2. Start a game session and complete all the words.
3. Observe the board after it shuffles.
4. Repeat Step 2 and 3 several times.

### ❌ Actual Result
Some words are missing, and close approximations appear instead.

![word search](https://github.com/user-attachments/assets/181ef4a6-88b6-457a-911f-484c6354cbb9)

### ✅ Expected Result
All words should be present and correctly assigned after the board shuffles.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by ai47patos** [comment]
The lag caused by the letter swapping animation could cause this issue sometimes, fixed it by improving the animation optimization.
