### ISSUE TITLE
[QA] Some scenes do not load after teleporting 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2480]
### **Explorer Alpha build versions:**
0.36.0

### **Issue Description:**
After teleporting to mini-games scenes , the user can find an empty parcel instead of a mini-game 

### **STR:** 

  1. Open 0.36.0
  2. Verify that the missions require you to go to a certain spot 
  3. Teleport to tile tally (for example)  or World search 
  4. Validate that the scene actually never loads 

### **Expected behavior:**
The scene should load properly when teleporting

### **Current behavior:**
Some scenes do not load after teleporting 

#### **Evidence:**
![image (6)](https://github.com/user-attachments/assets/7e224413-e397-43a2-a3e7-88eff1e1f6f7)

https://github.com/user-attachments/assets/bf7b9f1a-7288-46bb-9233-f591fc51b265

[Player.log](https://github.com/user-attachments/files/17413770/Player.log)

#### **Additional Notes:**
This issue can happen on Windows and Macos

**Comment by dalkia** [comment]
Closed, since its repeated and the log doesn't offer useful information
