### ISSUE TITLE
[QA] Click on notification makes the screen blink

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2503]
### **Explorer Alpha build versions:**
Not version specific

### **Issue Description:**

When getting a notification about a wearable/emote recieved, if we click on that notification, instead of opening the backpack or the panel to you the mentioned item, the screen makes a subtle blink and goes back to the main view.

### **STR:** 

  1. Receive someting on the notifications
  2. Click on the reward
  3. Observe the behavior

### **Expected behavior:**
The client shows the panel (backpack)

### **Current behaviour:**
It appears for a second and then disappears

#### **Evidence:**

https://github.com/user-attachments/assets/578ef1ad-0714-4fef-b60d-d3791279d30a

**Comment by DafGreco** [comment]
We were able to see this issue fixed on 0.39.0 
Attaching video as evidence 

https://github.com/user-attachments/assets/8d8a2d0c-a007-4d05-b6e7-e7283bbb9818
