### ISSUE TITLE
[QA] Minigames | User is unable to cut food on Salad Slash 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2509]
### **Explorer Alpha build versions:**
0.37.0

### **Issue Description:**
When loading and playing Salad Slash , user is unable to cut the required food 

### **STR:** 

  1. Open 0.37.0
  2. Go to salad Slash 
  3. Attempt to cut food 
  4. Validate that the user is unable to cut food even with the camera locked 

### **Expected behavior:**
The user should be able to cut the food properly when playing Salad Slash

### **Current behavior:**
When loading and playing Salad Slash , user is unable to cut the required food 

#### **Evidence:**

https://github.com/user-attachments/assets/0ce8d565-15cc-4d1c-ae7c-153eae367edb

#### **Additional Notes:**
This issue happens on Macos and Windows

**Comment by ai47patos** [comment]
Notes about this issue:
Only fails in unfocused mode
Happens also in v0.36 and v0.35

**Comment by dzsunyec** [comment]
Deployed a fix for this successully. (for the third time, since the first two times the change somehow didn't merge into the release branch when doing a PR)
