### ISSUE TITLE
[QA] Empty billboard on GP carrousel

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2516]
### **Explorer Alpha build versions:**
Not version specific

### **Issue Description:**

On GP carrousel, **Best Rated** section, there is a billboard that appears to be empty. When clicking on Jump In button, it takes the user to an empty parcel.

![image](https://github.com/user-attachments/assets/cf258745-13d0-4d14-bedc-85bf39c8c736)

**Comment by DafGreco** [comment]
This issue is no longer happening on 0.46.0
