### ISSUE TITLE
[QA] Backpack | Eye color affects entire eye instead of iris

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2517]
### **Explorer Alpha build versions:**

- **v0.37.0**

### **Issue Description:**
When changing the eye type in the backpack, some eye options incorrectly display the entire white part of the eye or the pupil in the selected iris color. Both the white part and the pupil should remain unaffected by the selected color, only the iris should change color.

### **STR:** 

1. Open the backpack and navigate to the eye customization options.
2. Change between eye types.
3. Observe that, for certain eye types, the white part of the eye or the pupil is also colored with the selected iris color.

### ❌ Actual Result
The white part of the eye and/or the pupil are incorrectly colored along with the iris.

### ✅ Expected Result
Only the iris should change color, while the white part of the eye and the pupil should remain unaffected.

#### **Evidence:**

https://github.com/user-attachments/assets/664bf644-f23b-47bc-b7b3-65232f6a2e0f

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by Vitsky4079** [comment]
Here's another example: https://decentraland.org/marketplace/contracts/0x8243a7c58ea6288fda40203ad75861efbe31041e/items/2
![Uploading image-2.png…]()
