### ISSUE TITLE
[QA] Onboarding | Map UI briefly appears during the onboarding

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2528]
### **Explorer Alpha build versions:**
**release21-10-24 - v38**

### **Issue Description:**
When entering the explorer with a new account and triggering the onboarding, the map UI briefly appears with a white circle, overlapping the screen showing keyboard instructions. The map UI should not be visible during the onboarding process.

### **STR:** 

1. Enter the explorer with a new account.
2. Trigger the FTUE onboarding.
3. Observe the map UI briefly appearing with a white circle during the screen that explains how to control the avatar with the keyboard.

### ❌ Actual Result
The map UI briefly appears, overlapping with the FTUE screen showing keyboard instructions.

### ✅ Expected Result
The map UI should not appear during the FTUE onboarding process.

#### **Evidence:**
![image (1)](https://github.com/user-attachments/assets/19beeddc-c84a-4466-80bc-ffdcb18a0426)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by DafGreco** [comment]
This issue is no longer happening on 0.46.0
