### ISSUE TITLE
[QA] Quest emotes disappeared from the backpack

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2549]
### **Explorer Alpha build versions:**
0.38.0

### **Issue Description:**
When opening the wheel of the emotes , the user is able to see that there are missing emotes from quests. The notification of those emotes is still appearing on the Notification center but they are not currently displaying on the backpack or the wheel

### **STR:** 

  1. Open 0.38.0
  2. Check that you appear on Genesis Plaza 
  3. Open the wheel 
  4. Validate that you have missing emotes on the wheel but you have notifications about them

### **Expected behavior:**
The emotes should not disappear from the backpack after winning them 

### **Current behavior:**
The emotes of the wheel disappear 

#### **Evidence:**

https://github.com/user-attachments/assets/883df0d4-b604-4b13-8d02-2e1ab1b67cdb

#### **Additional Notes:**
This issue happened on Windows 11 pro 
16 GB RAM

**Comment by fcolarich** [comment]
After a lot of testing wearable/emotes related stuff, I have not been able to reproduce this issue at all with new or existing users, with onboarding rewards nor with minigame rewards :S 
I will close it for now and if it re-emerges like a phoenix we can get more logs and repro steps...
