### ISSUE TITLE
Terrain culling spike & OnWillRender 

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#2554]
### **Explorer Alpha build versions:**

Should be reproducable from the editor, rotate the camera and explore the world.

**We can ask what RenderStep1 is.**

![image](https://github.com/user-attachments/assets/23b2a489-65dd-45ec-9f47-eb9207a51c2d)
![image](https://github.com/user-attachments/assets/04f9ccaa-11b4-40f2-bb25-6930da1e5364)

**Comment by QThund** [comment]
It spends a lot of time computing the visibility of the trees, apparently, every now and then.
This data was captured using a build with deep profiling, being the player at Genesis plaza.
![Image](https://github.com/user-attachments/assets/6765627d-bdd2-4bd9-a49f-87e7a4999a8e)

**Comment by m3taphysics** [comment]
I don't seem to get any spikes (no deep profiling)

![image](https://github.com/user-attachments/assets/e4debe72-e110-4e76-87d2-d9dc74f3285e)
