### ISSUE TITLE
LoadFMODSound Spike (55,70) or adjacent scene

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#2556]
### **Explorer Alpha build versions:**
![image](https://github.com/user-attachments/assets/df4cc5fb-b9cf-4418-85aa-ce232619b3a7)

**Comment by QThund** [comment]
I couldn't reproduce the issue. Could you provide more info?

**Comment by QThund** [comment]
Some info about the possible issue:
https://discussions.unity.com/t/what-does-the-soundmanager-update-do/852609
