### ISSUE TITLE
FinalizeWearableLoadingSystem Budgeting / UniTask

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#2557]
### **Explorer Alpha build versions:**

Validate if its budgeted and verify if there is any other approaches to fixing. It can be replicated using Nicks tool.

![image](https://github.com/user-attachments/assets/ec1e942d-a9db-4176-986c-cf478e1c7d0c)

**Comment by QThund** [comment]
For me, in a build with deep profiling, it is not that bad
![Image](https://github.com/user-attachments/assets/3df9a15d-744c-4ba2-938a-a3acee0eb816)
