### ISSUE TITLE
[QA] Issues with compatibility on Exodus scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2562]
### **Explorer Alpha build versions:**
v0.38.0

### **Issue Description:**

The creators of the Exodus scene reported these two problems currently going on on their scene (as per their own words):

- We noticed that many of our assets now appear red.  It looks like maybe we have some incompatible textures?  We haven't released anything new, most of these textures rendered fine before, and were a "wooden" look

- Our users that are using the old client and the browser are able to authenticate and sign into our game, but users on the new one are not able.  Think this might be due to dcl.express middleware for signedFetch messages.  Has this changed for the new version, or should the authentication still work the same with that dcl.express?

#### **Evidence:**
(For the red assets)

![image (1)](https://github.com/user-attachments/assets/7238cbe5-09d3-4b6e-b0d9-c750f1343ec0)

**Comment by QThund** [comment]
Just to summarize our conversations so far: The problem may have to do with an issue when converting and deploying the assets, it's not allowed to use the same image file as a texture for both albedo and normals. A different file must be used instead for each, even if it has the same content.
@pravusjif 

More info:
https://github.com/decentraland/unity-renderer/issues/1583#issuecomment-985113886

**Comment by Juliendcl** [comment]
The team will work on it and will update us if needed, will close this ticket until then.
