### ISSUE TITLE
[QA] AB failing in parcel deployed on client

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2565]
### **Explorer Alpha build versions:**
v0.38.0

### **Issue Description:**

A user reported that, whenever the GLB file is imported to the web editor, is having the following error:

`Invalid GLTF: Material is incompatible with mesh primitive: Texture binding '/materials/2/pbrMetallicRoughness/baseColorTexture' needs 'TEXCOORD_0' attribute. Check /meshes/954/primitives/0/material`

This scene is deployed on `stom.dcl.eth` and working on browser, but on the new client, the parcel appears empty.
It appears that the AB is failing for this location.

#### **Additional Notes:**
(https://decentralandteam.slack.com/files/U079GRD9WTZ/F07S7HU7YEB/space-elevator.glb)

**Comment by davidejensen** [comment]
The scene is now correctly deployed
