### ISSUE TITLE
[QA] Minigames | Frozen fruits on the board in Salad Slash (17,-114)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2574]
### **Explorer Alpha build versions:**

- **v0.38.0**

### **Issue Description:**
In Salad Slash, fruits sometimes freeze on the board and don't disappear. The issue seems to occur when many bombs and fruits are sliced simultaneously, or during the switching of turns between players. The exact cause is unclear, but it happens frequently when playing multiple rounds.

### **STR:** 

1. Go to Salad Slash (17,-114) and start the game.
2. Slice multiple bombs and fruits at the same time.
3. Continue switching between multiple players in the queue.
4. Observe if fruits remain frozen on the board after slicing.

### ❌ Actual Result
- Fruits freeze on the board and do not disappear, disrupting the gameplay.

https://github.com/user-attachments/assets/0caf28c3-d169-4772-90ea-4e9c9933c796

### ✅ Expected Result
- Fruits should disappear properly after being sliced, and the board should reset cleanly between rounds.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by dzsunyec** [comment]
Pushed a fix for this as well. Systems were hiding the full vegetables, but not the sliced/partial vegetables. Should be okay now.

**Comment by dzsunyec** [comment]
Hmm, okay let me check. As I see it from the screenshots, even complete, un-sliced veggies/bombs are staying frozen...

**Comment by dzsunyec** [comment]
deployed another fix. Since removing fruits was working for me locally, I tried to reduce the sync messages (not sharing fruit positions on every frame), because maybe that was overloading the comms system, which then didn't receive the remove/hide messages. please test, not sure
