### ISSUE TITLE
[QA] Minigames | Score and lives number overlap in Salad Slash (17,-114)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2575]
### **Explorer Alpha build versions:**

- **v0.38.0**

### **Issue Description:**
When playing Salad Slash with two players, the score and lives indicator begin to overlap after one player finishes and the other starts their game. The overlap happens when the queue switches between players, and it gets worse after multiple rounds.

### **STR:** 

1. Go to Salad Slash (17,-114) with two different players (one on Mac, the other on Windows).
2. Player 1 starts the game while Player 2 queues up.
3. After Player 1 finishes, Player 2 starts the game.
4. Continue playing multiple rounds.
5. Observe the score and lives number overlapping from the previous game.

### ❌ Actual Result
The score and lives number overlap with data from the previous game, causing visual clutter and preventing the user from seeing their real score to reach the daily quest objective.

![salad slash](https://github.com/user-attachments/assets/cf8e713a-3a92-47f7-a950-81bc10e33042)

![salad slash](https://github.com/user-attachments/assets/2f2a734a-9730-485a-b048-f2d0c4a74690)

### ✅ Expected Result
The score and lives number should reset correctly and display without overlapping between games.

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by dzsunyec** [comment]
deployed a fix, but cannot test it alone

**Comment by dzsunyec** [comment]
Nope. didn't work it is still unsolved

**Comment by dzsunyec** [comment]
I think I found the issue, tested the fix locally and it worked, so I deployed it to workd. 
Counter IDs (for syncEntities) were too high numbers and that broke the sync...
