### ISSUE TITLE
[QA] Flickering issue in Genesis City street (-51,-51)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2577]
### **Explorer Alpha build versions:**

- **v0.38.0**

### **Issue Description:**
There's a persistent flickering issue occurring in one of the streets of Genesis City at coordinates (-51,-51). 

### **STR:** 

1. Launch the explorer and teleport to coordinates (-51,-51)
2. Observe the street visuals as you move around the area.
3. Look for flickering on the street surface.

### ❌ Actual Result
There is a visuals flickering on the street at -51,51 coords.

### ✅ Expected Result
The street visuals should remain stable without any flickering.

#### **Evidence:**

https://github.com/user-attachments/assets/c7332106-622d-4bc0-abc8-bc1fa2875835

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by DafGreco** [comment]
This issue is no longer happening on latest dev 

**Evidence:**

https://github.com/user-attachments/assets/fe183074-3b52-4cd2-a744-824bace33c75
