### ISSUE TITLE
[QA] Missing street from (-51,-51) to (-51,-1)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2578]
### **Explorer Alpha build versions:**

- **v0.38.0**

### **Issue Description:**
The street between coordinates (-51,-51) and (-51,-1) is missing. Instead of the expected street, there is a red floor present.

### **STR:** 

1. Launch the explorer and teleport to coordinates (-51,-51).
2. Move towards (-51,-1).
3. Observe the area where the street should be.

### ❌ Actual Result
There is no street between (-51,-51) and (-51,-1); instead, a red floor is present.

### ✅ Expected Result
The street should be present and visible between coordinates (-51,-51) and (-51,-1).

#### **Evidence:**

https://github.com/user-attachments/assets/d4d50b39-92c1-4af8-86b6-4e763ab3ce7d

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by anicalbano** [comment]
Fixed by #2882
