### ISSUE TITLE
Genesis plaza is not appearing as LOD when going out of range and coming back

### ISSUE THREAD

**Issue by davidejensen** [decentraland/unity-explorer#2579]
### **Issue Description:**
If we spawn in genesis plaza, run away till it disappears (out of range) and come back, as soon as it appears it's not as a LOD but as a full scene with running animations

### **STR:** 

  1. Spawn in genesis plaza
  2. Run away south while looking towards genesis plaza
  3. Run away till after the scene disappears
  4. Start walking back towards genesis plaza
  5. As soon as the scene will be shown again it won't be a LOD but the actual scene

### **Expected behaviour:**

The scene should re-appear as a lod

### **Current behaviour:**

The scene appears as a full scene not LODded

#### **Evidence:**

https://github.com/user-attachments/assets/2b4237a6-7a13-4883-bd18-25f99e877670

#### **Additional Notes:**
The test was done in a Mac M1

**Comment by dalkia** [comment]
Fixed on this [PR](https://github.com/decentraland/unity-explorer/pull/2581)
