### ISSUE TITLE
[QA] Minigames | Player removed from Tower of Hanoi game if another user joins the queue (61,-22)

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2587]
### **Explorer Alpha build versions:**

- **v0.38.0**

### **Issue Description:**
In the Tower of Hanoi minigame, if a player is actively progressing through levels and another user joins the queue, the active player is removed from the game, interrupting their progress. This issue is particularly problematic for Daily Quests that require players to reach higher levels, as the game cannot be completed if other users are continuously joining the queue.

### **STR:** 

1. Teleport to the Tower of Hanoi minigame at coordinates (61,-22) with another user.
2. Player 1 clicks "Play" to start the game, while Player 2 waits in the queue.
3. Player 1 progresses through the game until another player joins the queue.
4. Observe that Player 1 is removed from the game upon the new player joining

### ❌ Actual Result
Player 1 is kicked out of the game upon another user joining the queue, interrupting their progression, regardless of the current level. This prevents completing quests that require reaching higher levels if multiple players are present.

https://github.com/user-attachments/assets/6b7acf97-34e5-4600-b984-6c8aa4c5d690

### ✅ Expected Result
Player 1 should be able to continue progressing through levels uninterrupted, even if other users join the queue

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by Pejosonic** [comment]
This is the desired behavior by design so people doesn't have to wait too much to play.

Users can play again the game but start from a higher level if needed.
This is not working for completing the challenges?

**Comment by ai47patos** [comment]
The current design is that if someone is waiting in the queue, the current player has a limited time to play until the queue is moved
This can make completing the challenges more difficult because the harder ones require more time to complete
We need to think if we leave the design as it is and prioritize the cycle of players so everyone can play, or we give much more time to the active one so they can complete the quest

**Comment by Pejosonic** [comment]
I can do it!
Do you have a suggestion about min time to wait until letting other people play?
