### ISSUE TITLE
[QA] Memory/RAM not freeing up in client, causing excessive usage

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2592]
### **Explorer Alpha build versions:**

- **v0.38.0**

### **Issue Description:**
Memory usage in the client builds up over time and is not freed up during use. After extended sessions, the client consumes excessive amounts of RAM (e.g., 40GB). 

### **STR:** 

1. Launch the client.
2. Use the client for an extended period.
3. Monitor memory usage over time.

### ❌ Actual Result
Memory/RAM usage continues to increase, reaching up to 40GB without being released, even after long usage.

### ✅ Expected Result
Memory/RAM usage should stabilize and free up during normal operation to prevent excessive consumption.

#### **Evidence:**
![image](https://github.com/user-attachments/assets/a4f5f41c-7be7-458a-adad-2714655b98c3)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
We believe this is related to https://github.com/decentraland/unity-explorer/issues/2532

**Comment by AnsisMalins** [comment]
Do we know when this started happening? Or got noticeably worse?

**Comment by AnsisMalins** [comment]
Teleporting between 0,0 and 120,7 over and over again:
![image](https://github.com/user-attachments/assets/0d5a6ead-d681-4355-b803-fd1b526dd1a7)

**Comment by AnsisMalins** [comment]
I guess, there's one:
![image](https://github.com/user-attachments/assets/ca9df0bd-62af-4f14-9f64-0dd15c69ecf2)

**Comment by AnsisMalins** [comment]
This seems to be content dependent. Going to the plaza (0,0) or the mall (145,60) does not reliably raise memory usage. Going to seed (-104,-95) or art week (52,52) does so by about 200 MB every time.

**Comment by AnsisMalins** [comment]
Okay, so the easiest reproduction is to run `--debug --realm olavra.dcl.eth`, take a memory capture, then `/goto metadynelabs` and back, then do another memory capture. The difference is not large, but it's immediately obvious that extra copies of things are piling up. For example, the "PlayerName" game object, whatever it is, but for sure there should only be one when you're alone in an empty scene like olavra.
