### ISSUE TITLE
[QA] Emotes | Emote can be assigned to multiple slots simultaneously

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2599]
### **Explorer Alpha build versions:**

- **v0.39.0**

### **Issue Description:**
The same emote can currently be assigned to multiple slots in the backpack, resulting in duplicated emotes across different slots. Expected behavior is that when an emote is equipped in one slot, re-equipping it in another slot should remove it from the previous slot.

### **STR:** 

1. Open the backpack.
2. Equip an emote in one slot.
3. Attempt to equip the same emote in a different slot.

### ❌ Actual Result
The emote remains in both slots simultaneously.

### ✅ Expected Result
Equipping an emote in a new slot should remove it from the previous slot and place it in the new one.

#### **Evidence:**

![emote rep2](https://github.com/user-attachments/assets/d456a66b-63c0-406d-b496-a20a58ffcf84)

![emote rep](https://github.com/user-attachments/assets/2b343367-cb37-4314-a3c2-db1b941c5ee6)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by DafGreco** [comment]
This issue is not happening anymore on latest dev version or 0.49.0 

Closing ticket with evidence :

https://github.com/user-attachments/assets/a6344da4-be13-4fe6-af36-4e10d3b013cf
