### ISSUE TITLE
[QA] Genesis Plaza | Missing colliders on environment

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2608]
### **Explorer Alpha build versions:**
Not version specific

### **Issue Description:**

When going outside the Genesis Plaza cafe and running, we can see that there are colliders missing in rocks, floor and buildings. The avatar is able to transverse the structures and in case of teleporting to a location, it can get stuck on the floor under the building.

### **STR:** 

  1. Go outside GP cafe
  2. Start roaming around
  3. Run straight to rocks or floor elevations

### **Expected behaviour:**
Colliders should prevent the avatar from transversing structures

### **Current behaviour:**
Structures can be passed into

#### **Evidence:**

https://github.com/user-attachments/assets/a9bb3aa8-1a0f-409b-a1f0-21070b97b786

**Comment by ShibuyaMartin** [comment]
Hey guys! Im checking and the colliders seems fine for me. Should be something related to loading maybe? @m3taphysics 


<img width="1079" alt="Screenshot 2024-10-31 at 7 35 20 AM" src="https://github.com/user-attachments/assets/1889ca44-3c0c-423d-8cb0-c0633a3264a7">

<img width="460" alt="Screenshot 2024-10-31 at 7 35 28 AM" src="https://github.com/user-attachments/assets/e5851672-f480-4f5a-92ed-c788353914d9">

<img width="995" alt="Screenshot 2024-10-31 at 7 35 14 AM" src="https://github.com/user-attachments/assets/93c58633-8095-42b5-bd3c-98e02ad23a26">
