### ISSUE TITLE
[QA] User is stuck on infinite loading screen 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2614]
### **Explorer Alpha build versions:**
0.39.0

### **Issue Description:**
When opening the App , the user gets stuck on the loading screen 

### **STR:** 

  1. Open launcher 
  2. Enter to DCL
  3. Check that the loading screen appears infinitely 

### **Expected behavior:**
The user should be able to enter properly to the client 

### **Current behavior:**
The user gets stuck on the loading screen 

#### **Evidence:**

https://github.com/user-attachments/assets/e243076d-d264-48e4-bfd2-8444c3231ff9

[main.log](https://github.com/user-attachments/files/17555959/main.log)

[Player.zip](https://github.com/user-attachments/files/17555977/Player.zip)

#### **Additional Notes:**
This issue is happening on Windows as far as we know

**Comment by m3taphysics** [comment]
Isolated issue based on the ISP blocking access
