### ISSUE TITLE
[QA] Soft-lock when tapping Friends button and the map puzzle 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2623]
### **Explorer Alpha build versions:**
0.39.0

### **Issue Description:**
When a user is on polkadot stuff (13,-1) and taps the Friends button and then the map puzzle the screen becomes unresponsive to the user 

### **STR:** 

  1. Open 0.39.0
  2. Go to 13,-1 
  3. Tap the friends button 
  4. Then tap the Map puzzle button 
  5. Validate that a soft-lock happens 

### **Expected behavior:**
No actions should have a soft-lock 

### **Current behavior:**

When a user is on polkadot stuff (13,-1) and taps the Friends button and then the map puzzle the screen becomes unresponsive to the user 

#### **Evidence:**

https://github.com/user-attachments/assets/83a61908-7e87-483a-bc07-632ee5d9152b

#### **Additional Notes:**
This issue happens on Windows and Macos

**Comment by DafGreco** [comment]
This issue is still happening on latest dev and latest release (0.49.0)

Due to the soft-lock the video recorded for this issue got lost because I was not able to save it before restarting the PC.

**Comment by fcolarich** [comment]
I cant seem to be able to open the map minigame?
I only get an AI thing when clicking on the middle orb... and no map 😢

**Comment by fcolarich** [comment]
Corroborated with QA, in current version of the scene this bug is not reproducible!
