### ISSUE TITLE
[QA] Minigames | Liquid Labyrinth Pipeline Illumination Issue

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2637]
### **Explorer Alpha build versions:**

- **v0.39.0**

### **Issue Description:**
In the Liquid Labyrinth minigame, the goal is to connect pipes, and when time runs out, water flows through them, illuminating the pipes as it advances. However, `SOMETIMES` the illumination fails, leaving some pipes with shiny liquid while others do not light up.

This issue is intermitent, doesn't have an 10/10 repro step

### **STR:** 

1. Start the Liquid Labyrinth minigame.
2. Connect the pipes to complete the objective.
3. Wait for the time to run out.

### ❌ Actual Result
Some pipes do not illuminate when the water flows through them.

https://github.com/user-attachments/assets/94816346-4390-4fff-a3ca-97540eaf3698

### ✅ Expected Result
All connected pipes should illuminate as the water flows through them.

**Comment by surz90** [comment]
I make an update to the liquid labyrinth repo: https://github.com/decentraland-scenes/minigame-pipe-mania/commit/f3b9606f2f55fd423801cf022c0a0b575d3b696e to preload 3d model that is used on the scene at the start of the scene. Hope this solve the issue
