### ISSUE TITLE
[QA] NPCs Not Visible or Not Working in Specific Scenes

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2645]
### **Build version:**
- **v0.39.0** 

### **Issue Description:**
In specific scenes, NPCs are either not visible or not functioning as expected. This issue has been observed in the following locations:
- **Crackden** (-91, -89)
- **My Happy Place** (/world myhappyplace)

### **STR:** 

1. Enter the scene at Crackden (-91, -89) or My Happy Place (/world myhappyplace).
2. Look for NPCs in the area.
3. Observe whether the NPCs are visible and interactive.

### ❌ Actual Result
NPCs are either not visible or not functional in these scenes.

![-91,-89 actual](https://github.com/user-attachments/assets/28ee2625-7c1b-4ddc-b7da-e09d49cb3f7c)

![image](https://github.com/user-attachments/assets/bad6e3e6-f667-42d9-bd41-d43cab0ced3e)

### ✅ Expected Result
NPCs should be visible and working as intended in all scenes.

![-91,-89](https://github.com/user-attachments/assets/b4b3d425-b8aa-4379-a6c5-f45b56f72e02)

![image](https://github.com/user-attachments/assets/83e7b4f1-29f4-433e-84c3-719e6f8e1d02)

### **Repro Index:**
10/10

**Comment by pravusjif** [comment]
Tackled at https://github.com/decentraland/unity-explorer/pull/2742

**Comment by pravusjif** [comment]
Fix merged, should reach production with Explorer `v0.46`
