### ISSUE TITLE
[QA] Rapture Art gallery not visible in client 2.0

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2650]
### **Build version:**
Not version specific

### **Issue Description:**

User's scene not visible in new client; Rapture Art Gallery 

### **STR:** 

  1. `/goto -88,-66`
  2. Walk around and see that the scene does not appear
  3. Check over the minimap and you'll see the name of the scene **Rapture Art Gallery**

### **Expected behavior:**
Since the scene is SDK7, it should be visible

### **Current behaviour:**
The scene does not appear

### **Repro Index:**

10/10

#### **Evidence:**
![image](https://github.com/user-attachments/assets/efaf3a9d-8318-4b5f-a996-ab216a048363)

**Comment by KJwalker3D** [comment]
Trying to upvote this 🙏

**Comment by Vitsky4079** [comment]
https://drive.google.com/file/d/1WkV4VRsKfUZ-e5Ce5IfRzz0M_HbVYvOe/view?usp=sharing
https://drive.google.com/file/d/1vbovLSth8ZFy7O6Fs9vt23c9o9onlKvf/view?usp=sharing
https://drive.google.com/file/d/1KBqxYAFhwnzencedyP68iu13oRH8-Ytm/view?usp=sharing

[Player.log](https://github.com/user-attachments/files/17603988/Player.log)
[main.log](https://github.com/user-attachments/files/17603990/main.log)

**Comment by Kaze-No-Kai** [comment]
[Player.log](https://github.com/user-attachments/files/17605863/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17605864/Player-prev.log)

https://drive.google.com/file/d/18a0uq_hO0wr3arj15clNMPJMZvGXxpIw/view?usp=drive_link

We were able to get in the scene at some point, it loads after few tries to jump in, not high repro, but visible in the above video examples.

**Comment by Kaze-No-Kai** [comment]
May be related to https://github.com/decentraland/unity-explorer/issues/2262 ?

**Comment by anicalbano** [comment]
1. When getting closer to the scene it re-appears, but getting into it makes it disappear and do not appear back.
2. It's impossible to teleport to the points of the scene (10/10 repro on my end) to reach it we got to go to a close coord and walk to it.

Logs and videos:

https://github.com/user-attachments/assets/2c91fbd6-a178-4db0-bf00-70cecd8c7b29


https://github.com/user-attachments/assets/72a84ea4-01c9-4cbb-8337-5070990eccbf


[Player.log](https://github.com/user-attachments/files/17616940/Player.log)
