### ISSUE TITLE
[QA] Explorer Freezes Entire Windows System Requiring Forced Shutdown

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2676]
### **Build version:**

- **v0.39.0** Launcher Version

### **Issue Description:**
The Explorer on Windows repeatedly freezes the entire system, making it unresponsive and requiring a forced shutdown. The issue seems to occur in various locations, frequently while interacting with quests or minigames. Notably, it prevents access to the Task Manager or any other workaround for recovery. 

❗📋 Additional Context
This issue has occurred consistently, with four freezes happening in one day while attempting to complete the daily quest. After clearing the cache, the issue doesn’t occur for the rest of the day, but it usually returns the following day.

### **STR:** 

1. Open the Decentraland Explorer on Windows.
2. Go to **Recall Rush** with `/goto 36,86`.
3. Progress through the game:
   - Attempt 1: Explorer froze at level 5.
   - Attempt 2: Explorer froze at level 3.
4. Restart and attempt other locations:
   - **Color Pop Minigame** (`/goto -121,-60`): Quest completed without issues.
   - **Liquid Labyrinth**: Explorer froze again, requiring a forced shutdown.

**Note**: Similar freezing issues have also occurred in **Genesis Plaza** and other scenes.

![capture_241031_131141](https://github.com/user-attachments/assets/62bb998b-4a4b-4d76-8159-b38dd1d80538)

### ❌ Actual Result
Explorer freezes the entire Windows system, requiring forced shutdowns. Task Manager and other workarounds are inaccessible.

### ✅ Expected Result
Explorer should function without freezing the system, allowing task termination via Task Manager if necessary.

### **Repro Index:**
5/10 attempts 

#### **Evidence:**

[Player-prev.zip](https://github.com/user-attachments/files/17590928/Player-prev.zip)
[Player.zip](https://github.com/user-attachments/files/17590930/Player.zip)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

Device name	MSI
Processor	12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	43366277-7FAD-40FB-A216-A642AE578075
Product ID	00342-22244-03920-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by DafGreco** [comment]
This issue also happens when going to 13,-1 an doing the next steps :

https://github.com/decentraland/unity-explorer/issues/2623
