### ISSUE TITLE
Scene flickering between scene and LOD

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-explorer#2693]
Right now, when approaching a scene, you may face the following situation. A pop between the real scene and the LOD

https://github.com/user-attachments/assets/f19cdd6e-ae27-4db4-a628-9752e6859d4f

The "pop to scene" is inevitable on the current state. Even if assets are cached, the scene loading take a couple of seconds to startup. This breaks immersion

The fix for that would be
- Start loading the scene with assets off.
- Leave the LOD on while this process is occuring
- Do the swap when the scene is ready

**Comment by m3taphysics** [comment]
⚠️ I have raised to critical as its possible to run around the scene itself stops running entirely. And lods are not being built ⚠️
