### ISSUE TITLE
[QA] Minigames | Play Button Fails to Load Inconsistently

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2721]
### **Build version:**

- **v0.40.0**

### **Issue Description:**
There is an inconsistent issue where the minigame `Play` button fails to load, sometimes remaining black indefinitely instead of turning green when ready. Users have reported that changing locations or attempting to access other minigames does not resolve the issue. The only way to recover the button state is by closing and reopening the Explorer. In one instance, Dawid closed and reopened the Explorer, but the button still did not load after going to a minigame.

### **STR:** 
1. Start the Decentraland Explorer.
2. Teleport to any minigame or walk to them
3. .
4. Observe the state of the minigame button.
5. If the button is black and does not change to green, try:
   - Changing location within the Explorer.
   - Accessing a different minigame.
6. Observe whether the button remains unresponsive.

### ❌ Actual Result
The minigame button sometimes does not load, staying black indefinitely. It does not change to green even after attempting to change locations or access other minigames. Restarting the Explorer is necessary to recover the button state.

### ✅ Expected Result
The minigame button should load correctly and turn green when ready for play. Users should be able to change locations or access different minigames without encountering a loading issue.
Este formato

### **Repro Index:**
4/10 

#### **Evidence:**

https://github.com/user-attachments/assets/a831429a-1fed-40cf-80de-a35637123c13

**LOGS**:
[Player.log](https://github.com/user-attachments/files/17637641/Player.log)
[main.log](https://github.com/user-attachments/files/17637642/main.log)

[Player.log](https://github.com/user-attachments/files/17637796/Player.log)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

**Comment by DafGreco** [comment]
This issue is no longer happening on 0.46.0
