### ISSUE TITLE
[QA] First person view is not forced when playing Ratscape

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2815]
### **Build version:**
0.41.0
0.42.0 (not released yet)

### **Issue Description:**
When teleporting to Metadynelabs the first person view is not forced and the teleport gun is never given to the user making it unable to play any type of levels on Ratscape

### **STR:** 

  1. Open 0.42.0
  2. Teleport to Metadynelabs 
  3. Validate that when the level loads...the first person view is never forced and the teleport gun is never given to the user 

### ❌ **Actual Result:**
When teleporting to Metadynelabs the first person view is not forced and the teleport gun is never given to the user making it unable to play any type of levels on Ratscape

### ✔️ **Expected Result:**
First person view must be forced in order to play properly 

### **Repro Index:**
10/10

### **Evidence:**

https://github.com/user-attachments/assets/e5ebacbf-8617-4e81-b7f6-b6f0f7846a7a

#### **Additional Notes:**
This issue happens on Windows and Macos

**Comment by pravusjif** [comment]
Fixed at https://github.com/decentraland/unity-explorer/pull/2859

**Comment by fcolarich** [comment]
You rock! thank you Pravus!!!!!!
