### ISSUE TITLE
[QA] Map | DCL Music Festival Parcel Misalignment

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2885]
### **Build version:**

- **v0.45.0**

### **Issue Description:**
The DCL Music Festival scene appears offset on the map, misaligned with its designated square parcel. This is purely a visual issue in the map view, as no additional problems are observed within the explorer itself.

### **STR:** 

1. Open the Decentraland Explorer.
2. Click on the minimap in the upper-left corner.
3. Locate the DCL Music Festival parcel on the map.
4. Observe that the scene is visually misaligned and appears outside its designated parcel square.

### ❌ **Actual Result:**
The DCL Music Festival scene appears offset on the map, misaligned with its parcel.

### ✔️ **Expected Result:**
The scene should be perfectly aligned with its designated square parcel on the map.

### **Repro Index:**
10/10 attempts 

### **Evidence:**
![issue mapa](https://github.com/user-attachments/assets/e1b9091d-ad5f-4932-8a2f-ce1ed89a2965)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by m3taphysics** [comment]
We are redeveloping this view
