### ISSUE TITLE
[QA] Errors on requests are not being sent to the scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#2943]
### **Build version:**
Not version specific

### **Issue Description:**

When we make a request on a campaign that has already ended, on EA side the request error is only giving the statusCode and not the root of the error as it follows (example):

`"error": {
        "statusCode": 400,
        "code": "campaign_key_uninitiated"
      }`

### **STR:** 

  1. Make a request on a campaign that has already ended
  2. Check on the request result

### ❌ **Actual Result:**
We can only see the `"statusCode":400` , only `HTTP/1.1 400 Bad Request`

### ✔️ **Expected Result:**
Whe should be able to see the full response with the code of the failed request

### **Repro Index:**

10/10

**Comment by aixaCode** [comment]
Will be fixed in v0.48 release
