### ISSUE TITLE
Missing default floor on scenes

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#358]
### **Issue Description:**
Some scenes do no have a geometry floor and they rely on the previous green floor shader to act as a base ground. Right now, we dont have that and we display the satellite view as ground. We need to mask the satellite view with ground texture for all the scenes around the player that are loading any type of LOD, or at least LOD0 and Scene Runtime

### **Steps to reproduce:**

  1. Go to -6,-15
  2. Check the floor

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ x]  100%

### **Severity:**

- [ x] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/41490935/b9d07ba2-ba72-4d36-a8fa-5d230a3a32b0)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/82a45c3f-8682-45b1-89f0-b7b6e0d8472c)

**Comment by m3taphysics** [comment]
Duplicate
