### ISSUE TITLE
Optimize entity fetching by Transform at AvatarModifierAreaHandlerSystem

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-explorer#359]
To ensure the needed behaviour of the AvatarModifierArea, there are a couple of queries implemented **to fetch an Entity based only on its Transform** (since the CharacterTriggerArea takes advantage of Unity physics to detect avatars with a trigger collider, thus only having their Collider->Transform).

Those queries currently use a lambda function to do the needed entity-finding.

We should find a way of avoiding using those lambda to monimize memory and performance impact.

Those queries are currently running when:
* An avatar enters an Avatar Modifier Area
* An Avatar leaves an Avatar Modifier Area
* An Avatar Modifier Area gets updated and has avatars already inside

-----------------

* Avatar Modifier Area component original PR: https://github.com/decentraland/unity-explorer/pull/336
* [Target Query 1](https://github.com/decentraland/unity-explorer/blob/5f84874875683d036d76987f59315bd41f8ab127/Explorer/Assets/DCL/SDKComponents/AvatarModifierArea/Systems/AvatarModifierAreaHandlerSystem.cs#L96~L116) & [Target Query 2](https://github.com/decentraland/unity-explorer/blob/5f84874875683d036d76987f59315bd41f8ab127/Explorer/Assets/DCL/SDKComponents/AvatarModifierArea/Systems/AvatarModifierAreaHandlerSystem.cs#L118~L137) (links pointing to file in original PR, since PR not merged in `main` yet due to building times chaos)

**Comment by sandrade-dcl** [comment]
This lack of performance is provoking the issue #1643.
