### ISSUE TITLE
Memory: Compress and Resize Textures

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#38]
New description
----

## How it works now
- Textures are loaded by Unity Web Request
  - It decodes JPG and PNG only
  - Does not compress textures, PNG is loaded into RGBA32, JPG into RGB24
  - It is the only built-in way to download textures
- Without compression images have an enormous size, e.g. 2k RGBA takes 128 MB RAM
- We don't control all endpoints, users may expose images as they wish quickly bloating up memory usage. Currently 3rd party textures and textures hosted in Catalyst are TOP1 contributors to the memory usage

## Expected Behavior
- Textures are decoded and compressed without intermediate results and allocations
- Texture compression is selected based on hardware capabilities, e.g. 2k ASTC 8x8 takes 8 MB
- It's possible to target a specified maximum textures resolution that a user can control from Settings

## Nice to have
- Support for Webp/Gif
- Support for different compression quality to target different hardware tiers more aggressively

## Possible Solution
- Integrate any Rust/C++/C# that can decode and compress a texture from the given byte pointer without additional managed allocations.
   - As a bonus majority of the existing plugins support more formats out of the box
   - There are very complex solutions that would require a lot of bridging, a weighed one should be selected according to our needs
- Change the current way of loading textures to loading a native byte array instead and passing it for decoding into the plugin
- Pre-allocate the texture on Unity side with the selected [format](https://docs.unity3d.com/ScriptReference/TextureFormat.html)
- The result should be GPU-compatible straight-away so it is possible to [write it directly into the preallocated texture](https://docs.unity3d.com/ScriptReference/Texture2D.GetRawTextureData.html) or [via this](https://docs.unity3d.com/ScriptReference/Texture2D.LoadRawTextureData.html)

## Benefits
- We will experience immediate memory relief, memory consumption will be more predictable for users
- We don't need to make a design decision to forbid all 3rd links to textures and move everything to our catalyst, we can  implement it purely on our side within the predictable period of time

Old description
----

Output should be a texture in a GPU-friendly format (that can be uploaded to GPU without additional conversions, e.g. by `SetRawData`)

It's possible to retrieve textures from an external source; in this case it can't be preprocessed

Unity does not expose API for decoding textures on a worker thread. Unity support recommended using an external library, e.g. [FreeImage](https://freeimage.sourceforge.io/download.html)

I tried to integrate it in the past without any success, and it was not straightforward at all.
I found a [topic](https://forum.unity.com/threads/trying-to-get-the-freeimage-library-to-work-in-unity.1194094/) where a guy tried to do the same without success either.

Just like for Meshes we should introduce different levels of LODs, LODs can be used as mip-maps

**Comment by mikhail-dcl** [comment]
I have a plan in my head regarding textures:
Integrate a library for decoding (FreeImage)
Integrate a library for runtime compression (similar to https://docs.unity3d.com/ScriptReference/Texture2D.Compress.html) that can run on a worker thread (I'm talking to Unity to find one)
For textures web requests: use a preallocated buffer, just like we discussed before
On a background thread decode and compress
Take a texture from the pool (in case it is similarly sized we can set data to the internal array directly, otherwise reload the internal array)
This technique can be applied to both single textures and gifs

**Comment by pravusjif** [comment]
Kudos to you, based on your notes your approach looks promising!

You probably already saw this but just in case it's useful for you in any way, FYI for the WebGL client, [the kernel processes GIFs in a webworker/thread](https://github.com/decentraland/unity-renderer/blob/60edb726692ca9fc88226d93aedb4cecbfcd3a3c/browser-interface/packages/unity-interface/gif-processor.ts), stores the texture and sends a pointer to the texture to unity and in unity [the image is loaded from that pointer](https://github.com/decentraland/unity-renderer/blob/60edb726692ca9fc88226d93aedb4cecbfcd3a3c/unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/GIFProcessingBridge/GIFProcessingBridge.cs#L115~L116).

**Comment by NickKhalow** [comment]
@mikhail-dcl @m3taphysics do we have a test set of images that we would support? I need it to make a playground and to test the solution

**Comment by NickKhalow** [comment]
@mikhail-dcl FreeImage uses BGR by default on Little-Endian machines, we have to set it manually during lib's compilation 

// Color-Order:
// The specified order of color components red, green and blue affects 24-
// and 32-bit images of type FIT_BITMAP as well as the colors that are part
// of a color palette. All other images always use RGB order. By default,
// color order is coupled to endianness:
// little-endian -> BGR
// big-endian    -> RGB
// However, you can always define FREEIMAGE_COLORORDER to any of the known
// orders FREEIMAGE_COLORORDER_BGR (0) and FREEIMAGE_COLORORDER_RGB (1) to
// specify your preferred color order.
#define FREEIMAGE_COLORORDER_BGR    0
#define FREEIMAGE_COLORORDER_RGB    1
#if (!defined(FREEIMAGE_COLORORDER)) || ((FREEIMAGE_COLORORDER != FREEIMAGE_COLORORDER_BGR) && (FREEIMAGE_COLORORDER != FREEIMAGE_COLORORDER_RGB))
	#if defined(FREEIMAGE_BIGENDIAN)
		#define FREEIMAGE_COLORORDER FREEIMAGE_COLORORDER_RGB
	#else
		#define FREEIMAGE_COLORORDER FREEIMAGE_COLORORDER_BGR
	#endif // FREEIMAGE_BIGENDIAN
#endif // FREEIMAGE_COLORORDER

**Comment by NickKhalow** [comment]
It's finished partly with https://github.com/decentraland/unity-explorer/pull/2568 PR, MipMap and Gif supports remain to do
