### ISSUE TITLE
Landscape Elements are not synchronised across machines

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#384]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
The landscape elements are not correctly seeded across the network, we tested and each machine had a different layout.

![image](https://github.com/decentraland/unity-explorer/assets/296469/50dc40bb-12ad-4a6a-bc5f-92d9a3576785)

### **Steps to reproduce:**

  1. Join machine 1 and run to an area with landscape elements such as rocks
  2. Joine machine 2 and run to the same location
  3. Share screen and notice there is a difference on both

### **Expected behaviour:**

The landscape should be the same on both machines.

**Comment by m3taphysics** [comment]
@anicalbano can you re-check this issue on latest main?

**Comment by anicalbano** [comment]
Looks correct on the latest build! Closing the ticket.
