### ISSUE TITLE
[QA] It's possible to join a realm with an invisible avatar

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#385]
### **Issue Description:**

The load order in the background prevents the avatar from loading quickly, and thus its possible to join the realm with an entirely invisible avatar. This appears to be due to scenes loading and nothing having a real priority of load.

### **Steps to reproduce:**

  1. Open the build
  2. Login before the avatar appears
  3. Observe

### **Expected behaviour:**
The avatar must be visible inside the realms

### **Current behaviour:**
Avatar cannot be seen

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [x] Critical
- [ ] Blocker

### **Priority:**
- [x] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [x] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
@anicalbano can you re-check this?

**Comment by anicalbano** [comment]
> @anicalbano can you re-check this?

Confirmed that it's not happening anymore. Closing the ticket!
