### ISSUE TITLE
Implement correct click distance for interactables

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#391]
### **Issue Description:**
When calculating the click distance, we currently calculate the distance between the camera position and the click position. This is a bad practice, because we end up with different interaction capabilities depending on 1st or 3rd camera view. 

We should calculate distance from the avatar Transform position. This should affect both the hover hint display, and the distance property on the hit event.

The click raycast should be done from the camera, as it is now.

- [ ]  Use the avatar Transform position to calculate hover hints
- [ ] Use avatar position Transform position to populate the distance property in hit event

**Comment by Kinerius** [comment]
This should have been fixed with https://github.com/decentraland/unity-explorer/pull/489
