### ISSUE TITLE
Support for eyes & their masks

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#395]
### **Issue Description:**
Eyes have two required assets to work, the main texture and the mask. And this is the only wearable that has this special requirement.
Our load wearable system is not prepared to do that; work with an array of assets rather than a single asset.

- [x] Allow wearable system to work with an array of assets
- [x] Integrate eyes & their masks into the shader

**Comment by mikhail-dcl** [comment]
https://github.com/decentraland/unity-explorer/pull/424
