### ISSUE TITLE
Incorrect texture displayed using Asset Bundles sharing the same model

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-explorer#401]
## Description
We are experiencing an issue where multiple scenes deployed to the Art Week Plaza are not loading models or textures correctly. 
The same issues existing in current renderer.
The problem occurs when we have the same model and texture names (`cube_display.glb`) but with different texture content. After deploying all three scenes, they are displaying the same texture instead of their respective unique textures.

## Affected Scenes
- M1: https://github.com/decentraland-scenes/dcl_art_week_2024_m1 (coordinates: 60,68)
- M9: https://github.com/decentraland-scenes/dcl_art_week_2024_m9 (coordinates: 59,64)
- M14: https://github.com/decentraland-scenes/dcl_art_week_2024_m14 (coordinates: 65,63)

## Steps to Reproduce in unity-renderer
1. Visit the Art Week Plaza in Decentraland on web
2. Navigate to the coordinates of the affected scenes (M1, M9, and M14).
3. Observe that the `cube_display.glb` model in each scene is displaying the same texture instead of their respective unique textures.

## Expected Behavior
Each scene (M1, M9, and M14) should display the `cube_display.glb` model with its respective unique texture content.

The issue root cause comes from caching ABs based on the hash, which is the same for those models.
We could investigate how to introduce extra information for the id used in caching, i.e combining scene id to differentiate the assets

**Comment by mikhail-dcl** [comment]
During fixing the problem we should consider the following:
- Asset Bundle can be loader either from Embedded or Web resources, thus, we can't purely rely on the URL
- We should not loose the capability of shared asset bundles between different scenes
