### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by ShibuyaMartin** [decentraland/unity-explorer#420]
### **Issue Description:**

<img width="178" alt="Screenshot 2024-03-21 at 11 40 03" src="https://github.com/decentraland/unity-explorer/assets/25348765/5d6397b3-ce69-4734-b832-5e9aeaf63a17">

### **Steps to reproduce:**

  1. Open the main branch and check any transparent alpha blend wearable.
  2.
  3.

### **Expected behaviour:**
Should be transparent, not opaque.

### **Current behaviour:**
The wearables is being seen as opaque.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
Closing in favor of this one: https://github.com/decentraland/unity-explorer/issues/419
