### ISSUE TITLE
Metadyne realm doesn't work

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#432]
Stuck on the custom in-scene Loading Screen - possibly some events are missing - investigation required

**Comment by NickKhalow** [comment]
for which scenes?

**Comment by NickKhalow** [comment]
it's definitely not observables, checked from the source code with @m3taphysics

**Comment by NickKhalow** [comment]
the world: MetadyneLabs.dcl.eth

**Comment by NickKhalow** [comment]
Progresss: now we can get into the play level

Known errors:
- Player cannot pick the weapon
- Dialogs won't appear
- Raycasting won't work
- (Minor) progress bar won't work, but the level starts


Supposed fixes:
- Raycasts
- UI (in progress by Santi)
