### ISSUE TITLE
Compression of `Movement` Message

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#457]
In comparison with the previous client, the `Movement` [message](https://github.com/decentraland/protocol/blob/1cf6abc820ca3948649d03eb57c5787814ef27e3/proto/decentraland/kernel/comms/rfc4/comms.proto) has considerably grown.

In its current form, we will blow up the bandwidth pretty quickly. And it can't be delivered as production-ready without compression.
We already know the tactics to be applied (and they are already discussed):

- Floating point mantissa and exponent reduction
- Putting additional reliable data to `Participant.Metadata`
- Inferring some animation blends from bit-wise state

We didn't have time to implement it during the cycle.

**Comment by olavra** [comment]
@mikhail-dcl didnt we do any optimization yet for format compression?

**Comment by mikhail-dcl** [comment]
It's worth raising the priority as:
- the bandwidth will blow up in the production-ready flow as the total throughput is significantly higher than in `unity-renderer`
- making any future additions to the protocol will be virtually impossible without any optimization as it will make things exacerbate even further

**Comment by m3taphysics** [comment]
@NickKhalow please review with @mikhail-dcl before commencing this and reach out to me too.
