### ISSUE TITLE
[QA] Backpack not reflecting the changes made on the avatar

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#461]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**

By changing wearables on the backpack and closing, the changes are not being saved

### **Steps to reproduce:**

  1. Go to backpack
  2. Make some changes to the avatar's appearence 
  3. Close the backpack

### **Expected behaviour:**
Changes are reflected in world

### **Current behaviour:**
No changes visible

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [X] Critical
- [ ] Blocker

### **Priority:**
- [X] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [X] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**

https://github.com/decentraland/unity-explorer/assets/139157886/d739c6fd-3948-4a1e-b43f-4df49ff3221d

**Comment by lorux0** [comment]
Could not repro on my side. Could you add details to the steps? Like the urn of the wearables you are trying to equip? How is your profile composed?

**Comment by lorux0** [comment]
Perhaps its fixed by this pr, since you were able to equip incompatible wearables, which end up in possible undesired results.
https://github.com/decentraland/unity-explorer/pull/610

**Comment by anicalbano** [comment]
Fixed in #641
