### ISSUE TITLE
[QA] Blank sceen on backpack after open-close-open

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#462]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**

After opening the backpack to make a change, closing it and opening it again, the screen appears blank. It's necessary to pivote in between options to see the backpack correctly again.

### **Steps to reproduce:**

  1. Open the backpack and close it
  2. Re open the section

### **Expected behaviour:**
Backpack can be seen

### **Current behaviour:**
Blank scene

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [X] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [x] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [x] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**

https://github.com/decentraland/unity-explorer/assets/139157886/85a3ef0b-6f8b-425a-bde5-048da6cbf2b5

**Comment by olavra** [comment]
This is suppose to be fixed in another branch

**Comment by anicalbano** [comment]
It's fixed in the latest build
