### ISSUE TITLE
[QA] Instantiated avatars are not reflecting self avatar locomotion

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#465]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**
### **Issue Description:**

When instantiating an amount of avatars, in some ocations the locomotion breaks and there is no movement other thant sliding and jumping

### **Steps to reproduce:**

  1. Instantiate avatars (more than 30 if possible)
  2. Move around
  3.

### **Expected behaviour:**
The avatars instantiated replicate self movement

### **Current behaviour:**
There is no movement of the avatars instantiated and self avatar 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [X]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [X] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [X] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**

https://github.com/decentraland/unity-explorer/assets/139157886/87d74ed5-551c-4f4a-886d-1384d2b4c813

**Comment by m3taphysics** [comment]
Not a bug :)
