### ISSUE TITLE
[QA] LOD color changes in some structures when going closer or farther

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#466]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**

This can be tested in the structure on (13,38) by moving away or getting closer of it.
You'll notice that, by being far, it turns green and going closer shows the structure as it is.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [X] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [X] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [X] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/aa516a2b-2538-4937-9529-7354058057e3)

**Comment by AlejandroAlvarezMelucciDCL** [comment]
Isn't this related to the LOD system? Have you tried toggling the lod color in the debug menu?

**Comment by m3taphysics** [comment]
@dalkia is this still happening in the new LODs?
