### ISSUE TITLE
[QA] When teleporting, some colliders are missing

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#469]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**
In some coordinates, the floor collider is missing and the avatar goes down.

### **Steps to reproduce:**

  1. Go to (-147,95) to check the issue

### **Expected behaviour:**
The avatar must be on top of the floor

### **Current behaviour:**
The avatar traspasses the floor 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [X]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [X] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [X] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/476933cc-164c-4a43-964c-65ba076695e5)

#### **Additional Notes:**

If we start walking and go back to the section in which the avatar traspassed the floor, everything works as expected

**Comment by olavra** [comment]
This happens whenever you teleport to a empty parcel as the spawn point may be placed below a elevated terrain. Avatar needs to be spawn to the maximum elevation possible in empty parcels.
