### ISSUE TITLE
Show grass floor masking Satellite floor

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#479]
### Problem
- The current default floor of the scene is the satellite view, and that is only suitable for large distances.
- Other scenes like worlds, do not have a satellite view and needs a default

### Solution
The floor shader needs to be composed of to set of textures, one default grass tile (repeated in the same amount as the terrain), and the satellite view textures. The player position needs to be input to the shader to create circular mask between both textures to show the grass nearby to the player, and the satellite view on afar. 
The radious of the mask can be tweaked to determine the best distance.
The mask should be smooth to have a smooth transition between one texture and the other.

In order to get the player position to place the mask properly, the position vector will need to be feed to the shader, either by a global parameter, or with a specific systems that modifies the material properties.

This is just one proposed solution, if there is a better approach go for it

**Comment by GBirch33** [comment]
You're going to have to explain this better, because I don't under the masking concept, what exactly are we masking?
