### ISSUE TITLE
Port "outline" render feature for interactables

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#483]
### Problem
The previous explorer had a render feature to outline / glow the selected objects of the environment like players and other interactables.
We want the interactables to be highlighted the same way in explorer alpha.
![image](https://github.com/decentraland/unity-explorer/assets/41490935/f3fa149d-3a31-43ea-8f06-883b905d0e8f)

### Solution
Try to port the same render feature so we can highlight the interactable objects in the scene without a big cost of performance.
Bare minimun of this feature should be the pixelated border around the objects and the silluete color fill, additionally if we can find a better algorithm for the blur function it would be nice, but not mandatory. 

@Kinerius is handling the port but we need @GBirch33 to review the performance of the blur as it caused many issues in the previous renderer.

**Comment by GBirch33** [comment]
Is the old method this?

https://drive.google.com/file/d/1pXh64cJX9cLfZjTplOZ6m0KG5rNuU0m-/view

**Comment by olavra** [comment]
> Is the old method this?
> 
> https://drive.google.com/file/d/1pXh64cJX9cLfZjTplOZ6m0KG5rNuU0m-/view

Yes, an extended version of that. We had 3 things drawn: the pixel edge, the same edge but blurred (behind it) and the color mass of the interior of the avatar with a gradient
