### ISSUE TITLE
Scene Shader does not make use of exponential fog

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#485]
### Problem
We need to decide if we are going with exponential fog before we fix this issue.

The shader used for the scenes is not processing the exponential fog
![image](https://github.com/decentraland/unity-explorer/assets/41490935/1ecd84fc-97d5-4190-88b3-2460ca86dc78)

It seems to be working on linear
![image](https://github.com/decentraland/unity-explorer/assets/41490935/31c38808-e33f-49a6-9c00-cbf246133337)

**Comment by m3taphysics** [comment]
@mikhail-dcl - this may be fixed but we need to verify if we need to re-generate the asset bundles.

**Comment by GBirch33** [comment]
It's presumed that we used asset bundle to create these shaders and the AB convertor was set to Linear Fog and therefore there was no shader created for Exponential Fog shader created. I believe this to be fixed. Needs verification.
