### ISSUE TITLE
[QA] Diferent avatar on web auth and in world when changing login method

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#486]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**

When changing the login method or logging in with another account, the avatar on the web auth is different from the one that appears on the client

### **Steps to reproduce:**

  1. Start a login
  2. Select another login method or change the account
  3. Accept the auth with the login number

### **Expected behaviour:**
The avatar shown in the web for the authorization must be the same on the client.

### **Current behaviour:**
Avatars are different, on the client, it shows the default avatar.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [x] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [x] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [x] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/6a67efbf-6815-4106-aea8-7d329adf629f)

**Comment by m3taphysics** [comment]
This is likely on the dapps side, @nachomazzara can you help here?
