### ISSUE TITLE
[QA] DAO link not working on Point of Interest

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#487]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**

Clicking the DAO link on the map filters is not working

### **Steps to reproduce:**

  1. Open the map -> Filters 
  2. Click the DAO link next to Points of Interest
 
### **Expected behaviour:**
We are taken to the DAO page

### **Current behaviour:**
Link is unresponsive

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x]  100%

### **Severity:**

- [ ] Cosmetic
- [x] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [x] Low

### **Platforms / OS:**
- [ ] Windows 11
- [x] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by davidejensen** [comment]
Already fixed in main
