### ISSUE TITLE
[QA] Deleting text on a map's search doesn't close the places list

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#488]
### **Explorer Alpha build version:**
**0.3.160-main-251ca6c**

### **Issue Description:**

When searching for a place on maps, and then deleting the search text, the list of places on screen doesn't disappear after closing and re-opening the map.

### **Steps to reproduce:**

  1. Open map and go to search
  2. Input a search (ie won) 
  3. Delete the searched text after the list of places appear

### **Expected behaviour:**
The list closes

### **Current behaviour:**
The list remains open

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [x] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/79b66520-9774-4ca6-920f-1c8540ba6655

**Comment by davidejensen** [comment]
Fixed in the past when refactoring the search panel
