### ISSUE TITLE
Some wearables textures are not properly displayed

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#506]
In the backpack, when equipping some particular wearables, the textures seem to be wrong. I was not able to got it on video, but I've seen this hat with 3 different sets of textures while equipping and unequipping.

https://github.com/decentraland/unity-explorer/assets/41490935/000df68f-389c-4e10-bc83-4ee92b056e80

**Comment by anicalbano** [comment]
Fixed with #577
