### ISSUE TITLE
[QA] No image preview of places on maps

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#512]
### **Explorer Alpha build version:**
**0.3.170-main-251ca6c**

### **Issue Description:**

By clicking on places on the map or searching, there is no image preview or thumbnail for the scene.

### **Steps to reproduce:**

  1. Go to the map
  2. Make a search or click on any parcel that has a scene deployed

### **Expected behaviour:**
Previews or thumbnails should be visible

### **Platforms / OS:**
- [ ] Windows 11
- [x] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![Screenshot 2024-04-02 110339](https://github.com/decentraland/unity-explorer/assets/139157886/0cde5a92-72a9-4d9c-af89-0bcfc554d19b)

**Comment by davidejensen** [comment]
Already fixed in main
