### ISSUE TITLE
[QA] Music keeps playing when going away from a scene

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#513]
### **Explorer Alpha build version:**
**0.3.170-main-251ca6c**

### **Issue Description:**

When going on a scene that has music and then going away (even teleporting) the music keeps playing on the back ground.

### **Steps to reproduce:**

  1. Go to a scene of the music festival section and go around until the music starts playing (-64,64)
  2. Leave the scene, go as far as possible, and/or teleport
  
### **Expected behaviour:**
Music stops when going away

### **Current behaviour:**
Music continues
Try on (23,-52)

**Comment by anicalbano** [comment]
Re-opening it with the following comment:

"When I start playing an AudioStream, for example in Genesis Plaza SDK7, in the radio, the audio stays with me and follows me wherever I go for the rest of the session. "

**Comment by popuz** [comment]
A bit more for repro steps: 
- dclexperience.dcl.eth
- the radio is this thing here, on one of the corners of the bar. You can cycle through channels clicking the buttons under the screen. 
Some stations don’t work bc they’re legacy, but at least a couple still do
- if you select one that does play music, it should stop playing when you walk out of the building or back into the clouds
and should DEFINITIVELY stop playing when you go to another scene
but for me it keeps playing for ever even if I jump to another world

![Image](https://github.com/decentraland/unity-explorer/assets/35366872/a3dedb6a-3592-4034-b79e-d3f63e741c0e)
