### ISSUE TITLE
[QA] Auto-walk gets activated with a combination of keys

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#525]
### **Explorer Alpha build version:**
**0.3.170-main-251ca6c**

### **Issue Description:**

While walking and keep the W pressed, and then press enter to write on the chat, the avatar enters a state in which it can walk by itself. It can only be stopped by clicking in world and pressing enter on the chat.

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/880038a9-8ef2-43ab-a185-8ba6b00b2689

**Comment by Kinerius** [comment]
This was fixed with the Interactions branch
