### ISSUE TITLE
SceneFacadeShould.UpdateWithProperIntervals is flaky

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#536]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
[Explorer.DCL.EditMode.Tests.dll.SceneRunner.Tests.SceneFacadeShould.UpdateWithProperIntervals.](https://github.com/decentraland/unity-explorer/runs/23603978797#r0s104)

This test is flakey and needs to be fixed to ensure the failures are not random.

**Comment by dalkia** [comment]
Temporarly commented out
