### ISSUE TITLE
Investigate various frame rate spikes

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#548]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
Various frame rate spikes which appear to be unrelated to flying around the world. The first spike is as you first drop into genesis plaza. 

### **Steps to reproduce:**

  1. Join the plaza
  2. Notice a spike of 1-2s (probably less on better machines)

### **Expected behaviour:**
No spikes! Smooth as butter.

**Comment by olavra** [comment]
Duplicated ticket #563
