### ISSUE TITLE
[QA] Backpack does not save changes

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#561]
### **Issue Description:**
After making some changes in the backpack, clicking close do not change the avatar or refresh it. Closing the game keeps the avatar as it was.

https://github.com/decentraland/unity-explorer/assets/41490935/086e367b-d168-4c63-8c89-28eb6fe7381b

### **Steps to reproduce:**

  1. Enter the backpack
  2. Equip some wearables
  3. Exit the backpack

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by lorux0** [comment]
Could not repro on my side. Could you add details to the steps? Like the urn of the wearables you are trying to equip? How is your profile composed?

**Comment by lorux0** [comment]
Perhaps its fixed by this pr, since you were able to equip incompatible wearables, which end up in possible undesired results.
https://github.com/decentraland/unity-explorer/pull/610

**Comment by anicalbano** [comment]
Fixed in #641
