### ISSUE TITLE
Investigate more performant scriptable terrain culling

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#580]
### **Explorer Alpha build version:**
Main 

### **Issue Description:**
A large portion of our frame time  is spent culling, more specifically the trees. In the capture:

- All other foliage is disabled
- The lod bias is increased, this reduces the overall number of trees so performance is improved

Ultrimately the LOD BIAS does not solve the problem since it is related to the culling of each tree.

![image](https://github.com/decentraland/unity-explorer/assets/296469/e5704e5f-37e6-43b0-acad-e8c69a82a079)
![image](https://github.com/decentraland/unity-explorer/assets/296469/7170a9d8-a1d5-4f9e-a9b1-1b763c9b7f95)

Capture:
https://drive.google.com/file/d/1d77pRMMyi3OnIVkGyEs4myqC6l2ddARp/view?usp=sharing

### **Steps to reproduce:**

  1. Jump in
  2. Disable everything but trees
  3. Streaming OFF
  4. Fire up the profiler
  5. Look at the highest usage of frame time

**Comment by Kinerius** [comment]
The culling is internal to unity, I would not invest much time here since it is already very fast
