### ISSUE TITLE
Investigate location 15,115 with Expensive SkinnedMesh Update

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#582]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
![image](https://github.com/decentraland/unity-explorer/assets/296469/78e0b94d-ca4b-4b48-a195-bcae63836c53)
![image](https://github.com/decentraland/unity-explorer/assets/296469/aef9d801-b4f5-4533-a42b-5435586dcbca)

**Comment by m3taphysics** [comment]
This is a high priority if we have control over the SkinnedMeshRenderer problems - otherwise it will be a scene issue if there are too many.

**Comment by QThund** [comment]
Can't reproduce the issue.
