### ISSUE TITLE
[QA] Scene shader alpha looks wrong

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#584]
### Problem
Most of the textures with any alpha look broken in the scenes.

![image](https://github.com/decentraland/unity-explorer/assets/41490935/c468ffea-5cb2-492c-9ca7-d316572b2a25)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/e6688c38-1d00-4d87-bd02-632654cc7a48)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/e1137cb0-f760-48b1-a272-1bbb0b33d067)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/7f3ad879-4f84-4e84-b15f-0333115d8a32)

**Comment by GBirch33** [comment]
Do we have a location for these issues?
