### ISSUE TITLE
[QA] Debug menu is still visible during splash screen

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#590]
### **Issue Description:**
Hide the debug menu in the splash screen

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Fixed by #659
