### ISSUE TITLE
[QA] Assets of emotes not working when playing in world

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#598]
### **Explorer Alpha build version:**
**0.3191-main-c7268e8**

### **Issue Description:**

By playing emotes that contains assets in world, some of those are not acting according to the avatar's movement.

### **Steps to reproduce:**

  1. This can be tested with, for example, Easel Painter emote

### **Expected behaviour:**
The animation starts and the assets are in place even after looping

### **Current behaviour:**
After the first animation loop, the assets break

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/a76c833d-f1b3-49b4-8b33-0bfa9c319687

**Comment by Kinerius** [comment]
This is the same issue as #520
