### ISSUE TITLE
[QA] Emojis panel must be closed when clicking anywhere else

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#599]
### **Explorer Alpha build version:**
**0.3191-main-c7268e8**

### **Issue Description:**

When opening the emoji pannel and selecting one to chat, if we click some place else, the panel remains on chat screen.

### **Steps to reproduce:**

  1. Open chat and use emojis
  2. Click anywhere else

### **Expected behaviour:**
The panel closes

### **Current behaviour:**
The panel remains open

**Comment by davidejensen** [comment]
Fixed in main
