### ISSUE TITLE
[QA] Incorrect section highlight on main menu

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#649]
### **Explorer Alpha build version:**
**0.3.236-main-ec5ece4**

### **Issue Description:**

When going through the main menu and jumping between Backpack/Map/Settings, it's always the Map section that remains highlighted even if we change section.
In addition, the icon of Settings is not being highlighted either.

### **Steps to reproduce:**

  1. Go to the main menu and go back and forth between the sections

### **Expected behaviour:**
The highlight is on the section we are in 

### **Current behaviour:**
The highlight remains the same

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/7e814552-b9c3-4138-bdde-6b13c6a6a50b

**Comment by davidejensen** [comment]
Fixed in https://github.com/decentraland/unity-explorer/pull/630 @anicalbano
