### ISSUE TITLE
[QA] When teleporting to a high terrain, the spawn point appears to be under it

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#661]
### **Explorer Alpha build version:**
**0.3.236-main-ec5ece4**

### **Issue Description:**

When teleporting to coordinates that are located over a hill type terrain, the avatar appears to be under or inside the hill because it is zero y-position spawning, and it don't take into account terrain height.

### **Steps to reproduce:**

  1. Teleport to **(-104,4)** and observe
  

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/a5c59976-d25e-4ebd-acf6-0cb56b5a15ae)

**Comment by sandrade-dcl** [comment]
Still happening in other cords like `-73,-85`, `-144,-106`.
Reopening the issue...
