### ISSUE TITLE
dclexperience: basketballs do not always appear and do not work / throw

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#678]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
![image](https://github.com/decentraland/unity-explorer/assets/296469/d4ffa743-f952-44ed-badd-325628ee075d)

### **Steps to reproduce:**

  1. Load dclexperience.dcl.eth
  2. Try play some ball

**Comment by NickKhalow** [comment]
fixed by a Misha's PR

**Comment by anicalbano** [comment]
🟢 Basketball game is working. There are other issues on the UI as you can see on the video, but not related to the game's functionality


https://github.com/decentraland/unity-explorer/assets/139157886/2cbf161c-6290-4224-b21a-f819c00c3c22
