### ISSUE TITLE
Livekit spams the chat

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#689]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
For some reason we get random spam, we need to establish if its platforms, or livekit, or our own integration. Or bots.

![image](https://github.com/decentraland/unity-explorer/assets/296469/b5fa62d9-adc3-464b-9674-703c9d6cadd0)

### **Steps to reproduce:**

  1. Have one player join unity-renderer and enter DCLEXperience.dcl.eth
  2. Have one player join explorer-alpha and enter DCLEXperience.dcl.eth
  3. Talk for a while, and notice random spam occurs

**Comment by m3taphysics** [comment]
We had to revert the change for the build

**Comment by NickKhalow** [comment]
We need someone with windows to ensure what's wrong, can you reassign someone?
