### ISSUE TITLE
[QA] Genesis Plaza Road: Street Corner Shifted at Coordinates -7,11

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#693]
### **Issue Description:**
The street corner in Genesis Plaza Road is shifted halfway at coordinates -7,11.

### **Steps to reproduce:**

1. Navigate to Genesis Plaza Road.
2. Locate the street corner at coordinates -7,11.
3. Observe the position of the street corner.

### **Expected behaviour:**
The street corner should be aligned correctly without any shifting.

### **Current behaviour:**
The street corner is shifted halfway from its intended position.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [✅]  100%

### **Severity:**

- [] Cosmetic
- [✅] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [✅ ] Low

### **Platforms / OS:**
- [✅ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![-7,11](https://github.com/decentraland/unity-explorer/assets/146741383/34abfbe0-008a-404d-9fba-abc2fe965db1)

**Comment by anicalbano** [comment]
🟢 Fixed on current version 0.28.0

![image](https://github.com/user-attachments/assets/39ec5c5b-5d9c-4be3-ba95-9c357e5b6a5c)
