### ISSUE TITLE
dclexperience: billboard conversation does not work

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#704]
### **Issue Description:**
The NPCs having a conversation with billboard bubbles does not work. The conversation does not happen, and the bubble does not face the camera

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/75ad566e-523c-4f9d-8f3a-707bcbfa20d1)

Explorer Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/e7379920-8ce3-464e-8c32-9127138aa3e4)

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by NickKhalow** [comment]
<img width="251" alt="image" src="https://github.com/decentraland/unity-explorer/assets/71646502/9c6f1b33-ba48-4a00-9e7c-48bf3473fd12">
I found some inconsistency with SDKTransform and TransformComponent (or maybe it's just an effect from PBBillboard)

**Comment by NickKhalow** [comment]
Fixed in https://github.com/decentraland/unity-explorer/pull/1251
