### ISSUE TITLE
dclexperience: basketball game does not work

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#706]
### **Issue Description:**
Interacting with the balls highlights all the balls at the same time, with multiple tooltips. Interacting with them does nothing

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/2ea20a0f-65ff-4bec-a87b-65a923b559b0)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/e0acb868-c16d-43dd-a1e1-2882e77112e3)

Explorere Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/21c86152-c107-4910-903d-e4f8134271ef)

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
NOTE: this has moved to the south-west

**Comment by NickKhalow** [comment]
It doubles this ticket https://github.com/decentraland/unity-explorer/issues/678

**Comment by NickKhalow** [comment]
UI for the game works incorrectly @m3taphysics

**Comment by anicalbano** [comment]
Comment left on #678
