### ISSUE TITLE
dclexperience: Screens on top of the octopus dont work

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#707]
### **Issue Description:**
Screen are not displaying the images on top of the octopus

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/9bc7a929-2c6b-4d17-8f94-2803ea302161)

Explorer Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/844ec678-6009-4750-8066-4b3ee5137f1a)

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
The screens are there but it seems like the images are darker than the ones @olavra added on the screenshots @popuz 

https://github.com/decentraland/unity-explorer/assets/139157886/3e765833-d876-4bbe-a1f7-7bc0204d6c4a

**Comment by popuz** [comment]
it seems to work fine for me now
![image](https://github.com/decentraland/unity-explorer/assets/35366872/61ae31d3-7c87-40bb-a15f-5bc0e5be171c)

**Comment by anicalbano** [comment]
I still see it a little bit darker on my end, but still is brighter than before
![image](https://github.com/decentraland/unity-explorer/assets/139157886/7d2d9e69-8586-4c4b-ba34-30eecb5db2a3)
