### ISSUE TITLE
dclexperience: social media icons do not trigger web redirect

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#710]
### **Issue Description:**
Clicking on the social media icons do not prompt the URL dialog

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/2be7ef47-04a6-4e22-85b6-befe7e689a5d)

Explorer Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/fbb0d8f0-5462-4f8c-91c5-11048da954a6)

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by sandrade-dcl** [comment]
This issue will be solved when https://github.com/decentraland/unity-explorer/pull/803 is merged.
