### ISSUE TITLE
dclexperience: places and events browser do not work

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#711]
### **Issue Description:**

The events and places browser on top of the clouds do not show any content

Explorer Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/3fab2ead-f081-4c4d-bbe4-fc163db0f915)

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/aefd3321-516c-4369-996d-ea3c63ec10bf)

### **Steps to reproduce:**

  1.
  2.
  3.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
We can currently see the cards on dclexperience, but not the texts:
![image](https://github.com/decentraland/unity-explorer/assets/139157886/9947407a-d411-4060-810e-f9643951e94b)
