### ISSUE TITLE
[QA]  Avatar Preview Duplicates When Equipping and Unequipping Wearables in Backpack

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#725]
### **Issue Description:**
When equipping and unequipping wearables in the backpack and switching tabs to emotes, for example, the avatar preview duplicates, showing both wearables (the one unequipped and the one equipped) superimposed.

### **Steps to reproduce:**
 

1. Open the backpack.
2. Equip or unequip a wearable.
3. Switch to another tab, such as emotes.

### **Expected behaviour:**
The avatar preview should only show the currently equipped wearable without duplication.

### **Current behaviour:**
The avatar preview duplicates, showing both the unequipped and equipped wearables superimposed.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [✅ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [✅] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [✅ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [✅ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/146741383/a881dcce-bd73-44f3-abb3-a186edcdfa7c

![capture_240424_174425](https://github.com/decentraland/unity-explorer/assets/146741383/365ecdb7-a764-44ba-b85c-f922ac84164a)

**Comment by m3taphysics** [comment]
Duplicate of #651
