### ISSUE TITLE
[QA] Emotes Disappear from Backpack

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#726]
### **Issue Description:**
When entering and exiting the backpack, standard emotes (those included by default in the application) vanish from the inventory.

### **Steps to reproduce:**

1. Open the backpack.
2. Observe the presence of standard emotes.
3. Exit the backpack.
4. Reopen the backpack.
5. Notice that standard emotes are no longer visible.

### **Expected behaviour:**
Standard emotes should remain visible in the backpack even after exiting and re-entering it.

### **Current behaviour:**
Standard emotes disappear from the backpack upon exiting and re-entering it.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [✅ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ✅] Medium
- [] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [✅ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [✅ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**

![customAvatars](https://github.com/decentraland/unity-explorer/assets/146741383/d8a19add-5968-4816-8e88-abee9ad61837)

**Comment by m3taphysics** [comment]
@lorux0 is this due to the pagination?

**Comment by lorux0** [comment]
> [@lorux0](https://github.com/lorux0) is this due to the pagination?

I will check
