### ISSUE TITLE
[QA] Deafult position of the drone view is too low

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#737]
The position of the camera when transitioning from 3rd to Drone view is too low. It should be defaulted higher.

Current position
![image](https://github.com/decentraland/unity-explorer/assets/41490935/f4be1fc5-a520-4858-a986-48d46826a924)

Desired position
![image](https://github.com/decentraland/unity-explorer/assets/41490935/62f38e3a-bb24-4527-aa42-54314d2e48fa)

**Comment by Kinerius** [comment]
This is not a bug, this is how @olavra wanted the camera change to work, both cameras point towards the same position after switching between them, if we do what this issue says, I have to pull the camera down artificially
