### ISSUE TITLE
[QA] System messages are being sent as player messages

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#743]
The system messages like teleporting to another location or wrong commands are being sent by the player itself, and that makes it show a speech bubble.

System messages need to be simulated as another player.

![image](https://github.com/decentraland/unity-explorer/assets/41490935/3168329b-3ed3-48cf-b4c6-214c5735f8d4)

**Comment by davidejensen** [comment]
@RominaMarchetti do we have the design for the system messages somewhere in figma?
