### ISSUE TITLE
[QA] Metallic reflection displayed on non-metallic surfaces

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#771]
,Some of the assets rendered in the SDK7 have wrong values of metalness / specular / roughness

How to test:

Go to dclexperience.dcl.eth, check the rocks surrounding the whirpool.

Explorer Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/f9110257-c53b-494b-9bbe-982fdc4d0cdc)

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/b7b23019-b4a7-472f-bc22-243de238539c)

Another example at 59,58

Explorer Alpha
![image](https://github.com/decentraland/unity-explorer/assets/41490935/39d56a23-0cb9-4c7c-8de8-6b0ac3b2968e)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/0aacd224-ea98-4d4f-a99c-75f2db453ce7)

Unity Renderer
![image](https://github.com/decentraland/unity-explorer/assets/41490935/851fdd09-3ce5-4711-9e81-7d5bc5e5aad8)
![image](https://github.com/decentraland/unity-explorer/assets/41490935/71bf12bb-24d4-47f8-b725-a61e24a90d0d)

**Comment by anicalbano** [comment]
Fixed by #814

**Comment by GBirch33** [comment]
![image](https://github.com/user-attachments/assets/f6074659-9c01-41f5-98ec-d2806f9a9439)

**Comment by GBirch33** [comment]
![image](https://github.com/user-attachments/assets/1272231e-23c1-4a32-b5ad-2d49a60ab716)
![image](https://github.com/user-attachments/assets/4c4f00a9-e40e-4401-a41b-c8542fa3cdac)
![image](https://github.com/user-attachments/assets/cdab3fa8-a194-4119-8fdc-5ec697fbd941)
![image](https://github.com/user-attachments/assets/340d5e9f-b4c3-4fa1-aaf2-32b3faae942e)

**Comment by GBirch33** [comment]
Universal Render Pipeline/Lit vs DCL/Scene

The shaders are aligned, as expected.

**Comment by meshr00m** [comment]
Roughness looks ok to me, but i think the metallic values might be off!

![2024-08-07 14_34_06-Explorer](https://github.com/user-attachments/assets/56332822-e06b-45ce-9724-90e75ad1d113)
