### ISSUE TITLE
[QA] Traveling back and forward with other players can end up in an world with no players

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#784]
### **Explorer Alpha build version:**
**0.3.250-main-08f208c**

### **Issue Description:**

Jumping in between different worlds with other players that are doing the same with us can lead us to an empty world where no other players can be seen.

### **Steps to reproduce:**

  1. Jump between worlds with other players

**Comment by m3taphysics** [comment]
Re-test when we fix: #779

**Comment by m3taphysics** [comment]
During playtests this was not happening anymore.
