### ISSUE TITLE
[QA] Other player's avatars are invisible

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#785]
### **Explorer Alpha build version:**
**0.3.250-main-08f208c**

### **Issue Description:**

It can happen with different conditions but sometimes we cannot see other avatar around us but we can still see the nametag going around.

### **Steps to reproduce:**

To repro this, we only need to be with more than two players with us in the same place. It can also be checked by teleporting to other place and then back where we were.

**Comment by m3taphysics** [comment]
During playtests this was not happening anymore.
