### ISSUE TITLE
HUDs in one canvas

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-explorer#790]
Currently we have different UIs that acts as HUD in different canvases. For example: minimap, chat, explore panel opener, emote wheel opener. Because of this design, we cannot build proper layouts in the UI. We cannot align elements. We cannot implement visual aspects in-between features.

The proposal consists on merging all these UIs into a single canvas so we can edit them as a whole in the editor.

**Comment by fcolarich** [comment]
This was addressed already when we added the side bar!
