### ISSUE TITLE
[QA] Nametag spreads outside the chat bubble

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#799]
### **Explorer Alpha build version:**
**0.3.250-main-08f208c**

### **Issue Description:**

When the nametag is long and it has attached the last digits of the user's wallet, the text spreads outside the chat bubble inside the chat window.
In order to see this happen, the text input that the user sends must be shorter than the nametag.

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/4ef87527-e60d-4289-a75f-936f28db48a7)

**Comment by davidejensen** [comment]
I tried to repro this with the exact same name but it doesn't happen for me 😱  @anicalbano 

![Image](https://github.com/decentraland/unity-explorer/assets/4254522/62dbd5e7-5de4-4094-a34b-fcd2e5055cf0)

**Comment by anicalbano** [comment]
@davidejensen could it be related to the screen resolution? Just thinking out loud 🤔
