### ISSUE TITLE
[QA] Map right coordinates are not interactable after teleport

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#812]
If you open the map, teleport to another location and try to mouse over the parcels on the right side of the screen, they can not be interacted.

Apparently the Floating Panel is capturing the input even if its not visible. After deactivating the floating panel in the scene, it works as usual.

**Comment by anicalbano** [comment]
Duplicated https://github.com/decentraland/unity-explorer/issues/769

**Comment by anicalbano** [comment]
Fixed by #630
