### ISSUE TITLE
[QA] Chat messages can be seen globaly

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#821]
### **Explorer Alpha build version:**
**0.3.250-main-08f208c**

### **Issue Description:**

It's possible to read chats of players that are in different coordinates than our own avatar.

### **Steps to reproduce:**

  1. Be with more than one player in the same place and chat
  2. Go to different coordinates (far away)
  3. Observe

### **Expected behaviour:**
We can only read chat and chat with people that are close to us

### **Current behaviour:**
The chat can be read globaly

**Comment by NickKhalow** [comment]
@olavra isn't there 2 types of chat? Global and the local one

**Comment by olavra** [comment]
Nope, for now is only local

**Comment by NickKhalow** [comment]
Ok, island chat will be removed

**Comment by m3taphysics** [comment]
@NickKhalow lets chat about this I do not think we should remove the island chat. There may be an issue with archipelago and how we are reporting the positions and its managing the clusters of users.

**Comment by mikhail-dcl** [comment]
@m3taphysics I don't think we should the island chat either, moreover it may affect User experience pretty badly
