### ISSUE TITLE
NRE when trying to throw the basketball

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-explorer#823]
- Go to `dclexperience` world, go outside, and search the basketball field
- Pick the basket ball up and try to throw it (by left clicking), observe the UI and the NRE at the console.

![Image](https://github.com/decentraland/unity-explorer/assets/7646450/df577a83-1b46-41a8-b9d0-00d572afef71)

![Image](https://github.com/decentraland/unity-explorer/assets/7646450/e7cca538-f613-48ee-a188-e3a5a478f824)

**Comment by mikhail-dcl** [comment]
Should be fixed by https://github.com/decentraland/unity-explorer/commit/1689819b3fdb8293044c5a77a0f7b3388604f093
