### ISSUE TITLE
dclexperience NPC dialog stops unexpectedly

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#833]
### **Issue Description:**

When talking to the Octopus NPC at the bar, the dialog box starts normal but stops and it's not possible to advance any further.
At this point, it's not possible to close the dialog box.

### **Steps to reproduce:**

  1. Talk to the octopus an continue the dialogue until it stops
 
#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/139157886/7324c572-0514-4f3d-9afb-334b1c35399b)

**Comment by sandrade-dcl** [comment]
This issue will be fixed when https://github.com/decentraland/unity-explorer/pull/868 is merged 👍
