### ISSUE TITLE
Show Systems hierarchy

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#85]
Currently, it is impossible to understand the flow of the systems. It will be very problematic to debug.
We need a visualization that will clearly display the current instantiated tree of groups and systems.

There is a built-in node canvas in `UI Toolkit`, consider using it

**Comment by m3taphysics** [comment]
Fixed with the introduction of [Arch Visualiser](https://github.com/m3taphysics/Arch.SystemGroups.Visualiser)

![image](https://github.com/decentraland/unity-explorer/assets/296469/6b902e78-2efb-49a3-b76c-74c458f59e0f)
