### ISSUE TITLE
NPC button options ignored

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-explorer#876]
### **Issue Description:**
When talking to an NPC in Genesis Plaza SDK7 with the new explorer, I can't select the No option with my cursor. I can press F to select it, but if I click on the button the dialog won't progress.

### **Steps to reproduce:**

  1. Go to dclexperience.dcl.eth
  2. Go downstairs and talk to the octopus, till he asks you if you want to learn more
  3. Click on the NO button, it will keep loading the same screen again and again. If I press the F key as a short cut, it does work.

This should also be easier to observe in the Goerli Plaza scene Simple NPC
https://github.com/decentraland/sdk7-goerli-plaza/tree/main/Simple-NPC

### **Expected behaviour:**

I should move on to another dialog option

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**

On the Explorer Alpha only

**Comment by LucasLioyQA** [comment]
QA checked: 

https://github.com/decentraland/unity-explorer/assets/146749313/ffb3f6e9-494b-45e4-a4c3-7aa28161aa0b
