### ISSUE TITLE
No sound on the Zenquencer

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-explorer#878]
### **Explorer Alpha build version: 0.3.335-g8f637032-main**

This old musical contraption doesn't emit any sound
<img width="1690" alt="Screenshot 2024-05-01 at 3 40 55 PM" src="https://github.com/decentraland/unity-explorer/assets/3507907/6e241de0-fce6-4659-aab9-885754a5f027">

### **Steps to reproduce:**

  1. Go to dclexperience.dcl.eth
  2. Walk out to -1, 5
  3. Click on some of the tiles to activate them
  4. Click on any of the blocks on the panel to start playing a loop that uses those tiles as musical notes
   
<img width="552" alt="Screenshot 2024-05-01 at 3 43 57 PM" src="https://github.com/decentraland/unity-explorer/assets/3507907/3548efa5-f639-4ce2-8596-db4976276961">

### **Expected behaviour:**

I should hear a soothing glassy sound each time I activate on of the notes on the sequencer, and also when I click the panel to turn it on.

### **Current behaviour:**

I see the animations happen, the sequence is working fine, but I don't hear any sounds for the musical notes being played

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ x ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [ x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
@anicalbano can we verify this works properly in unity renderer ?

**Comment by nearnshaw** [comment]
@m3taphysics @anicalbano I can confirm that if I visit dclexperience.dcl.eth with the old client, the sound does work well there
Each time activate a droplet on the grid or play the loop, I hear the sound (when the droplet hits the water's surface)

**Comment by anicalbano** [comment]
I am currently unable to hear the sounds on latest version 0.3.402-g7a23dc7e-main
