### ISSUE TITLE
metadyne: gun does not work/attach

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#900]
### **Issue Description:**
Clicking and trying to use the gun does not work:
![image](https://github.com/decentraland/unity-explorer/assets/296469/d1cf8b0c-fffa-4c6b-9a81-9d8b9b6a8eb4)

Unity renderer:
![image](https://github.com/decentraland/unity-explorer/assets/296469/e2e58e70-2155-4336-9727-0872075045e0)

### **Steps to reproduce:**

  1. Goto genesis first
  2. Then /goto metadynelabs
  3. Pick up the gun

**Comment by Kinerius** [comment]
Im re opening this one since I reverted the fix
