### ISSUE TITLE
[QA] Avatars are not being hidden when entering Metadynelabs

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#908]
### **Explorer Alpha build version:**
**0.3.335-g8f637032-main**

### **Issue Description:**

Metadyne must be single player only, which means that all other avatars around ours should be hidden. Currently, it's possible to see the other avatars on the scene with us.

### **Steps to reproduce:**

  1. Go to metadynelabs with other players

### **Expected behaviour:**
We only see ourselves on first person

### **Current behaviour:**
We can see other players

**Comment by m3taphysics** [comment]
Going to close this for now as we saw this happen in Unity-Renderer
