### ISSUE TITLE
Angzaar Outpost does not load

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#909]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
Jumping to location: 0, -91 does not work

![image](https://github.com/decentraland/unity-explorer/assets/296469/23f51c4d-171f-4fac-9200-f19856e0caaf)

### **Steps to reproduce:**

  1. Jump to  0, -91

**Comment by anicalbano** [comment]
The white screen issue is not happening anymore, but still the SDK7 scene is empty

![image](https://github.com/decentraland/unity-explorer/assets/139157886/a78183b8-fca7-4bee-9580-c466bcdfbefa)
