### ISSUE TITLE
[QA] [Graphics] Orange Grass Overlaps Scene

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#911]
### **Explorer Alpha build version:**
v0.3.335-g8f637032-main

### **Issue Description:**
In the scene Mocaverse Clubhouse (101,-110), orange grass appears overlapped and on top of the green grass, causing a visual clash.

Issue can be reproduce also in:
- Guangxi Culture and Art Center (101,-116)
- Amsterdam (16,99)
- New scene (128,-16)
- Louis XIV Tower (107,-123)
- 

### **Steps to reproduce:**

1. Launch the explorer
2. Jump in to any of the coordanates given on the description
3. Observe the rendering of grass textures.
4. Repeat step 1-3 with the other locations

### **Expected behavior:**
Orange grass should not be visible in the scene.

### **Current behavior:**
The orange grass overlaps the green grass in the scene, resulting in a visual clash and disrupting the overall appearance.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [❌]  100%

### **Severity:**

- [ ] Cosmetic
- [ ❌] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [❌ ] Low

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![image](https://github.com/decentraland/unity-explorer/assets/146741383/e0ec151d-bc67-40fc-942d-86644d5553ec)

![07 05 2024_18 44 25_REC](https://github.com/decentraland/unity-explorer/assets/146741383/32fcf1fb-1c14-46c1-a056-63a1225eaa34)

![amsterdam](https://github.com/decentraland/unity-explorer/assets/146741383/24af8826-84b1-4f88-a676-b89d6f27b366)

![NEWSCENE](https://github.com/decentraland/unity-explorer/assets/146741383/3ef397d6-d87f-4b4d-befa-b38205d6d6f3)

![louisXIV](https://github.com/decentraland/unity-explorer/assets/146741383/fd105a55-d52b-451b-9a4a-0c68704000ff)

**Comment by m3taphysics** [comment]
We need to integrate the world manifest
