### ISSUE TITLE
dclexperience: the dialog won't disappear 

### ISSUE THREAD

**Issue by NickKhalow** [decentraland/unity-explorer#918]
repro:
- go to dclexperience
- meet the octo
- go away 
- see the message won't dissabpper

<img width="1715" alt="image" src="https://github.com/decentraland/unity-explorer/assets/71646502/3028baa4-4047-45eb-8703-019ec3a7e2ae">

**Comment by LucasLioyQA** [comment]
Issue still takes place in alpha: 

https://github.com/decentraland/unity-explorer/assets/146749313/34886931-c3cf-4728-b44b-e0cdc1b36a3e

While it doesn't take place in explorer:

https://github.com/decentraland/unity-explorer/assets/146749313/b17f2eaf-d83f-4d94-a2e7-76b58a1c848c

**Comment by LucasLioyQA** [comment]
QA fixed: 


https://github.com/decentraland/unity-explorer/assets/146749313/1c0f66be-ed62-4597-9b94-d98393093171
