### ISSUE TITLE
sometimes you do not get connected to the same island room

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-explorer#920]
### **Explorer Alpha build version:**
Main

### **Issue Description:**
If you gather many people and jump to a location such as -150,0 that has no scene room 

### **Steps to reproduce:**

  1. Gather 7-8 avatars 
  2. All meet in genesis plaza
  3.  Jump to -150, 0

Notice people can be connected to different island rooms

**Comment by anicalbano** [comment]
Unable to repro since the ticket was created
