### ISSUE TITLE
metadyne: unable to close UI

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-explorer#931]
### **Explorer Alpha build version:**
**0.3.335-g8f637032-main**

### **Issue Description:**

When entering Metadyne Labs, if we open the UI (for example, the Ranking) and move through it, it's not possible to close the screen later. In order to fix the problem, we need to go to other place and back to Metadyne.

### **Steps to reproduce:**

  1. Go to Metadyne, open the ranking and navigate through the pages
  2. Attempt to close it

### **Expected behaviour:**
We can close the modal and keep going around the world

### **Current behaviour:**
It's not possible to close it

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/45e254ce-16c2-4376-845f-791b82cbaf17

**Comment by sandrade-dcl** [comment]
This issue should be fixed by #1179
