### ISSUE TITLE
dclexperience: some dialogues with NPCs (mainly Simone- Aisha- Doge) do not load any text at all

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#935]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Some dialogues with NPCs do not load any text at all (like with Simone, Aisha, Doge, etc). They seem to be the ones which have the look and feel shown on these screenshots. These dialogues load the text in explorer, but not in alpha:

Explorer: (ok)

![explorer aisha](https://github.com/decentraland/unity-explorer/assets/146749313/8c1285b7-c255-4c3b-93c0-5dfe4c2a0be7)

Alpha: (issue)

![dialogue with aisha no text](https://github.com/decentraland/unity-explorer/assets/146749313/e9fd05e5-20a5-4fe6-b1ba-1d40aeed9fe1)

### **Steps to reproduce:**

  1.STart the game in DCL EXP in alpha
  2. Talk to SImone, Aisha or Doge

### **Expected behaviour:**

Dialogue should be triggered

### **Current behaviour:**

No text is triggered

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ x] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
This may be related to the changes @mikhail-dcl is working on but we should investigate.

**Comment by sandrade-dcl** [comment]
### Status update
After several fixes mostly related to the `fetch` API (that solves the connection between our client and the `colysseus` js framework), I have reached the point where the flow is being cut in some point in the `WebSocket` side. The websocket is apparently created correctly in the `WebSocketApi` API but, although it keeps waiting, we never receive the data corresponding to the NPC's conversation and I don't still know the reason.
