### ISSUE TITLE
dclexperience: F button does not skip any dialogue at all

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#936]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

 F button does not skip any dialogue at all. This also takes place in explorer (browser):

![skipping dialogues doesnt work](https://github.com/decentraland/unity-explorer/assets/146749313/d60a4b12-8180-4dd6-9068-834b0b0ed4a9)

### **Steps to reproduce:**

  1.Talk to any NPC
  2. Check it is possible to press F to skip the dialogue
  

### **Expected behaviour:**

When pressing F, the dialogues isnt skipped

### **Current behaviour:**

Dialogue should be skipped after pressing F

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ x] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
@anicalbano can you retest

**Comment by anicalbano** [comment]
It's currently working!

https://github.com/decentraland/unity-explorer/assets/139157886/1b4a80ec-1bc1-4ea6-b123-315bf797a2b5
