### ISSUE TITLE
[QA] Chat error messages: text overlapping with some long messages when getting errors

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#937]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

When getting an error message after having sent a long text, there is text overlapping on the chat message:

![image](https://github.com/decentraland/unity-explorer/assets/146749313/47c06d4b-a740-484e-bd2a-2353259f8b40)

### **Steps to reproduce:**

  1. Send this message on the chat skipping a line to get an error:

/world dclexperience.dcl.eth

Skip a line like this:

![image](https://github.com/decentraland/unity-explorer/assets/146749313/0e180d37-da7b-4cd3-aa74-89690939924b)

### **Expected behaviour:**

Error message shown on chat shouldn't have text overlapping

### **Current behaviour:**

There is text overlapping

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [X ]  100%

### **Severity:**

- [ ] Cosmetic
- [X ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [X ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by davidejensen** [comment]
Could be fixed in main with the recent system messages change

**Comment by davidejensen** [comment]
Closing, not happening to me on main with the recent changes

![Image](https://github.com/decentraland/unity-explorer/assets/4254522/aee4e317-43bf-4474-8b83-6974b2a8ecef)
