### ISSUE TITLE
dclexperience Position -7, 7 : Bella's dialogue stops all of a sudden and dialogue box cannot be closed

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#940]
### **Explorer Alpha build version:**

 (Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Position -7, 7 : Bella's dialogue stops all of a sudden:

![bella robot dialogue doesnt finish](https://github.com/decentraland/unity-explorer/assets/146749313/8698d512-9971-4dd0-a251-0ac447235840)

And dialogue box cannot be closed, even if the user runs far away: 

![bella message is on screen even after running away](https://github.com/decentraland/unity-explorer/assets/146749313/684b4bd9-d1ac-469d-aa29-25e31055f4fc)

### **Steps to reproduce:**

  1. Go to position -7, 7
  2. Talk to Bella
  

### **Expected behaviour:**

Dialogue should be ok and should finish

### **Current behaviour:**

Dialogue is interrupted and dialogue box cannot be closed

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ X]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ X] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [X ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
This may be related to the issue @mikhail-dcl is working on

**Comment by sandrade-dcl** [comment]
@anicalbano can you retest?
