### ISSUE TITLE
[QA] When being teleported and appearing in new position, user is not centered and is placed in the same position in which the avatar was before being teleported 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#941]
### **Explorer Alpha build version:**

 (Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

When being teleported and appearing in new position, user is not centered and is placed in the same position in which the avatar was before being teleported:

https://github.com/decentraland/unity-explorer/assets/146749313/5d5e2b16-7cd9-4ad2-8f43-776595175935

### **Steps to reproduce:**

  1. Place your avatar looking down
  2. Go to /world dclexperience.dcl.eth

### **Expected behaviour:**

Avatar should be centered when getting to new position

### **Current behaviour:**

Avatar  is placed in the same position in which the avatar was before being teleported 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment]
For this we need to ensure we adopt the right position AND rotation for teleportation (when using the scenes spawn point). @sandrade-dcl can help.

**Comment by sandrade-dcl** [comment]
@lorux0 let me know when you start with this fix, I can explain you how we have currently implemented the teleportation to the spawn points and how we should manage the "look at" rotation of the player (that is currently missing) 👍
