### ISSUE TITLE
dclexperience: when jumping and falling, almost nothing can be heard on Alpha build compared to explorer

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#942]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

When jumping and falling, almost anything can be heard on Alpha build.

Check explorer: 

https://github.com/decentraland/unity-explorer/assets/146749313/28a2f00e-af2c-45a7-9944-b21e82b771f0

And now Alpha: 

https://github.com/decentraland/unity-explorer/assets/146749313/f8f30493-b1ec-435f-9dcb-065425077921

### **Steps to reproduce:**

  1. Start and jump and soon as you start
 
### **Expected behaviour:**

Sounds should be triggered when falling as in explorer

### **Current behaviour:**

when jumping and falling, almost anything can be heard on Alpha build

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Working on current main. There is a cut on the radio's audio but it's an issue on my side

https://github.com/decentraland/unity-explorer/assets/139157886/f2f1452e-2d60-4a74-b29b-745104941f99
