### ISSUE TITLE
dclexperience: elevator at - 6, -7 doesn't always work in Alpha, while it always does in Explorer

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#945]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

dclexperience: elevator at - 6, -7 doesn't always work in Alpha, while it always does in Explorer

Explorer: 

https://github.com/decentraland/unity-explorer/assets/146749313/139891c4-e083-4270-954c-4eccb823c37c

Alpha: 

https://github.com/decentraland/unity-explorer/assets/146749313/5a3f9d24-6829-46e9-99a8-487481dbca79

### **Steps to reproduce:**

  1. Go to -6, -7
  2. Try to use the elevator

### **Expected behaviour:**

Elevator should work in Alpha as it does in Explorer

### **Current behaviour:**

Elevator doesn't always work in Alpha

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [x ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [X ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [X ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by LucasLioyQA** [comment]
@m3taphysics 

Issue still takes place on my end on 0.3.402-g7a23dc7e-main build: 

https://github.com/decentraland/unity-explorer/assets/146749313/450e81ea-8619-481c-8842-ef3181dcec59

**Comment by aixaCode** [comment]
@LucasLioyQA Could you re-check if this still happens on latest build?

**Comment by LucasLioyQA** [comment]
@aixaCode Issue seems to be ok and elevator seems to be working properly now: 

https://github.com/decentraland/unity-explorer/assets/146749313/5b4ea98c-61ae-44e3-bf45-78890c58ff9f

As a result, this issue will be closed.
