### ISSUE TITLE
dclexperience: elevator at - 6, -2 doesn't always work in Alpha, while it always does in Explorer

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#946]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Elevator at - 6, -2 doesn't always work in Alpha, while it does always in Explorer

Explorer (it works): 

https://github.com/decentraland/unity-explorer/assets/146749313/2d70731d-e992-431f-b52e-7a4d70567592

Alpha (it doesn't work):

https://github.com/decentraland/unity-explorer/assets/146749313/9b13a17b-d027-4f9c-8c6b-0f2081d0e4d8

### **Steps to reproduce:**

  1. Go to -6, -2
  2. Try the elevator

### **Expected behaviour:**

Elevator should work in Alpha

### **Current behaviour:**

Elevator doesnt always work in Alpha

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [x ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [x ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [x ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by LucasLioyQA** [comment]
@m3taphysics 

Issue still takes place on my end on 0.3.402-g7a23dc7e-main build: 

https://github.com/decentraland/unity-explorer/assets/146749313/668c618c-9980-4192-be56-637cf0b36d13

**Comment by aixaCode** [comment]
@LucasLioyQA Could you check on latest build?

**Comment by LucasLioyQA** [comment]
@aixaCode Even though the elevator works now, there are some issues when using the elevator to go back down again: elevator falls faster than the avatar and avatar ends up falling on the air: 

https://github.com/decentraland/unity-explorer/assets/146749313/f5e5ce6f-b7b9-4f95-97a8-b2051ac6ec35

**Comment by m3taphysics** [comment]
The issue above is unrelated
