### ISSUE TITLE
dclexperience: robot's dialogue at -2-7 doesnt finish and dialogue box cannot be closed

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#947]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Robot's dialogue at -2-7 doesn't finish and dialogue box cannot be closed:

![robot at -2-7 dialogue doesn't finish and dialogue box cannot be closed](https://github.com/decentraland/unity-explorer/assets/146749313/23a24a35-a8ec-49fd-93b9-b82bf98d818e)

### **Steps to reproduce:**

  1. Go to -2, -7
  2.Talk to the robot 

### **Expected behaviour:**

DIalogue should finish well

### **Current behaviour:**

Dialogue is interrupted and dialogue box cannot be closed

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by sandrade-dcl** [comment]
@anicalbano can you retest?

**Comment by LucasLioyQA** [comment]
@sandrade-dcl  now it lets you advance a little bit more but it fails later on in the conversation if you choose more options to know more: 

https://github.com/decentraland/unity-explorer/assets/146749313/4060cde3-e535-46d6-9af2-4e833b673683

**Comment by anicalbano** [comment]
On my end and latest build, is working as expected. 

https://github.com/decentraland/unity-explorer/assets/139157886/071f128d-c84c-4ee6-9a0a-8439075cd831
