### ISSUE TITLE
dclexperience: cableway at 5,1 doesn't always work in Alpha, while it always does in Explorer

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#948]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

Cableway at 5,1 doesn't always work in Alpha, while it always does in Explorer

Explorer: 

https://github.com/decentraland/unity-explorer/assets/146749313/69f5f8ab-32fe-4717-b254-d06366e11000

Alpha: 

https://github.com/decentraland/unity-explorer/assets/146749313/41dfd0b3-7dfc-43e6-8158-9abb3fd9535c

### **Steps to reproduce:**

  1. Go to 5, 1
  2. Get into cableway
  

### **Expected behaviour:**

It should always work in Alpha

### **Current behaviour:**

It doesn't always work in Alpha

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [X ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [X ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [X ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [X ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
The elevator to reach the cableway is not working  **0.3.402-g7a23dc7e-main**

https://github.com/decentraland/unity-explorer/assets/139157886/41a19ba5-0396-4cb3-acff-d4a65fe6598d
