### ISSUE TITLE
dclexperience Position 9, -2 : Ron's dialogue stops all of a sudden and dialogue box cannot be closed

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#951]
### **Explorer Alpha build version:**

(Version 0.3.335-g8f637032-main
(windows)

### **Issue Description:**

Ron's dialogue stops all of a sudden and dialogue box cannot be closed:

![ron 9 -2 dialogue stops](https://github.com/decentraland/unity-explorer/assets/146749313/e379139e-7988-4802-b7d1-2243486ff535)

### **Steps to reproduce:**

  1. Go to 9, -2
  2. Talk to the robot
 

### **Expected behaviour:**

Dialogue should be properly triggered

### **Current behaviour:**

Dialogue stops all of a sudden

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Fixed on latest

https://github.com/decentraland/unity-explorer/assets/139157886/ade035fa-49f4-46ef-81f7-440e5aa22a00
