### ISSUE TITLE
dclexperience Positions 1, 6 and 2, 5 : dialogues stop all of a sudden and dialogue boxes cannot be closed 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#952]
### **Issue Description:**

dclexperience Positions 1, 6 and 2, 5 : dialogues stop all of a sudden and dialogue boxes cannot be closed :
![1 - 6  dialogues stop working](https://github.com/decentraland/unity-explorer/assets/146749313/3698dca0-87df-4d4f-9f28-cfa1d1549519)

![2 -5 dialogues](https://github.com/decentraland/unity-explorer/assets/146749313/5cd7a828-a5bd-4a68-87a2-9b45d800260c)

### **Steps to reproduce:**

  1. Go to 1,6 and 2, 5 and talk to everyone

### **Expected behaviour:**

Dialogues should work properly

### **Current behaviour:**

Dialogues stop all of a sudden and dialogue boxes cannot be closed 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [ x] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Fixed on current build

https://github.com/decentraland/unity-explorer/assets/139157886/657d9b23-13ea-433c-bfa2-5d321e427f37
