### ISSUE TITLE
dclexperience: text and bilboards visibility issues for Places and Events Carousel

### ISSUE THREAD

**Issue by popuz** [decentraland/unity-explorer#964]
### **Explorer Alpha build version:**
![image](https://github.com/decentraland/unity-explorer/assets/35366872/c988f6fe-a60a-4dc9-bdc8-29a47ac86f68)

### **Steps to reproduce:**

  1. `/goto dclexperience`
  2. Look on the Places and Events Carousel and try to scroll it with buttons
  3. Observe that texts and billboard outside of it are still visible

### **Expected behaviour:**
Texts and billboards outside of the Carousel are hidden

### **Current behaviour:**
Texts and billboards outside of the Carousel are visible

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [x] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [x] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
Seems like there is still an issue with the interactable letters:
![image](https://github.com/decentraland/unity-explorer/assets/139157886/94685ed9-015e-46a7-8f42-32ba1ee3892b)
