### ISSUE TITLE
[QA] Metadyne: Missing SFX for UI Interactions and Narrator's Voice in Game

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#969]
### **Explorer Alpha build version:**
v0.3.335-g8f637032-main

### **Issue Description:**
Certain UI options, such as ranking, rewards, settings, and home, lack sound effects (SFX) when interacted with in the game. Additionally, the narrator's voice is also missing.

### **Steps to reproduce:**

1. Goto genesis
2. /goto metadynelabs
3. Go to the UI options section.
4. Interact with the ranking, rewards, settings, and home buttons.

### **Expected behavior:**
- Each UI option (ranking, rewards, settings, and home) should trigger appropriate sound effects (SFX) when interacted with.
- The narrator's voice should be audible.

### **Current behavior:**
- The UI options mentioned lack sound effects (SFX) when interacted with.
- The narrator's voice is missing.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [❌ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [❌  ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [❌  ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [❌  ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**

**Explorer-Alpha:**
https://github.com/decentraland/unity-explorer/assets/146741383/66f0941d-ca0d-4ed5-976d-e54197a9f138

**Unity-Explorer:**

https://github.com/decentraland/unity-explorer/assets/146741383/27f1f422-e4ed-4766-975b-151d096278b1

**Comment by anicalbano** [comment]
Fixed in current build 0.3.402-g7a23dc7e-main
