### ISSUE TITLE
dclexperience: first elevator at 0, 1 doesn't always work in Alpha, while it always does in Explorer

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#970]
### **Explorer Alpha build version:**

Version 0.3.335-g8f637032-main
(windows))

### **Issue Description:**

First elevator at 0, 1 doesn't always work in Alpha, while it always does in Explorer:

![first elevator doesnt always work on 1 0](https://github.com/decentraland/unity-explorer/assets/146749313/ef7a9d8d-e546-413b-9c40-6e79de0d8a10)

### **Steps to reproduce:**

  1. Go to 0 , 1 
  2. Try to use the elevator 

### **Expected behaviour:**

It should always work

### **Current behaviour:**

It doesn't always work

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [x ]  < = 75%
- [ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [x ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by anicalbano** [comment]
🟢  Fixed on main
