### ISSUE TITLE
[QA] [Emotes 2.0] some emotes are not working for a specific wallet user

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#990]
### **Issue Description:**
Certain Emotes 2.0 are not working for me, despite attempts to clear cache. The issue seems to be isolated to me and has persisted across multiple versions, including previous ones.

Wallet Address: 0xc9C29AB98E6BC42015985165A11153F564e9F8C2

### **Steps to reproduce:**

  1. Launch Explorer Alpha
  2. Log in with the specified wallet address.
  3. Attempt to use the affected Emotes 2.0.

### **Expected behavior:**
All Emotes 2.0 should function correctly without any issues.

### **Current behavior:**
Some emotes 2.0 cannot be triggered. 

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [❌]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [❌ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [❌ ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/146741383/5ed7c4ee-4957-471b-b857-c38eb5d34f5a

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by lorux0** [comment]
It seems to be an asset bundle cache issue. They are working fine on latest versions of the entity
