### ISSUE TITLE
[QA][Animation] Planting seeds emote animation discrepancy

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#998]
### **Explorer Alpha build version:**
v0.3.335-g8f637032-main

### **Issue Description:**
The "Planting seeds" emote fails to display the same animation as in the production environment. In the production version, flowers progressively grow while the avatar ascends from a squatting position to standing upright.

### **Steps to reproduce:**

  1. Launch the explorer
  2. Press the B key to trigger the emote wheel.
  3. Select the "Planting seeds" emote.

### **Expected behavior:**
https://github.com/decentraland/unity-explorer/assets/146741383/23a28803-644a-4a30-ad93-9c2eae6a51e8

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/2deed158-4990-4acd-bb7b-6d7d42860390

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ❌ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ❌] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ ❌] Low

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
windows 11. Gen Intel(R) Core(TM) i7-12650H

**Comment by Kinerius** [comment]
Please test again but clear asset bundles cache first
